### ISSUE TITLE
White colour for unread count?

### ISSUE THREAD

**Issue by orschiro** [martinrotter/rssguard#101] opened 2017-03-07 11:43 UTC
Dear @martinrotter, 

May I suggest to use a white colour for the unread count?

The blue on orange does not fit nicely, I think. 

![image](https://cloud.githubusercontent.com/assets/170947/23655018/aa32b364-0333-11e7-9d60-f6cb6f1dbdff.png)

**Comment by martinrotter** [comment] 2017-03-07 12:23
There is for sure room for big improvements in the UX of the tray icon and RSS Guard overally.

**Comment by orschiro** [comment] 2017-03-07 15:28
May I ask where in the code you set the blue colour for the unread count
number?

**Comment by martinrotter** [comment] 2017-03-08 05:01
[Here](https://github.com/martinrotter/rssguard/blob/master/src/gui/systemtrayicon.cpp#L122).

**Comment by martinrotter** [comment] 2017-03-08 06:26
The fact is that numbers are normally black, they are blue when there are NEW unread messages.

I will update icon to more simple one, so that number is clearlier visible.

**Comment by orschiro** [comment] 2017-03-08 06:54
That's great. Thank you!

Let me know if I can help somehow. :-)

**Comment by martinrotter** [comment] 2017-03-08 07:34
You can check latest development build. I added new icons there. Let me then know if the issue is resolved. The white color looks very unreadable in fact. I tried to change it to black color everytime. Looks nicer. Test and let me know.
![bez nazvu](https://cloud.githubusercontent.com/assets/1255302/23694424/1874409e-03da-11e7-8aee-220aabb49ee5.png)

**Comment by orschiro** [comment] 2017-03-08 08:04
Judging from your screenshot, it looks very nice!

Unfortunately, I don't know how to install it from the development build on
Ubuntu.

**Comment by martinrotter** [comment] 2017-03-08 08:52
There is not dev build for Ubuntu, unless you want to build RSS Guard yourself. Sorry. :) But I will publish 3.4.0 in a week.

**Comment by orschiro** [comment] 2017-03-08 09:56
Alright. I will wait then.

Thank you so much! :-)

**Comment by martinrotter** [comment] 2017-03-14 12:32
Version is released, please check and let me know if I can close this.

**Comment by orschiro** [comment] 2017-03-14 13:20
Thank you, Martin!

I might have overlooked it but how can I install the latest release on
Ubuntu 16.10?

Yours,

Robert

**Comment by martinrotter** [comment] 2017-03-15 07:44
I am not sure who or which repo packages RSS Guard for Ubuntu.

Is [this](https://www.ubuntuupdates.org/package/getdeb_apps/yakkety/apps/getdeb/rssguard) it?

**Comment by orschiro** [comment] 2017-03-15 08:30
Yes, you found it.

Thank you so much!

I just installed the latest version and I really like the new icons.

Thank you. :-)

**Comment by orschiro** [comment] 2017-03-15 08:32
How can I add this [1] link to the wiki page [2]?

[1] https://www.ubuntuupdates.org/package/getdeb_apps/yakkety/apps/getdeb/rssguard
[2] https://github.com/martinrotter/rssguard/wiki/Official-downloads

**Comment by martinrotter** [comment] 2017-03-15 08:55
I will.

**Closed by martinrotter** 2017-03-15 08:55 UTC
Labels: Component-GUI, Status-Accepted, Type-Enhancement

**Comment by martinrotter** [comment] 2017-03-15 09:01
Added.

**Comment by orschiro** [comment] 2017-03-15 09:02
Thanks!
