### ISSUE TITLE
config and database file location issue

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#50] opened 2016-08-17 16:17 UTC
#### Brief description of the issue.

Config and database file will be created in system Program Files folder if you choose option to run RSS Guard once installation finish. Windows 8.1 x64, RSS Guard 3.3.2.

#### How to reproduce the bug?

1.  Install RSS Guard on default location, in system Program Files folder  (e.g. C:\Program Files (x86)\RSS Guard).
2. Make sure option "Run RSS Guard Checked portable" is checked.
3. Finish

#### What is the expected result?

Config and database file are created in .rssguard folder in user folder

#### What actually happened?

Config and database file are created in RSS Guard folder in Program Files.

**Comment by martinrotter** [comment] 2016-08-18 04:51
This happens if you have write permissions in that `Program Files\RSS Guard` folder which is usually not the case.

RSS Guard checks if folder it was launched from is writtable. If it is, then RSS Guard assumes it can run in "portable" mode and runs in portable mode. If the folder is not writtable, RSS Guard will use "home" folder, which is `Users\<user>\......` on Windows.

I realized this scenarion when desiging this functionality and I thought that having write permissions in `Program Files\......` indicates a bug in the system setup, not in RSS Guard. I might wrong though. Will check the algorithm.

**Comment by martinrotter** [comment] 2016-08-18 04:53
Problem is in the installer, rather than in the RSS Guard. The installer requests UAC admin rights when started. So also RSS Guard started by the installer is run as admin, which is wrong.

**Comment by martinrotter** [comment] 2016-08-18 05:01
Bug reproduced -> it influences all installers. Question is how to really well fix this.

I will definitely fix the installer, so that it does not launch RSS Guard as admin.

**Comment by martinrotter** [comment] 2016-08-18 06:49
OK. Installer now launches RSS Guard in non-admin mode. Also, I discovered some related bug when RSS Guard falsely thought he can run in portable mode while it really could not due to folder permissions.

So, this is now from my side probably fixed.

RSS Guard (and other apps) is really not meant to be run as root (admin).

Fixed in 9b886427ef5b9223255c1f41f3178ebd8dcf4776.

**Closed by martinrotter** 2016-08-18 06:49 UTC
Labels: deployment, desktop-integration

**Comment by blackarcher21** [comment] 2016-08-18 06:53
thank you :)
