### ISSUE TITLE
[BUG]: Read status is not synced from nextcloud server

### ISSUE THREAD

**Issue by chrbayer** [martinrotter/rssguard#338] opened 2021-01-18 10:04 UTC
#### Brief description of the issue.

If a message has been marked unread on the server, this change is not synced to the rssguard database so it is impossible to read only the messages have not been read by a different client on a mobile e.g.

#### How to reproduce the bug?

1. Snyc messages with nextcloud server
2. Mark a message as read on the server
3. Sync again with the server, the rssguard message is not marked as read

#### What was the expected result?

I expect to sync the read status too, so that it is possible to read the messages with multiple clients in multiple devices.

#### What actually happened?

The messages with read status on the server are kept as unread in rssguard after syncing

#### Other information

* OS: Ubuntu 20.10, Arm64
* Desktop Environment: Mate
* RSS Guard version: 3.8.4 (flatpak)

**Comment by martinrotter** [comment] 2021-01-18 11:15
Additional questions:
* What exact version of Nextcloud/News have you installed on your server?
* Did you noticed this error in previous RSS Guard versions?

**Comment by martinrotter** [comment] 2021-01-18 11:25
UPDATE: I did test it and I am not able to reproduce the problem: https://www.youtube.com/watch?v=2rXlKrp7eaY

It just works here so I suspect it could be something perhaps related to specific News server version. Anyway, provide some extra info as state in previous post, thank you. :)

**Comment by chrbayer** [comment] 2021-01-18 22:13
Thanks for looking at this!

What exact version of Nextcloud/News have you installed on your server?
I'm using the latest stable versions, Nextcloud 20.0.5 and News 15.1.1

Did you noticed this error in previous RSS Guard versions?
This is the first try of rssguard, so i have no experience with older versions

Could you share RSS Guard debug/standard output log? Especially when performing step 3.
The logfile of an update is attached.

[log.txt](https://github.com/martinrotter/rssguard/files/5832586/log.txt)

Don't you have download unread messages only checked in RSS Guard's nextcould news account settings dialog?
Yes, I have this checkbox checked because it tries to download a lot of messages if this is removed (after hours it was not completed) and nextcloud news does not seem to purge anything at the moment

**Comment by martinrotter** [comment] 2021-01-19 06:24
@chrbayer 
>Yes, I have this checkbox checked
This is the source of your issue. If this checkbox is checked then RSS Guard really does what it says it will do: *it will only download (and sync) messages which are unread on the server* and no other messages.
Therefore, if you mark your message as READ via web server GUI and then want to receive this change on the RSS Guard too, you cannot have the checkbox checked.

Your say
> it tries to download a lot of messages if this is removed (after hours it was not completed) 
How many feeds do you have added in your News instance? How many total messages (including all read etc.) usually are there in your average feed?

We should cope with the "slowness" problem, but also make sure (maybe with some smaller feed) that if you UNcheck the mentioned checkbox that all works as expected - in other words this reported bug is not in fact a bug. Then we can make something to make RSS Guard work faster in your use case.

Note that in acc settings there is also setting "Limit number of messages downloaded per feed" and this setting would be probably very useful for you, perhaps setting it to like 100 will work nicely...

Anyway try to uncheck the checkbox and re-test pls, then we can do something about the speed. :) Thanks, man.

**Comment by martinrotter** [comment] 2021-01-19 07:05
![image](https://user-images.githubusercontent.com/1255302/104999393-0b077b80-5a2d-11eb-9447-b43885e63aec.png)

**Comment by chrbayer** [comment] 2021-01-20 00:27
@martinrotter 

AH, Ok, that explains it of course. But this makes the option for downloading only unread messages quite useless. I interpolated it like to only add unread messages but of course sync the status oft old locally existent messages anyhow. I used the possibility to limit the number of synced messages to get it working as expected, so all status information is synced as it should and this isn't a bug. Thanks for the help!

I have at the moment 900,000 messages in 80 feeds, I forgot to purge messages since years :-) I now need to get rid of most of messages, but that is a different problem... I tried to limit the number of messages per feed in nextcloud news, but they are not purged...

About the performance: After limiting the performance is not a real problem for my anymore, even with my very slow system (but is is in the same LAN than the server).

Starting more threads in parallel for the update could nevertheless improve the performance.

Thanks again for helping me!

**Comment by martinrotter** [comment] 2021-01-20 06:40
The option "download unread only" is offered at this point by these plugins in RSS Guard: nextcloud-news, ttrss. The purpose of the feature is to make sure, that only "needed" messages are downloaded, in other words it saves network bandwidth and noticeably speeds up message downloading on systems with slow network. That is the whole point. Even if the feed has 1 000 messages and 5 of them are unread, then RSS Guard only transfers those 5 unread messages and the other 995 are left intact and not even downloaded to speed things up.

Btw, your number of message is quite huge, does RSS Guard cope with that high number well? Even I managed to accumulate maybe like 20 000. Your numbers are insane. :D.

As for threading regarding updating of messages/feeds. Well, RSS Guard some year(s) back had this feature and in fact, updating was crazily fast. But technically, the feature was problematic, relatively hard to maintain, because there were some very-hard-to-debug race condition bugs which I was unable to solve. It just kept crashing for some users, so I decided to brutally simplify updating logic to make things simple, easy to understand for programmers, easily maintainable and slimmer.

As for this our syncing problem. Note that in Nextcloud News there is "get me only updated messages" [feature](https://github.com/nextcloud/news/blob/master/docs/externalapi/Legacy.md#get-updated-items), which might be utilized by RSS Guard and could be maybe switchable. It would effectively mean, that RSS Guard would be able to download only really "updated" messages, including those which were changed directly on the server and this hypothetical feature would work even with "Download unread messages only". Similar technique could probably be added to TT-RSS plugin too.

I added a ticket for it: https://github.com/martinrotter/rssguard/issues/339

Closing this as invalid as described behavior is not a bug, but stick to https://github.com/martinrotter/rssguard/issues/339 and we will find some more general solutions.

**Closed by martinrotter** 2021-01-20 06:40 UTC
Labels: Component-Plugins-Nextloud, Priority-High, Status-Not-Enough-Data, Type-Enhancement, Type-Question
