### ISSUE TITLE
Core dumps upon exiting desktop session

### ISSUE THREAD

**Issue by pmattern** [martinrotter/rssguard#22] opened 2016-06-24 21:15 UTC
Recent VCS checkouts of RSS Guard are frequently crashing upon exiting LXQt sessions on Arch Linux.

Unfortunately I couldn't nail down the exact conditions when the problem takes place. Launching RSS Guard via auto start seems to be a condition.
Traces are uploaded at https://gist.github.com/pmattern/89282f5be04bdf45e1b42fc73b312db3.

**Comment by martinrotter** [comment] 2016-06-25 07:22
Not able to reproduce here with these steps:

1. Reboot, let RSS Guard autostart.
2. Make sore RSS Guard output is logged.
3. Reboot.
4. Check log file, it says RSS Guard exited with code 0 - success.

Can you reproduce 100% with autostart enabled and confirm that issue is really not present, when RSS Guard is not started via autostart feature?

Is RSS Guard running with correct privileges/user when started via autostart?

**Comment by pmattern** [comment] 2016-06-26 19:21
> It would be nice to have real backtrace generated by gdb

Does this mean anything in addition to rebuilding with `CONFIG+=debug` set?

As for everything else I may have to ask you for a bit patience as nailing down how to reproduce failed so far.
Also, I can test in virtual machines only right now as I didn't upgrade my main system to Qt 5.7 yet due to [QTBUG-53928](https://bugreports.qt.io/browse/QTBUG-53928) which is affecting RSS Guard as well, btw.

**Comment by martinrotter** [comment] 2016-06-26 19:53
> Does this mean anything in addition to rebuilding with CONFIG+=debug set?
No, AFAIK. It seems, actually, reading your trace files, that the actual crash does not seem to come directly from rssguard. I do not see any "rssguard" line there. Just some "libQt5DBus" lines etc.

Yea, Qt 5.7 has bunch of nasty bugs.

**Comment by martinrotter** [comment] 2016-08-03 04:26
> Does this mean anything in addition to rebuilding with CONFIG+=debug set?

That should be enough.

**Comment by martinrotter** [comment] 2016-08-10 06:15
Any new info for me? If not I will have to postpone this bug for 3.3.4 as I am not able to reproduce in VirtualBox or Arch/Cinnamon. :(

**Comment by pmattern** [comment] 2016-08-10 07:46
Unfortunately there are no news and the problem keeps being hard to reproduce. But I can't rule out this is related to LXQt sessions.
So I'd even say it's okay to remove the milestone altogether and I'd give feedback when the question whether it's due to LXQt is sorted out.

**Comment by martinrotter** [comment] 2016-08-10 07:58
Okay, I will remove the milestone and keep the issue open. When the issue happen what the standard/error output looks like?

`rssguard > log.txt 2>&1`

**Comment by pmattern** [comment] 2016-08-10 08:03
> When the issue happen what the standard/error output looks like?
> 
> rssguard > log.txt 2>&1

That will be hard to say as the issue can only be seen when RSS Guard was launched via autostart. But this shouldn't represent a problem as there has always been something useful in systemd journal and the saved core dumps so far.

**Comment by martinrotter** [comment] 2016-08-10 08:11
You can go to "autostart" settings section of your DE and change the command from `rssguard` to `rssguard > log.txt 2>&1`. That way, even autostarted RSS Guard will log to file of your desire.

**Comment by martinrotter** [comment] 2016-08-10 08:13
BTW: If you are really sure that the bug is triggered by starting RSS Guard via autostart, then I would bet that the bug is actually LXQt bug, but who knows.

**Comment by pmattern** [comment] 2016-08-10 08:30
> You can go to "autostart" settings section of your DE and change the [...]

Strange. So far I never got redirections in key `Exec` of those desktop entry files to work. But I may have another look.

**Comment by martinrotter** [comment] 2016-08-10 08:41
You can always put your redirecting code inside bash script and set that bash script to autostart.

**Comment by martinrotter** [comment] 2016-08-10 08:42
[This](http://stackoverflow.com/questions/23696439/stdout-stderr-not-redirecting-on-autostart) might help too.

**Comment by martinrotter** [comment] 2016-08-25 11:02
Okay, so it seem that bug is related to LxQt, not RSS Guard. Closing for now.

**Closed** 2016-08-25 11:02 UTC
Labels: bug, desktop-integration, invalid
