### ISSUE TITLE
Updating large feed list results in repeated server errors

### ISSUE THREAD

**Issue by mgorny** [martinrotter/rssguard#235] opened 2020-05-02 05:59 UTC
#### Brief description of the issue.

I have quite a long list of GitHub release feeds. When updating all items, GitHub starts rejecting my requests at some point and the relevant feeds are marked red. Using 'update all items' results in another mass update that results in another set of feeds failing.

#### How to reproduce the bug?

1. Add a lot of GitHub feeds.
2. Click 'update all items'.

#### What is the expected result?

I'd like to have all my feeds updated without having to manually update these that initially failed. I suppose potential solutions could involve:
- ability to throttle update requests from one server
- function to update only these feeds that failed

#### What actually happened?

A dozen feeds failed to update, and I can't find a friendly way of updating just them without triggering another global update that's going to fail.

#### Other information (logs, see Wiki)

Here's my export that should be sufficient to reproduce the issue:
[export.opml.gz](https://github.com/martinrotter/rssguard/files/4567165/export.opml.gz)

**Comment by martinrotter** [comment] 2020-05-04 05:24
Is there any documentation on GitHub RSS feeds HTTP limits?

**Comment by mgorny** [comment] 2020-05-04 06:26
Not that I know of but it just might be hard to find. I suspect it might be a generic HTTP request limiting.

**Comment by martinrotter** [comment] 2020-06-15 07:21
Can you test with latest development version? I cannot reproduce the issue. It all just works.

**Comment by mgorny** [comment] 2020-06-15 07:29
Indeed it seems to work on git master.

**Comment by martinrotter** [comment] 2020-06-15 08:12
Yes, that is because network operations for feeds which are "updating" are now more serialized and do not run in parallel in general. I guess we can close this for now. If the issue re-appears, let me know and I will add some kind of switchable delays....

**Closed** 2020-06-15 17:10 UTC
Labels: Component-Core, Type-Enhancement
