### ISSUE TITLE
[BUG]: article list blank on FreeBSD 13/14

### ISSUE THREAD

**Issue by chaplina** [martinrotter/rssguard#1489] opened 2024-09-01 13:53 UTC
### Brief description of the issue

Fresh setup of rssguard on Freebsd 13/14.  Article list is blank.

### How to reproduce the bug?

pkg install rssguard
rm -rf .config/RSS\ Guard\ 4
rssguard
setup using RSS/ATOM/...
add "default" feeds
feeds list is OK
fetch articles from a feed (tested with Lifehack and rssguard commits)
select feed
articles list is blank (no extra highlighting/filtering)

### What was the expected result?

list of articles

### What actually happened?

nothing displayed
![20240901095215](https://github.com/user-attachments/assets/413dcae0-cfb3-4e5b-bc84-1c818a204c1d)

### Debug log

full log from first run and fetches
[rssguard-freebsd14p9.log](https://github.com/user-attachments/files/16829111/rssguard-freebsd14p9.log)

### Operating system and version

* OS: FreeBSD 13.2/14.0
* RSS Guard version: 4.6.3,4.6.6,4.7.3

**Comment by Peter2121** [comment] 2024-09-03 09:25
Same problem here. The problem is related to SQLite backend.

**Comment by martinrotter** [comment] 2024-09-03 09:29
Try to apply this fix

https://github.com/martinrotter/rssguard/pull/1481

and let me know if it helps.

**Comment by Peter2121** [comment] 2024-09-03 10:14
I confirm that #1481 resolved the issue.

**Comment by martinrotter** [comment] 2024-09-03 10:28
Merged the fix.

**Closed by martinrotter** 2024-09-03 10:28 UTC
Labels: Type-Defect
