### ISSUE TITLE
Some character don't show correctly

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#106] opened 2017-03-17 17:27 UTC
#### Brief description of the issue.

Hi, I just upgraded from rssguard-3.3.6-dc6b5b6-nowebengine-win32 to rssguard-3.4.0-88b6c5d-nowebengine-win32, I realize there some character looks wrong, for example 
News ≈ Packet Storm
but in recent version it shows
News â‰ˆ Packet Storm

Character like –,“,” also same issue.

It happens on feeds name and messages content.

Windows 8.1 x64

#### How to reproduce the bug?

Nothing, just open normally.

#### What is the expected result?

It shows correctly.

#### What actually happened?

Shows different character.

#### Other information (logs, see Wiki)

None. Doesn't seem need log file.

**Comment by martinrotter** [comment] 2017-03-18 12:05
Can you post URL of the feed which triggers the issue? Is the problem concerning also newly downloaded messages or only those downloaded with 3.3.6 and viewed i 3.4.0?

**Comment by blackarcher21** [comment] 2017-03-24 13:57
hi, sorry for late answer. here one of the URL https://rss.packetstormsecurity.com/news/
I'm not sure. I just realized some feed name and message content with certain character not showing correctly. With URL above, I just tried adding it as new feed with fresh RSS Guard and it can't be added with error on notification with MySQL as backend. I forgot to mention I use MySQL.

**Comment by martinrotter** [comment] 2017-03-25 08:15
Works here on latest code with MySQL (XAMPP on Windows). Can you post here the actual debug log of the situation where the feed cannot be added?

**Comment by martinrotter** [comment] 2017-03-25 08:18
Note that the encoding problem might be cause by [this](https://github.com/martinrotter/rssguard/blob/master/resources/sql/db_update_mysql_6_7.sql). The encoding of MySQL columns got changed to UTF-8 explicitly. Try with new database, maybe?

**Comment by blackarcher21** [comment] 2017-03-25 09:45
[log.txt](https://github.com/martinrotter/rssguard/files/869900/log.txt)
I seems XAMPP uses MariaDB as database. My WAMP is using MySQL 5.6.29.

**Comment by martinrotter** [comment] 2017-03-25 13:14
It is known that some MySQL versions have quite some problems with proper UTF-8 strings. It seems this is the case.

Check that all tables in rssguard2 database do you `utf8mb4` encoding.

**Comment by martinrotter** [comment] 2017-03-25 13:16
Here, I can add `News ≈ Packet Storm` to MySQL/MariaDB database [without problems](https://i.snag.gy/Z7xpDv.jpg).

**Comment by martinrotter** [comment] 2017-03-25 13:17
So it seems, that your DB has some problems with `utf8mb4` encoding.

**Comment by blackarcher21** [comment] 2017-03-25 13:52
I tried with rssguard-3.3.6-dc6b5b6-nowebengine-win32 and new database (rssguard4) and no problem.
Is there any change that could trigger this issue? BTW I skipped 3.3.7 and 3.4.0 release version. Will try those build, maybe tomorrow.
We had discussions about this before, here I post my MySQL setting, clould you take a look? 
+--------------------------+-----------------------------------------------+
| Variable_name            | Value                                         |
+--------------------------+-----------------------------------------------+
| character_set_client     | utf8mb4                                       |
| character_set_connection | utf8mb4                                       |
| character_set_database   | utf8mb4                                       |
| character_set_filesystem | binary                                        |
| character_set_results    | utf8mb4                                       |
| character_set_server     | utf8mb4                                       |
| character_set_system     | utf8                                          |
| character_sets_dir       | d:\wamp\bin\mysql\mysql5.6.29\share\charsets\ |
+--------------------------+-----------------------------------------------+
8 rows in set (0.00 sec)

**Comment by martinrotter** [comment] 2017-03-25 14:06
This is actually weird because, 3.3.6 should contain those UTF-8mb4 encoding changes too.

**Comment by martinrotter** [comment] 2017-03-25 14:13
Can you show me, what encoding/collation does column title of table Feeds have?

**Comment by martinrotter** [comment] 2017-03-25 14:13
``
SELECT character_set_name FROM information_schema.`COLUMNS` 
WHERE table_schema = "schemaname"
  AND table_name = "tablename"
  AND column_name = "columnname";
``

**Comment by martinrotter** [comment] 2017-03-25 14:13
Or

`SHOW FULL COLUMNS FROM table_name;`

**Comment by blackarcher21** [comment] 2017-03-25 14:24
http://i.imgur.com/XPGZPg8.png

**Comment by martinrotter** [comment] 2017-03-25 14:25
OK, will test with wamp when I get to another machine. Maybe In a week.

**Comment by blackarcher21** [comment] 2017-03-25 17:08
Just tested rssguard-3.3.7-91edb4d7-nowebengine-win32 release version, got same issue.

**Comment by martinrotter** [comment] 2017-04-19 09:23
I tested on latest WAMP.

1. I launched a latest dev RSS Guard.
2. I added new account, added feed https://rss.packetstormsecurity.com/news/.
3. Feed was added without problems and it got updated, I received 25 messages.

**Comment by martinrotter** [comment] 2017-04-19 09:31
So to sum it up:

 - in version 3.3.7, there was a new change -> all contents of feeds and messages is now stored in new utf8mb4 encoding,
 - encoding of existing databases is "converted" (during this conversion, there may be some data loss or some characters may look weird, in that case, remove feed and add it again),
 - RSS Guard with clean profile should work.

So can you try this:

1. Get latest dev build of RSS Guard.
2. Run it with clean data profile, add feed https://rss.packetstormsecurity.com/news/.
3. Check feed list if the title of added feed looks correct.
4. Update feed.

Let me know the result.

**Comment by martinrotter** [comment] 2017-04-19 09:33
Btw, the wamp I used had this: 

> MySQL Version:5.7.14

**Comment by blackarcher21** [comment] 2017-04-19 13:28
The issue is still there with MySQL, I even upgraded it using WAMP addon to latest available MySQL 5.7.18, but when I also tried MariaDB from WAMP addon, there are no issue regarding this.

**Comment by blackarcher21** [comment] 2017-04-23 08:19
HI, I'm gonna close this issue. I decided to migrate to MariaDB, seems work fine so far. Thanks for your help. :)

**Comment by blackarcher21** [comment] 2017-04-23 08:23
Oops, I just realized something when reopen it, it shows wrong.

**Comment by martinrotter** [comment] 2017-04-23 11:13
so should i close it?

**Comment by blackarcher21** [comment] 2017-04-25 02:27
actually it remain unsolved. if we have no idea anymore what the could be the causes and seems only happen to me, you may close it. sorry for trouble

**Comment by martinrotter** [comment] 2017-04-25 04:08
Let's try once more, write here the exact steps you now used to reproduce the bug. If also MariaDB is affected it is weird. What locale you have set in you OS? What font do you use? Might it be font issue?

You can reproduce the issue and sent me MariaDB database data files. It could show us if data in db itself are OK or not.

**Comment by blackarcher21** [comment] 2017-04-26 05:18
mariadb10.1.22 (wamp addon) with default setting, RSS Guard 3.4.0-e2fa0ae-nowebengine
[rssguard2.zip](https://github.com/martinrotter/rssguard/files/957282/rssguard2.zip)
here I attached database with initial feeds and the sample of feed that has problem with the name.
I tried with empty database and insert all initial feeds. after that I add new feed with character issue (which I used same link above). it is fine and feed is inserted, then close RSS Guard. open again RSS Guard again and you'll see the character changed to ?

with MySQL, its not inserted at all

**Comment by martinrotter** [comment] 2017-04-26 05:42
OK, thank you, I will check.

**Comment by martinrotter** [comment] 2017-04-26 05:54
So, you have sent me ZIP which contains MariaDB (I guess) database data. I unpacked the data and loaded it into my XAMPP database server. It contains some feeds. The feed we are talking about really has "?" character in its name.

https://www.dropbox.com/s/nnm0i2xf0p1nuwy/Screenshot%202017-04-26%2007.51.31.png?dl=0

When you were adding the feed, was UTF-8 selected as the feed encoding?

https://www.dropbox.com/s/pqwchhcw8e5pvrt/Screenshot%202017-04-26%2007.53.18.png?dl=0

It is now sure, that the character was not inserted correctly into the database.

**Comment by martinrotter** [comment] 2017-04-26 06:01
I added logging to rssguard to actually precisely see what exactly is sent to DB when feed is added. So, wait until https://github.com/martinrotter/rssguard/commit/ac3c57cd4d422236158211edaeeb1e9842a1ddac gets compiled, then get latest rssguard development build.

Then try again. Start again with logging enabled and with clean profile, add that feed and then send me log file.

Thanks in advance.

**Comment by blackarcher21** [comment] 2017-04-26 06:09
I upload the video :D
https://transfer.sh/gswqV/2017-04-26_14-05-57.mp4

yes, UTF-8 was selected

**Comment by blackarcher21** [comment] 2017-04-26 06:28
[log.txt](https://github.com/martinrotter/rssguard/files/957437/log.txt)

**Comment by martinrotter** [comment] 2017-04-26 07:08
OK, one last try.

Wait until last commit https://github.com/martinrotter/rssguard/commit/a8213dd58ae17f0df051fff3ea4fcabd7ec2a6df gets compiled and the test latest development build.

Now, rssguard is sending raw utf-8 data to the database. This is as far as rssguard can go. So test with same steps as before and let me know.

**Comment by blackarcher21** [comment] 2017-04-26 08:06
okay, now it is inserted but when reopen it, it displays character like my first post

**Comment by martinrotter** [comment] 2017-04-26 10:02
OK, I pushed another commit https://github.com/martinrotter/rssguard/commit/803d7bc1a73b273b7bae2c4a74d9a91b08d968d2

Wait for it to compile and try again please. Now feeds titles/descriptions are also read in utf-8 raw data.

**Comment by blackarcher21** [comment] 2017-04-26 16:01
same issue. I believe the last working fine for me is dc6b5b63c6124ae311e4446082c1b3030ce78158, I wonder if you have started to track from that.
if your side is still working fine and have no idea about my issue anymore, then my computer is weird for sure :) too bad I can't test on new computer at the moment .

**Comment by martinrotter** [comment] 2017-04-28 04:21
It is just weird. I tested with both mysql/mariadb xampp/wamp and it works here. If the issue is not related to messages (in other if you get all messages and their encoding is OK) then I would suggest to just rename the feed to get rid of that "?" character. I will mark this as closed and we will see. Maybe i will encounter the issue myself. :)

**Closed by martinrotter** 2017-04-28 04:21 UTC
Labels: Component-DB, Component-Web-Browser, Status-Accepted, Status-Not-Enough-Data, Type-Defect

**Comment by blackarcher21** [comment] 2017-04-28 05:46
Okay, thanks. I will check again myself later 👍

**Comment by martinrotter** [comment] 2022-03-22 07:17
This could be now fixed, related to #579.
