### ISSUE TITLE
[BUG]: Stop responding while fetching feeds

### ISSUE THREAD

**Issue by joseashb** [martinrotter/rssguard#1073] opened 2023-08-24 20:16 UTC
### Brief description of the issue

The UI and app hangs (stop responding)

### How to reproduce the bug?

Launch App
Fetch feeds
Use the UI or browse the feeds or try to restart the app using the built in option

### What was the expected result?

App continue to respond as per previous versions while fetching feeds
App stop refresh and restart the app

### What actually happened?

App stop responding which last for about 2 minutes. Also restarting while fetching feeds also hangs up. As such that I have to manually end the process and start it again. Issue happens both on using in-memory db or hard drive

### Debug log

[debug.log](https://github.com/martinrotter/rssguard/files/12433032/debug.log)
Debug attached

### Operating system and version

* OS: Windows 10 22H2
* RSS Guard version: 4.5.0

**Comment by martinrotter** [comment] 2023-08-25 04:25
So the problem started only with this version?

**Comment by martinrotter** [comment] 2023-08-25 05:02
Also, please re-test now with installers from here.

https://github.com/martinrotter/rssguard/releases/tag/devbuild

**Comment by joseashb** [comment] 2023-08-25 15:01
> * So the problem started only with this version? Yes only with version 4.5.0
> * which file exactly did you install? rssguard-4.5.0-7175578b6-win10
> * what accounts/plugins do you use in rssguard, just plain RSS/ATOM? Yes plain RSS/ATOM, no linked accounts



> Also, please re-test now with installers from here.
> 
> https://github.com/martinrotter/rssguard/releases/tag/devbuild

Downloading. Will report soon

**Comment by joseashb** [comment] 2023-08-25 15:05
> > * So the problem started only with this version? Yes only with version 4.5.0
> > * which file exactly did you install? rssguard-4.5.0-7175578b6-win10
> > * what accounts/plugins do you use in rssguard, just plain RSS/ATOM? Yes plain RSS/ATOM, no linked accounts
> 
> > Also, please re-test now with installers from here.
> > https://github.com/martinrotter/rssguard/releases/tag/devbuild
> 
> Downloading. Will report soon

Tested. Above mentioned issues still persists on dev build. Reverting to 4.5.0.

**Comment by martinrotter** [comment] 2023-08-25 16:37
Can you try win7 installer?

**Comment by joseashb** [comment] 2023-08-25 18:33
> Can you try win7 installer?

Issue still persists using the devbuild-win7
Reverting to 4.5.0

**Comment by slalaurette** [comment] 2023-08-25 18:38
I have the same issue. With the latest dev builds, RSS Guard slows to a crawl whenever I interact with articles in any way. Just clicking on an article hangs the program for several minutes. 

I should point out that I have thousands of unread articles in a couple hundred feeds, and about 120 regex probes. I am now manually deleting the probes after performing a backup, to see if they are the culprit. But as every time I delete one I have to wait for the program to respond, it will take a while. ¯\_(ツ)_/¯

**Comment by gitdocke** [comment] 2023-08-26 00:59
I confirm. It happens in v4.5.0 but also in v4.4.0 and in a lesser degree with the previous version, all Flatpacks.
This is not a critical bug, at least for me, as you have to wait for all the feeds (like a 300 in my case) to be downloaded to regain full control on the GUI again.

**Comment by slalaurette** [comment] 2023-08-26 10:14
In my case it always happens, rendering the program unusable.

**Comment by martinrotter** [comment] 2023-08-26 11:57
So it happened with previous versions too? Which versions?

**Comment by slalaurette** [comment] 2023-08-26 13:41
For me, it started happening with the latest dev builds. I reinstalled the official 4.5 version and it kept happening. I uninstalled the program again, installed version 4.4, and it's not happening anymore. Of course, with 4.4 I have no probes, so I can't say if they are the cause.

**Comment by martinrotter** [comment] 2023-08-26 14:40
Can you share your or similar database.db file which has the issue?

**Comment by slalaurette** [comment] 2023-08-26 20:21
Let's see! 

This is a backup I made before reinstalling. I lost track of which was the program version at the time. 
[rssguard_202308251501.db.zip](https://github.com/martinrotter/rssguard/files/12446664/rssguard_202308251501.db.zip)

**Comment by joseashb** [comment] 2023-08-27 18:42
I might provide mine also if it helps.

**Comment by martinrotter** [comment] 2023-08-28 05:03
> I might provide mine also if it helps.

Yes.

**Comment by martinrotter** [comment] 2023-08-28 05:03
Also, anyone who would be able to "git bisect" the actual commit responsible for the bug is greatly welcomed as I am not seem to be able to reproduce the bug.

**Comment by martinrotter** [comment] 2023-08-28 05:13
ALSO, guys so do you believe that the bug is actually connected to "Regex queries" (Probes) feature?

**Comment by slalaurette** [comment] 2023-08-28 08:14
Well, in the first few dev builds with probes I wasn't having this problem, not to this extent. Since then I added dozens more probes so I guess it could entail a performance hit, but (correct me if I'm wrong) I think probes should only impact performance when articles are being downloaded, not all the time.

**Comment by martinrotter** [comment] 2023-08-28 08:49
Yes, I was able to reproduce the issue with attached DB file you provided and to me clearly issue is triggerred by high number of probes and I even know why the issue is there.

You know, When you do some operations (new article arrive, article marked as read/unread etc.) then the TOTAL/UNREAD counts of each item in feed list is recalculated, including probes. If you have many probes, that operation takes tooo long, because of how regular expressions operations are implemented in SQLite, they are not that fast and it just takes time, too much time.

I will have to re-work the logic of updating those unread/total numbers for regex queries or completely disable them, because they are just too slow.

**Comment by slalaurette** [comment] 2023-08-28 10:55
That makes sense. 

Maybe update the number only when the user clicks on a probe? 

I personally don't care for those figures, but I see how people would like to see how many results the query is returning.

**Comment by martinrotter** [comment] 2023-08-28 11:09
> That makes sense.
> 
> Maybe update the number only when the user clicks on a probe? (Only for that probe ofc.)
> 
> I personally don't care for those figures, but I see how people would like to see how many results the query is returning.

That is actually quite good idea! Will try to fast implement this.

**Comment by martinrotter** [comment] 2023-08-28 12:34
Your DB link is somehow broken,. upload again pls.

**Comment by slalaurette** [comment] 2023-08-28 12:49
It looks like two separate problems: too many probes slowing down the program generally, regardless of state, and RSS Guard not completing actions while uploading feeds. 

In another thread I can't find now, I had pointed out that some actions look like they succeed but don't while the feeds are updating (pressing a hotkey to star an article, for example, shows the icon as if the article was starred, but switching back and forth between folders shows that it wasn't).

It looks like the database gets locked while updating feeds, but the user is not warned about this.

**Comment by joseashb** [comment] 2023-08-28 17:51
> Your DB link is somehow broken,. upload again pls.

[rssguard_202308252231.db.backup.zip](https://github.com/martinrotter/rssguard/files/12455378/rssguard_202308252231.db.backup.zip)

**Comment by martinrotter** [comment] 2023-09-05 08:25
@joseashb Looking at it.

Yes, your db has over 130 000 articles and there indeed is some kind of freezing, but not permanent. The freezing is likely caused by some heavy workload on some parts of RSS Guard when refreshing list of articles with many items.

c37eadea0

This might improve the situation.

**Comment by joseashb** [comment] 2023-09-09 13:34
> @joseashb Looking at it.
> 
> Yes, your db has over 130 000 articles and there indeed is some kind of freezing, but not permanent. The freezing is likely caused by some heavy workload on some parts of RSS Guard when refreshing list of articles with many items.
> 
> [c37eade](https://github.com/martinrotter/rssguard/commit/c37eadea07a28837b9bafcf69118942515e745ee)
> 
> This might improve the situation.

Hey mate. Thanks a lot for your time and dedication.

I did test out the latest devbuild. The freezing has lessen, but the issue is still present. 

Will test and let you know if any findings

**Comment by mohafri** [comment] 2023-09-17 14:34
I use Arch Linux and compile RSS Guard myself (with -DUSE_WEBENGINE=OFF -DBUILD_WITH_QT6=ON).
I have almost 300 simple (RSS/Atom) feeds, no external accounts, no regex queries. 

After updating from 4.4.0 to version 4.5.0 I had the same problem, RSS Guard froze and became unusable, I had to stop the process manually.
So, step by step, I noted all the feeds that were last displayed in the status bar when freezing, restarted RSS Guard, deleted the respective feed, etc., until RSS Guard 4.5.0 no longer froze. Since then RSS Guard has been working fine.
Then I created a test database containing some working feeds and all problematic feeds. When I use RSS Guard 4.4.0 with this database, there is no problem. The same database with RSS Guard 4.5.0 leads to freezing - deleting the "freeze" category: RSS Guard 4.5.0 works like a charm!
The problematic feeds are those that have been red flagged by RSS Guard itself (feed either unavailable, malformed or whatever). So I guess RSS Guard 4.5.0 is less error tolerant than the previous version. Moreover, 4.5.0 in the frozen state continued to generate Internet traffic, as if constantly trying to fetch the feeds, without taking into account the timeout (as set in the options).

I would like to note that other feed readers (Liferea, QuiteRSS and the Firefox addons: Livemarks and Feedbro) fetch and display the feeds (CERN Document Server, Nature and Scientific Reports) without problems. However, I prefer RSS Guard and use it every day.

I have attached the test database.
[database.db.zip](https://github.com/martinrotter/rssguard/files/12643026/database.db.zip)

**Comment by martinrotter** [comment] 2023-09-18 06:23
> I use Arch Linux and compile RSS Guard myself (with -DUSE_WEBENGINE=OFF -DBUILD_WITH_QT6=ON). I have almost 300 simple (RSS/Atom) feeds, no external accounts, no regex queries.
> 
> After updating from 4.4.0 to version 4.5.0 I had the same problem, RSS Guard froze and became unusable, I had to stop the process manually. So, step by step, I noted all the feeds that were last displayed in the status bar when freezing, restarted RSS Guard, deleted the respective feed, etc., until RSS Guard 4.5.0 no longer froze. Since then RSS Guard has been working fine. Then I created a test database containing some working feeds and all problematic feeds. When I use RSS Guard 4.4.0 with this database, there is no problem. The same database with RSS Guard 4.5.0 leads to freezing - deleting the "freeze" category: RSS Guard 4.5.0 works like a charm! The problematic feeds are those that have been red flagged by RSS Guard itself (feed either unavailable, malformed or whatever). So I guess RSS Guard 4.5.0 is less error tolerant than the previous version. Moreover, 4.5.0 in the frozen state continued to generate Internet traffic, as if constantly trying to fetch the feeds, without taking into account the timeout (as set in the options).
> 
> I would like to note that other feed readers (Liferea, QuiteRSS and the Firefox addons: Livemarks and Feedbro) fetch and display the feeds (CERN Document Server, Nature and Scientific Reports) without problems. However, I prefer RSS Guard and use it every day.
> 
> I have attached the test database. [database.db.zip](https://github.com/martinrotter/rssguard/files/12643026/database.db.zip)

When it stops responding, is it frozen forever? Or does it unfreeze after minute or so? What "feed update timeout" you have set in settings?

**Comment by martinrotter** [comment] 2023-09-18 06:38
Dev.build is now compilling. Please test it when it is done. I lowered used Qt version back to 6..4.3.

**Comment by mohafri** [comment] 2023-09-18 09:05
> When it stops responding, is it frozen forever? Or does it unfreeze after minute or so? What "feed update timeout" you have set in settings?

Current Arch Linux, Qt version: 6.5.2
While RSS Guard freezes, it is still possible to read the feed messages and mark them as read. The context menu and settings also remain accessible. However, it is not possible to edit the feeds or exit RSS Guard normally.
Tested with the test database attached above:

Support very fast auto-fetching intervals enabled,connection timed out set to 28000ms.
RSS Guard 4.5.0: RSS Guard freezes, no change after 15 minutes, during that time constant internet traffic. Normal termination not possible, so process killed.
Connection timed out set to 1000ms, no change.
Support very fast auto-fetching intervals disabled, no change.
It seems that RSS Guard ignores the timeout.

The current dev-build from today: no change, exactly the same behavior as in 4.5.0.

By the way: The german translation for "Support very fast auto-fetching intervals":  "Unterstütze sehr schnell Abhol-Intervalle", better would be: "Unterstütze sehr schnelle Abhol-Intervalle" or just "Unterstütze schnelle Abhol-Intervalle".

**Comment by martinrotter** [comment] 2023-09-18 17:57
> While RSS Guard freezes, it is still possible to read the feed messages and mark them as read. The context menu and settings also remain accessible. However, it is not possible to edit the feeds or exit RSS Guard normally.
> Tested with the test database attached above:

Tested now on my home Arch machine with KDE. While some feeds to timeout (15 000 mseconds in my config)  after they timeout, RSS Guard normally continues to function, also during feed fetching no GUI freezing etc.

Try this: lower the timeout settings for example to 5000 ms and see if there is any difference?

**Comment by martinrotter** [comment] 2023-09-18 17:57
As for traslations, check readme and contributing.md file.

**Comment by martinrotter** [comment] 2023-09-19 05:01
Bug also presents itself when fetching https://www.neowin.net/news/rss/ according to user from #1101

**Comment by mohafri** [comment] 2023-09-19 11:23
> Try this: lower the timeout settings for example to 5000 ms and see if there is any difference?

I tested RSS Guard 4.5.0 again with my test database.
Timeout settings 5000ms - no change, RSS Guard keeps trying to update a problematic feed and freezes. The GUI remains accessible, but RSS Guard does not exit normally. When I try to stop updating, the GUI also freezes, nothing works.
As I said, after deleting the problematic feeds, RSS Guard works with almost 300 feeds - I am very happy with it.
Of course, I also tried to add the deleted feeds again. However, this is not possible: when retrieving the metadata, I either get an error message or, again, RSS Guard tries to fetch data endlessly. I can only click Cancel, the OK button is not active.
The feed https://www.neowin.net/news/rss/ here no problems, adding and fetching works.

**Comment by martinrotter** [comment] 2023-09-19 11:27
@mohafri 

1. Launch rssguard from commandiline: rssguard --log './rssguard.log'.
2. Make program freeze and wait few extra seconds.
3. Kill program.
4. Upload "rssguard.log" log file here pls.

**Comment by mohafri** [comment] 2023-09-19 11:57
> * Launch rssguard from commandiline: rssguard --log './rssguard.log'.
> * Make program freeze and wait few extra seconds.
> * Kill program.
> * Upload "rssguard.log" log file here pls.

Here it is.
[rssguard.log](https://github.com/martinrotter/rssguard/files/12659438/rssguard.log)

While waiting after freeze, the log-output in the terminal flickered like wild...

**Comment by martinrotter** [comment] 2023-09-19 11:59
> While waiting after freeze, the log-output in the terminal flickered like wild...

This is the exact cause of our problem and exact information i need.

**Comment by martinrotter** [comment] 2023-09-19 18:21
OK I found the problem.

https://github.com/martinrotter/rssguard/commit/cb6c49a36e7ff208678a1c1e7c5479caad9f2dea

I tried to create a fix, compilling devbuild now. Pls test when done.

**Comment by mohafri** [comment] 2023-09-25 08:36
> I tried to create a fix, compilling devbuild now. Pls test when done.

I just tested with the latest dev-build from today. RSS Guard works fine, no more freezing!

Thanks a lot for your excellent work.

**Comment by martinrotter** [comment] 2023-09-25 08:41
Just for sake of completeness can you provide debug log when RSS Guard runs now fine (in cases where it previously did not run fine)?

**Closed** 2023-09-25 08:40 UTC
Labels: Type-Defect, Status-Not-Enough-Data

**Comment by mohafri** [comment] 2023-09-25 09:02
Current Arch Linux - qt version 6.5.2
Tested again with the test database from above.
Updated all feeds, exited RSS Guard normally after successful update.

Here is the log file:
[rssguard.log](https://github.com/martinrotter/rssguard/files/12713278/rssguard.log)

**Comment by joseashb** [comment] 2023-09-27 22:03
Trying to navigate the feeds while the refresh is in progress issue still persists on the latest devbuild.

It is bugging because my feeds refresh every 5mins. Thus I'm unable to check the feeds for about 1mins.
