### ISSUE TITLE
Column header and tooltips are not translated

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#60] opened 2016-09-14 09:49 UTC
#### Brief description of the issue.

I use RSS Guard 3.3.5 no webengine version on Windows 8.1, as title said, they are not translated. Can't confirm with normal version, I don't use it.

#### How to reproduce the bug?

1. Switched to other language, e.g. Indonesian
2. As far as I can tell, menus are translated, but column header and tooltips are still in English, not Indonesian

#### What is the expected result?

Translated, they are included in localization file

#### What actually happened?

Not translated

**Comment by eson57** [comment] 2016-09-14 10:10
I can confirm this also for Swedish. Column headers and tooltips do not translate.

**Comment by martinrotter** [comment] 2016-09-14 10:32
Are we talking about column headers in message/feed list?

**Comment by martinrotter** [comment] 2016-09-14 10:32
Was  this bug present in 3.3.4 or older versions?

**Comment by eson57** [comment] 2016-09-14 10:38
Yes, to both questions.  :)

**Comment by martinrotter** [comment] 2016-09-14 10:39
Oh, okay. I will check that out. Looks like some bigger shit happened.

**Comment by martinrotter** [comment] 2016-09-14 10:52
Should be now fixed.

**Closed** 2016-09-14 10:53 UTC
Labels: bug, desktop-integration, fixed

**Comment by eson57** [comment] 2016-09-14 10:54
Wow, that was quick!  :+1:

**Comment by martinrotter** [comment] 2016-09-14 10:57
Thanks, easy fix.
