### ISSUE TITLE
[BUG]: Internal browser doesn't work

### ISSUE THREAD

**Issue by JakubMajcher** [martinrotter/rssguard#777] opened 2022-08-18 21:50 UTC
### Brief description of the issue

I have no idea why, but after months of using application I can't see article inside application. When I pick article from article list to read I see nothing in place I should to have text to read.

Looks like app is trying to download a website, but it can't. Anyway, I don't want see a webpage, but only text. "View website in reader mode" button is turn off.

![screen](https://user-images.githubusercontent.com/75312658/185501402-487e7bff-c422-4f5d-8558-58f4f6abb440.png)

### How to reproduce the bug?

Unfortunetlly I don't know.

### What was the expected result?

Text of article

### What actually happened?

Empty space.

### Debug log

time="   223.168" type="debug" -> gui: Message list got focus with reason 'Qt::MouseFocusReason'.
time="   223.168" type="debug" -> gui: Current row changed - proxy 'QModelIndex(0,16,0x55d2ee40b7c0,MessagesProxyModel(0x55d2e62342b0, name = MessagesProxyModel))', source 'QModelIndex(0,16,0x0,MessagesModel(0x55d2e60ff660))'.
time="   223.181" type="debug" -> database: SQLite connection 'RecycleBin' is already active.
time="   223.181" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/kuba/.config/RSS Guard 4/database/database.db' seems to be established.
time="   223.248" type="debug" -> database: SQLite connection 'ImportantNode' is already active.
time="   223.248" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/kuba/.config/RSS Guard 4/database/database.db' seems to be established.
time="   223.285" type="debug" -> database: SQLite connection 'RootItem' is already active.
time="   223.285" type="debug" -> database: SQLite database connection 'RootItem' to file '/home/kuba/.config/RSS Guard 4/database/database.db' seems to be established.
time="   223.314" type="debug" -> database: SQLite connection 'OwnCloudServiceRoot' is already active.
time="   223.314" type="debug" -> database: SQLite database connection 'OwnCloudServiceRoot' to file '/home/kuba/.config/RSS Guard 4/database/database.db' seems to be established.
time="   223.380" type="debug" -> feed-model: There is request to reload feed model for more than 10 items, reloading model fully.

### Operating system and version

* OS: Debian
* RSS Guard version: 4.2.3.

**Comment by martinrotter** [comment] 2022-08-19 05:53
that is weird, i run my rssguard instance each day for many hours and did not notice that.

can you go into your rssguard "data" folder and remove folder "web"? it contains internal web viewer cache etc. try and let me know.

**Comment by JakubMajcher** [comment] 2022-08-19 11:04
Thank You @martinrotter for your reply.

I understand I should delete folder in `~/.config/RSS Guard 4`. Unfortunetlly didn't help. :/

I think I used Articles > Open in internal browser (no new tab) and then it start to be default option. Then it will be perfect if we can setup default option to "reader mode". BTW Web browser & tabs > New browser tab (or Ctrl+T) doesn't work as well.

**Comment by martinrotter** [comment] 2022-08-19 11:34
there is something very wrong, do not delete WHOLE RSS Guard 4 folder!!!! navigate inside the folder and delete "web" subfolder only!

also if that does not help, perhaps make a video of the problem as from your depiction i am really unable to reproduce the problem

**Comment by CsatiZoltan** [comment] 2022-08-20 20:11
I have a similar problem under Ubuntu 22.04, using the X11 window system.

### System

RSS Guard
Version: 4.2.3 (built on Linux/x86_64)
Revision: 68c03688
Build date: 6/2/22 7:13 AM
Qt: 5.15.2 (compiled against 5.15.2)

### How to reproduce the bug?

Try downloading the AppImage with the webengine activated.

### What I tried

- Deleted the `web` folder as @martinrotter recommended.
- Checked the daily build

In both cases, the issue persists.

### Screenshot

![image](https://user-images.githubusercontent.com/12742890/185764441-eb2b1f14-9b92-4b01-8666-eab684f72b2f.png)

**Comment by martinrotter** [comment] 2022-08-22 05:26
@CsatiZoltan @JakubMajcher 

If you start RSS Guard with completely clean user folder, does it help?

Also, can you by any chance @CsatiZoltan try with Qt6-based RSS Guard build?

**Comment by CsatiZoltan** [comment] 2022-08-22 07:43
@martinrotter 
Deleting the contents of `~/.config/RSS Guard 4/` did not solve the problem.
I downloaded the AppImage from the published releases. Do I have to build RSS Guard myself with Qt6 to have a Qt6 build, or you can provide a precompiled AppImage (or deb file)?

**Comment by martinrotter** [comment] 2022-08-22 07:59
> @martinrotter Deleting the contents of `~/.config/RSS Guard 4/` did not solve the problem. I downloaded the AppImage from the published releases. Do I have to build RSS Guard myself with Qt6 to have a Qt6 build, or you can provide a precompiled AppImage (or deb file)?

That is just weird.

At this point, AppImage file is produced with Qt 5, but code itself fully supports Qt 6.

It would be likely best to just compile by yourself. It is fairly easy:

https://github.com/martinrotter/rssguard/blob/master/CMakeLists.txt

You can also take build command from Arch rssguard package which already uses Qt 6:

https://github.com/archlinux/svntogit-community/blob/packages/rssguard/trunk/PKGBUILD

Also, follow up question. If you just open new tab in RSS Guard and try to navigate to random web page that does not work either?

**Comment by CsatiZoltan** [comment] 2022-08-22 10:09
- When I open a new tab and try to open a web page, the same empty page welcomes me.
- I tried to compile with Qt 6, but I failed. The latest Ubuntu LTS has Qt 6.2 in its repository. So I downloaded the online installer from the website of Qt. Still, I get many missing Qt components to build RSS Guard. I have no idea which components contain these dependencies. I am not sure either whether the compilation will work with mixed Qt 5 (dependencies you defined in the CMakeLists) and Qt 6 settings.

   ![image](https://user-images.githubusercontent.com/12742890/185895956-6599ec82-e1de-45e7-a35c-6d0e05851322.png)

**Comment by martinrotter** [comment] 2022-08-22 10:36
You should set "QT_DIR".

**Comment by CsatiZoltan** [comment] 2022-08-22 13:49
All right, I managed to build it:
```RSS Guard
Version: 4.2.3 (built on Linux/x86_64)
Revision: 35e9f299
Build date: 8/22/22 1:42 PM
Qt: 6.3.1 (compiled against 6.3.1)
```
Now it displays the web content, but icons are missing (although I enabled *FORCE_BUNDLE_ICONS*).
![image](https://user-images.githubusercontent.com/12742890/185934543-cfedae4b-3f80-468f-9802-4ac6cd2fce22.png)

Moreover, I cannot update any feed as I receive the following error and warnings (pasted here for a given feed only, the same messages for other feeds too):

```
time="    36.170" type="debug" -> database: SQLite connection 'feed_upd' is already active.
time="    36.170" type="debug" -> database: SQLite database connection 'feed_upd' to file '/home/zoltan/.config/RSS Guard 4/database/database.db' seems to be established.
time="    36.170" type="debug" -> core: Downloading URL 'https://logout.hu/hirfolyam/cikkek/rovat/az_elet/rss.xml' to obtain feed data.
time="    36.170" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="    36.299" type="warning" -> The backend "cert-only" does not support QSslKey
time="    36.299" type="warning" -> Active TLS backend does not support key creation
time="    36.299" type="warning" -> The backend "cert-only" does not support QSslKey
time="    36.299" type="warning" -> Active TLS backend does not support key creation
time="    36.299" type="warning" -> The backend "cert-only" does not support QSslSocket
time="    36.299" type="warning" -> The backend named "cert-only" does not support TLS
time="    36.300" type="warning" -> QSslSocket::connectToHostEncrypted: TLS initialization failed
time="    36.300" type="debug" -> network: Destroying Downloader instance.
time="    36.300" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="    36.300" type="warning" -> core: Error 'QNetworkReply::UnknownNetworkError' during fetching of new messages for feed 'https://logout.hu/hirfolyam/cikkek/rovat/az_elet/rss.xml'.
time="    36.300" type="critical" -> network: Error when fetching feed: 'Feed::Status::NetworkError' message: 'unknown error (UnknownNetworkError)'.
time="    36.301" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 1/4 (id of feed is 131).
time="    36.301" type="debug" -> feed-downloader: Downloading new messages for feed ID '132' URL: 'https://logout.hu/hirfolyam/cikkek/rovat/sport/rss.xml' title: 'LOGOUT.hu - Cikkek [Rovat: Sport]' in thread: '0x7f139a7fc640'.
```
I had no problem downloading feeds with your published AppImage, so this is new.

**Comment by martinrotter** [comment] 2022-08-29 06:39
Can you try to change icon theme in settings?

**Comment by martinrotter** [comment] 2022-08-29 06:40
I cannot really reproduce base issue, attached first log does not really describe anything related. Closing for now. I plan to switch to Qt 6 for build soon. Feel free to reopen if you manage to pinpoint issue better or provide better log.

**Closed by martinrotter** 2022-08-29 06:40 UTC
Labels: Type-Defect

**Comment by CsatiZoltan** [comment] 2022-08-29 15:04
> Can you try to change icon theme in settings?

Changing from the default *Adwaita* to *gnome* solved my issues with the icons.

> I cannot really reproduce base issue, attached first log does not really describe anything related.

It also seemed to me a "normal" log file. Anyway, I am glad that the Qt 6 build and the different icon theme solved my issue.

> I plan to switch to Qt 6 for build soon.

That will be nice, as currently CMake does not find all the dependencies automatically, so I have to give them manually.

**Comment by martinrotter** [comment] 2022-08-30 07:29
> That will be nice, as currently CMake does not find all the dependencies automatically, so I have to give them manually.

That sounds more like distro configuration/installation issue. cmake has perfect qt6 integration, it should really be piece of cake,

**Comment by M1chael** [comment] 2022-09-01 12:46
The same issue with Cinnamon on Linux Mint 21 and RSSGuard 4.2.3 Appimage.

**Comment by arran4** [comment] 2022-09-02 01:41
Same issue with Kubuntu 22.04

**Comment by arran4** [comment] 2022-09-02 02:36
I was able to "fix" this by building locally, I was able to do that using only packages in apt.

**Comment by martinrotter** [comment] 2022-09-02 03:59
Ok I will try to check, likely appimage is missing some files

**Comment by martinrotter** [comment] 2022-09-02 04:00
I recommend to you all too switch to rssguard from flatpak, pls test and report back

**Comment by M1chael** [comment] 2022-09-02 06:15
> I recommend to you all too switch to rssguard from flatpak, pls test and report back

It works! Thanks a lot!

**Comment by martinrotter** [comment] 2022-09-02 08:10
Also, I managed to produce Qt-6 based AppImage release for rss guard.

Pls test via development builds.

**Comment by arran4** [comment] 2022-09-02 13:32
Browser worked for me:
![image](https://user-images.githubusercontent.com/111667/188156857-8e2052f8-d4b6-4f66-a32e-95030e2aa63f.png)

![image](https://user-images.githubusercontent.com/111667/188156993-34a5ebd7-883a-4f41-83be-7a921ccf3c38.png)

**Comment by CsatiZoltan** [comment] 2022-09-03 06:04
The Qt 6 based AppImage works fine for me as well under Ubuntu 22.04.

**Comment by martinrotter** [comment] 2022-09-03 06:54
I switched to linuxdeploy as these ideological obstacles were driving me crazy.
