### ISSUE TITLE
"Mark all items as read" is not persistent

### ISSUE THREAD

**Issue by ckorn** [martinrotter/rssguard#110] opened 2017-04-17 15:14 UTC
#### Brief description of the issue.

When selecting "Mark all items as read" in the menu and then updating the feeds all items are unread again.

#### How to reproduce the bug?

1. Select "Mark all items as read"
2. Update the feeds.
3. All feeds are unread again.

#### What is the expected result?

Read items should stay read after updating the feeds.

#### What actually happened?

The read feeds are unread again.

#### Other information (logs, see Wiki)

What might be of interest is that the feeds come from my Nextcloud server.

**Comment by martinrotter** [comment] 2017-04-18 04:10
Does this happen with CLEAN RSS Guard profile and with standard "online feeds" account?

**Comment by ckorn** [comment] 2017-04-18 15:52
No, standard feeds are not affected. Seems only to occur with feeds from Nextcloud.

**Comment by martinrotter** [comment] 2017-04-19 09:51
Can you provide application debug log? See wiki for more info.

1. Run RSS Guard with log generation enabled.
2. Simulate the bug.
3. Send me the log.

**Comment by ckorn** [comment] 2017-04-20 16:29
In this log I opened rssguard (there were 500 unread items).
Then I selected "mark all items as read" and updated the feeds again.
All the 500 items were unread again.
[mark_items_read.txt](https://github.com/martinrotter/rssguard/files/944520/mark_items_read.txt)

**Comment by martinrotter** [comment] 2017-05-03 05:19
Try with latest development build, see wiki for more info. Let me know if it works now.

**Comment by ckorn** [comment] 2017-05-05 23:28
It still does not work.

**Comment by gorgood** [comment] 2017-05-12 17:02
I think it happens with youtube feeds too. If you update the feed and mark it as read after 15-20 minutes updating it causes some of the articles to be updated. It's the same for clean profiles and default one.

Here's the log:
[log.txt](https://github.com/martinrotter/rssguard/files/997414/log.txt)

**Comment by martinrotter** [comment] 2017-05-15 04:17
Wait.

So, if you hit "Mark all feeds as read" are the feeds **immediately** after that marked as read? And then when feeds get **updated** again after some time, some messages in them are marked unread again?

**Comment by martinrotter** [comment] 2017-05-15 10:55
Can you try latest dev version?

Do these steps:
1. Run rssguard with clean profile.
2. Add nextcloud account.
3. Sync, update ONE fee.
4. Mark all items as read.
5. Update the feed again.
6. Exit app.
7. Send me the logs.

**Comment by ckorn** [comment] 2017-05-15 13:29
Here is the log.
Had to update a few feeds to find one with unread items.
Found one unread item in the BBC News feed.
[log.txt](https://github.com/martinrotter/rssguard/files/1001199/log.txt)

Also what @gorgood reported seems to be the problem I have.
After "Mark all items as read" they are read. But after updating the items that were unread before "Mark all items as read" are now unread again.

**Comment by gorgood** [comment] 2017-05-16 08:48
It seems that my problem with youtube feeds was fixed by installing dev version (3.4.1 revision 73925b64)

**Comment by martinrotter** [comment] 2017-05-17 04:25
CKORN can you send your DB? It seems somehow corrupted (feeds do not have custom IDs set), which is problem for nextcloud feeds. Send only DB file.

If you don't want to send DB file, try out latest version, I added some logging stuff.

**Comment by martinrotter** [comment] 2017-05-17 04:30
OR can you make some testing account in your nectcloud server for me?

**Comment by ckorn** [comment] 2017-05-17 10:09
Ok, here you have a test account. User is test. App pw ist: UFYDE-IFYKR-KKQDR-UMIPF

**Comment by martinrotter** [comment] 2017-05-19 05:58
It works for me on your server. Sor some reason, your DB (according to log) does not contains special ID numbers for your nextcloud feeds. This is the cause of your problems.

I added some more loggin, pls, test latest code and gimme log. I cannot reproduce the issue here.

**Comment by ckorn** [comment] 2017-05-19 14:05
Did there break something? I am not able to receive feeds any longer. Started with a clean profile but not even the feeds show up.
[log.txt](https://github.com/martinrotter/rssguard/files/1014478/log.txt)

**Comment by martinrotter** [comment] 2017-05-22 05:56
No, no changes. The error is network error. On your side.

**Comment by ckorn** [comment] 2017-05-22 13:57
Ok, odd. Now it works again.

Here is the log.
[log.txt](https://github.com/martinrotter/rssguard/files/1019051/log.txt)

**Comment by martinrotter** [comment] 2017-05-23 05:15
Could be some temporary network issue. Nextcloud is a bit unstable in this. Will check.

**Comment by peperjohnny** [comment] 2017-10-10 07:57
I had this problem a few times as well. What I noticed is that if you mark it as read while the update from nextcloud is going on, it get's marked as unread again. But if you wait till the update is finished and update afterwards it works fine.

**Comment by martinrotter** [comment] 2017-10-10 08:04
@peperjohnny Yes, this indeed can happen on SYNCHRONIZED accounts (nextcloud, inoreader, ...). When you change state of some messages (mark as read/unread) the change is not uploaded to online service right away but is CACHED for ONE MINUTE and after one minute ALL cached requests are sent to online service together - this is there so that fewer requests to service is made.

So it can happen, that:
1. You mark some messages as read (changes are cached for one minute).
2. You see that messages look marked in RSS Guard (but changes will be sent to server after that one minute),
3. You update feeds.
4. Messages read/unread states seem to get reverted in RSS Guard and that is because your message changes were not sent to server yet.
5. After one minute, changes are sent to server.
6. You update feeds again.
7. Message states are now correct.

Is this understandable? This behavior is probably not related to original bug from this report. Do you feel that the behavior @peperjohnny you reported is a bug?

**Comment by peperjohnny** [comment] 2017-10-10 08:16
To be honest I do not see it as a bug, but as a limitation of the current implementation without wanting to offend anyone. I adjusted my workflow as to wait until the notification, that rssguard has finished updating, comes up. After this behavior is as expected.

To describe how this happened to me is.

1. Start update
2. A new article is in, but update is not finished
3. Mark the article as read, while the update is still going on
4. Update finishes
5. Article which was marked as read, is now marked as unread by rssguard

So this happens only if you mark while update is going on. I adjusted myself to mark after update is finished and this works for me.

**Comment by martinrotter** [comment] 2017-10-10 08:25
OK, I will check your use case.

**Comment by martinrotter** [comment] 2017-10-10 09:00
I will try to fix your particular usecase @peperjohnny .

**Comment by martinrotter** [comment] 2017-10-10 09:55
I work on this, https://github.com/martinrotter/rssguard/commit/0814528e032d49d4c641d4661bf57a16c8d3f16e

**Comment by martinrotter** [comment] 2017-10-10 11:28
Please, @peperjohnny , test latest development build when it is compiled and check if your use case is fixed or not. - https://github.com/martinrotter/rssguard/commit/d7ba368a025ef65ad342e0d86c8e120b454dab7a

**Comment by peperjohnny** [comment] 2017-10-10 11:57
@martinrotter nicely done! Works for me, thanks a lot.

**Comment by martinrotter** [comment] 2017-10-10 12:55
@ckorn  Try latest dev build and let me please know if the original problem is resolved or not.

**Comment by martinrotter** [comment] 2017-10-25 04:47
Is this bug still present in latest dev version?

**Comment by martinrotter** [comment] 2017-10-27 07:13
Closing for inactivity.

**Closed by martinrotter** 2017-10-27 07:13 UTC
