### ISSUE TITLE
[BUG]: No status indication when synchronising an account

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#402] opened 2021-04-17 10:25 UTC
#### Brief description of the issue.

When performing a synchronisation action on an account there is no indication of it having started, finished or it having failed.

#### How to reproduce the bug?

1. Synchronise any account.
2. Wonder what happened as there is no visual confirmation of anything.

#### What was the expected result?

For it to show me the start, the progress, and the finish, and any errors that might have occurred.

#### What actually happened?

Nothing happens after a synchronisation action.

#### Other information

* OS: Windows Pro 20H2 64-bit
* Desktop Environment: Yes
* RSS Guard version: 3.9.2

https://user-images.githubusercontent.com/80743272/115109767-042ecd00-9f78-11eb-8039-5dbe7a9982fc.mp4

**Comment by martinrotter** [comment] 2021-04-17 18:18
@fredddd1 I believe that there is a single cause of all your bugs you reported - OpenSSL library is not probably correctly loading for you, which is very weird.

RSS Guard diplays "loading" icon instead of account icon if there is a sync running.


![image](https://user-images.githubusercontent.com/1255302/115122636-3c0a3480-9fb9-11eb-932d-dab79211435d.png)


RSS Guard performs sync automatically if you have not synced items (feeds/categories/tags). You can sync list of categories/feeds/tags (NOT MESSAGES) by going to account's menu and hit "Synchronise folder and other items". 

"Synchronise message cache" is there to force RSS Guard to synchronise you local message state changes (unread/read, etc.) and should be used very rarely as RSS Guard performs two-way MESSSAGE states sync once a minute automatically.

In your case, it seems that all operations which run via "https" secure transports just FAIL and that's why your sync fails, your login fails etc.

So what to do:
1. Download development build (scroll to Assets): https://github.com/martinrotter/rssguard/releases/tag/devbuild (it is compilling right now, you should see it soon).
2. Test your bugs and if they are still there then generate [debug log](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#generating-debug-log-file) and share it here.

**Comment by martinrotter** [comment] 2021-04-20 05:44
Duplicate of #400.

**Comment by martinrotter** [comment] 2021-04-20 10:54
Tested in VBox, clean 20H2.

![image](https://user-images.githubusercontent.com/1255302/115384646-9254be80-a1d7-11eb-9fab-532d830ab3a9.png)

**Comment by martinrotter** [comment] 2021-04-20 10:59
When you synchronise account via "Synchronise folders..." then account's icon turns into "loading" icon - that's all indication you currently get. If synchronisation fails the error is written only to debug log. I agree that it could also be written to use via messagebox.

Btw, you should use "Synchronise folders" very rarely, only if add/remove some feed or label etc.

**Comment by martinrotter** [comment] 2021-04-20 11:01
This is how "loading" looks like, notice the icon: 
![image](https://user-images.githubusercontent.com/1255302/115385501-80275000-a1d8-11eb-9a13-50e7b55bee14.png)

**Comment by fredddd1** [comment] 2021-04-20 11:15
I can confirm the icon change. It is so small that I did not notice it.

I was looking at the bottom right to see if a progress bar would appear there, because I am used to it appearing there when messages are checked for.

**Comment by martinrotter** [comment] 2021-04-20 11:24
Yes, if you do not have crazy big number of feeds then the feed sync should be relatively fast and non-problematic.

So, no are all your troubles fixed with lates dev. build?

**Comment by fredddd1** [comment] 2021-04-21 05:19
No. It is resolved.

Any estimate on when this fix will make it to stable?

**Comment by martinrotter** [comment] 2021-04-21 05:40
I will maybe backport it fo 3.9.3, but at this point it is scheduled for huge RSS Guard 4 version.

**Closed by martinrotter** 2021-04-21 05:40 UTC
Labels: Status-Not-Enough-Data, Type-Defect
