### ISSUE TITLE
[BUG]: sorting by title can't count past 9 right

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#596] opened 2022-01-19 11:22 UTC
### Brief description of the issue

![изображение](https://user-images.githubusercontent.com/1309656/150120324-f0137a54-6b79-4011-b64e-7415d033e260.png)
![изображение](https://user-images.githubusercontent.com/1309656/150120352-a9a861cc-2873-48c1-86e2-132378e5ce88.png)

### How to reproduce the bug?

have numbers in titles bigger than 9

### What was the expected result?

sort naturally:
1-9, 10+, 99, 100+

### What actually happened?

1,100,1000,2,20,200,2000,3...

### Operating system and version

* OS: Win 10 x64
* RSS Guard version: Dev build

**Comment by martinrotter** [comment] 2022-01-19 11:36
REally, that is "expected" result?

RSS Guard uses textual sorting in "title" column which IS expected behavior. That said, you can achieve the feature you want with article [filtering feature](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#fltr) and in several ways which come into my mind:
1. You can parse the title and extract the number of it. Then you must fit the number onto 0...100 scale and then you assign resulting number to "score" attribute. And that's it. You then can sort with the score column and have desired result.
2. Other way could be extracting the number and prepending it with zeros to reach fixed-width numerical strings - these strings can be sorted lexigographically and it is same as sorting them numerically.

**Comment by Owyn** [comment] 2022-01-19 11:42
> RSS Guard uses textual sorting in "title" column which IS expected behavior.

How is that useful to users? Does windows sort files by name the same robotic way? - no
I just can't imagine a person who would be happy about having item named `20` after item named `2`, can you?

**Comment by martinrotter** [comment] 2022-01-19 11:48
> Does windows sort files by name the same robotic way? - no

Lol of course it does.

**Comment by martinrotter** [comment] 2022-01-19 11:50
Also, you have "#" character in front of numbers...

**Comment by Owyn** [comment] 2022-01-19 11:51
> > Does windows sort files by name the same robotic way? - no
> 
> Lol of course it does.


![изображение](https://user-images.githubusercontent.com/1309656/150124502-c420b43a-5841-4875-bfbc-0adf30d595bc.png)

**Comment by martinrotter** [comment] 2022-01-19 11:52
This is sorcery. I would imagine implementing this ONLY if the value in the column is number, no garbage texts around. Also as I said, this can be already done with "score" column approach.

**Comment by Owyn** [comment] 2022-01-19 11:52
> Total commander uses same approach as RSS Guard - always textual sorting.

![изображение](https://user-images.githubusercontent.com/1309656/150124624-a88c8146-cb73-4b5c-ad8f-b46f299c40b0.png)

**Comment by martinrotter** [comment] 2022-01-19 11:54
I see. Like I said, I would consider implementing this but only for textual data which are numbers, no strings around (there is purely technical reason behind it).

**Comment by Owyn** [comment] 2022-01-19 11:55
> ONLY if the value in the column is number,

you don't really have to invent a wheel do you? I can bet there's already a method for that available in used libs and frameworks

**Comment by martinrotter** [comment] 2022-01-19 12:02
> > ONLY if the value in the column is number,
> 
> you don't really have to invent a wheel do you? I can bet there's already a method for that available in used libs and frameworks

RSS Guard uses server-side sorting, not client-side sorting.

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/core/messagesmodelsqllayer.cpp#L94

Not that easy to add what you request as I need to stay as close to ANSI SQL as possible (because i support sqlite and mariadb) and there is now function in ANSI SQL which would allow me to extract number from string.

This kind of sorting is done server-side because it is fast. Incredibly fast with long lists of articles. To do fine-grained sorting, it would have to be done client-side in list logic which would again make list slower.

As I said: I provided some options for you, feel free to react or suggest any of the options.

https://github.com/martinrotter/rssguard/issues/596#issuecomment-1016375491 + (number-only sorting i suggested to implement)

**Comment by Owyn** [comment] 2022-01-19 12:04
> RSS Guard uses server-side sorting, not client-side sorting.

?.?

So when I click the title column to change the sorting all my items go the the server and the server return all the items backs but sorted differently?...

Why not use QCollator or smth? https://stackoverflow.com/questions/11933883/sort-filenames-naturally-with-qt

**Comment by martinrotter** [comment] 2022-01-19 12:06
Yes, but the "server" is "sqlite" database which is local file managed by local library.

**Comment by martinrotter** [comment] 2022-01-19 12:07
> Why not use QCollator or smth?

This is client-side sorting which is not supported/used now, feel free to suggest PR.

**Comment by martinrotter** [comment] 2022-02-01 12:45
> ### Brief description of the issue
> 
> ![изображение](https://user-images.githubusercontent.com/1309656/150120324-f0137a54-6b79-4011-b64e-7415d033e260.png) ![изображение](https://user-images.githubusercontent.com/1309656/150120352-a9a861cc-2873-48c1-86e2-132378e5ce88.png)
> ### How to reproduce the bug?
> 
> have numbers in titles bigger than 9
> ### What was the expected result?
> 
> sort naturally: 1-9, 10+, 99, 100+
> ### What actually happened?
> 
> 1,100,1000,2,20,200,2000,3...
> ### Other information
> 
> _No response_
> ### Operating system and version
> 
>     * OS: Win 10 x64
> 
>     * RSS Guard version: Dev build

pls give link to that feed, so that i can try it myself

**Comment by Owyn** [comment] 2022-02-01 13:12
Here: 

url: `https://mangahub.io/manga/i-m-an-evil-god/`
script: `python css2rss.py "ul.list-group > li > a" "span > span"`
![image](https://user-images.githubusercontent.com/1309656/151974569-58e01bd5-5d95-49bd-b9b4-0c8823a0f849.png)

**Comment by martinrotter** [comment] 2022-02-01 13:46
hm
just checked, i can get relatively good results, it works okay only with some patterns, however, for example
 `#0000000` pattern would work, but if some item contains numerical dot, it sorts badly

is that viable solution?

![image](https://user-images.githubusercontent.com/1255302/151979587-ecbb612c-0380-4fe7-8752-41d80288817e.png)

**Comment by Owyn** [comment] 2022-02-01 13:54
Later all item titles have numerical dots in them... and having a dot is rather common, many and many release groups cut chapters into multiple using dots

**Comment by martinrotter** [comment] 2022-02-01 13:56
Well, that is the best what I can do with ANSI SQL. How it works is that it first sorts strings according to string length, then sorts same-length strings lexicographically, results are definitelly better than vanilla.

**Comment by martinrotter** [comment] 2022-02-01 13:57
![image](https://user-images.githubusercontent.com/1255302/151981609-dea5e6f8-0b38-4543-aa76-9f77c9ec95f3.png)

Perhaps it would really be best if you used article filtering feature? It will work good for your use case.

**Comment by Owyn** [comment] 2022-02-01 14:02
dot-less item were released long long ago, so now only dotted one are actual, if at least dotted ones are sorted fine now - that'd be it

your last screenshot looks great, everything seems fine there

**Comment by martinrotter** [comment] 2022-02-01 14:21
OK.

But even still, before I decide to implement anything. Article filters feature already offers you what you want - it is automatic (once the filter is setup, it runs automatically on incoming articles), it is switchable, etc.

I created very simple article filter for you. It takes each article and automatically assigns article `score` number depending on the number extracted from its title. This is robust solution and works naturally for all titles.

Then you can sort you list of articles directly with the `score` column and have achieved behavior you want, automatically, no subsequent work needed. Check video.

![w1e6Ns740N](https://user-images.githubusercontent.com/1255302/151985527-160a7c7e-da22-4566-959d-bdfc2da51828.gif)

```js
function filterMessage() {
  pars = msg.title.match(/\b\d+([\.,]\d+)?/);

  if (pars == null || pars.length == 0) {
    return MessageObject.Accept;
  }

  num = parseFloat(pars[0]);

  if (num != null && !isNaN(num)) {
    msg.score = num / 1000.0;
  }

  return MessageObject.Accept;
}
```

**Comment by martinrotter** [comment] 2022-02-01 14:24
You can even tweak the behavior and PREPEND the actual number, pre-padded with zeros, to the title - that would achieve same result, without the need of `score` property.

**Comment by Owyn** [comment] 2022-02-01 14:26
I see, thanks. 
Thought, on your latest screens I already see a great result even without any scores.
Usually everything is sorted by the date anyway, but if someone decides to sort by title - shown result would be rather satisfactory I think.

**Comment by martinrotter** [comment] 2022-02-01 14:30
Thing is that the first approach I offered is not really robust, it can be called "semi-natural sorting" at best and it seems there is really no great interest in this. You are the only one requesting this. The feature will not really be "solid" and it would work only for some cases. Titles formatted bit differently with numbers buried in them, will not work.

Article filter approach gives you massive flexibility. You could even tweak titles from `#100` or `#1.1` to `#0100.0` and `#0001.1` (fixed-width nubmers with one digit after the dot) - this sorts fully "naturally" even with current implementation.

**Comment by Owyn** [comment] 2022-02-01 14:35
> Article filter approach gives you massive flexibility. 

It does.

But the thing is just that "sorting by title" feature shipped by default with the app is barely does what users expect it to do, aka "being faulty", that's why I reported it.

**Comment by martinrotter** [comment] 2022-02-02 09:43
> "sorting by title" feature shipped by default with the app barely does what users expect it to do (at least it didn't for me as you can see in the 1st post), aka "being faulty", that's why I reported it.

OK, if that is the case, I am closing the issue as I disagree, because RSS Guard has seen hundred of versions released with tens of thousands of users and nobody complained/reported that sorting is somehow flawed.

As there are ways of implementing what you want easily, I close this. Not a bug. RSS Guard uses alphabetical sorting, not natural.

**Closed by martinrotter** 2022-02-02 09:43 UTC
Labels: Type-Defect
