### ISSUE TITLE
Move ~/.rssguard -> ~/.config/rssguard

### ISSUE THREAD

**Issue by TomaszGasior** [martinrotter/rssguard#77] opened 2016-12-19 19:16 UTC
#### Brief description of the issue.

Application saves config in hidden directory placed in user home dir. It does not respect standards such as a lot of Linux applications. 

#### What is the expected result?

Move config dir to subdir in ~/.config, for example: ~/.config/rssguard.

**Comment by martinrotter** [comment] 2016-12-20 05:55
Yes, this will be one of changes for breaking release 4.0.0 which will not guarantee backwards compatibility.


Unfortunately, I do not have much time for RSS Guard but I expect to release next version 3.X.X in one month and major 4.0.0 version and first half of 2017.

**Comment by pmattern** [comment] 2017-02-16 13:14
Now that the directory structure in `$HOME` has been subject to modification, wouldn't it be good to refrain from using a subdirectory `Martin Rotter` in `$XDG_{CACHE,DATA}_HOME` as well?
Directories like this just seem like an additional item that has to be memorized but does not provide any benefit to me. Just figure the data of all applications on a particular system were residing in directories named after the corresponding project or developer. It would be quite a task to memorize all of them in order to quickly lookup stuff in the FHS.
So couldn't you just use `~/.cache/RSS Guard` and `~/.local/share/RSS Guard` instead?

**Comment by martinrotter** [comment] 2017-02-17 07:10
Those are some shit folders created by Qt library, not by me. It seems that QtWebEngine component stores there some cache stuff etc.

I will probably re-tweak my info and patch RSS Guard to use these paths.

`..../.config/RSS Guard`
`..../.cache/RSS Guard`
`..../whatever/RSS Guard`

XDG variables are internally respected by Qt methods, so they should work too.

**Comment by martinrotter** [comment] 2017-02-17 07:11
It seems that this [method ](http://doc.qt.io/qt-5/qwebengineprofile.html#cachePath)can be used to tweak the shit.

**Comment by martinrotter** [comment] 2017-02-17 18:35
OK, new folders for Linux.
`$HOME/.{cache, config, local/share`}/RSS Guard.

I am still thinking about new paths for Windows/Mac OS.

Note that if old path still exists, it is used (fallback).

**Comment by martinrotter** [comment] 2017-02-19 09:34
Other oses will use new and more natural paths aswell. Fallback paths are maintained.

**Comment by pmattern** [comment] 2017-02-19 19:29
If I'm not mistaken, 9a1b5037 isn't behaving exactly as expected on Linux yet.
When none of the directories used in `$HOME` so far preexists, `$XDG_{CACHE,CONFIG,DATA}_HOME/RSS Guard` are created and used as expected.
But when `$XDG_{CACHE,DATA}_HOME/Martin Rotter` and `~/.rssguard` preexist, RSS Guard will keep using the latter but create and use `$XDG_{CACHE,DATA}_HOME/RSS Guard` instead of the former two.

**Comment by martinrotter** [comment] 2017-02-20 05:29
Indeed, that's a regression. I will check.

**Comment by martinrotter** [comment] 2017-02-20 05:35
Oh, no, `$XDG_{CACHE,DATA}_HOME/Martin Rotter` and `~/.rssguard` are the folders which RSS Guard used before this issue was raised. 

`$XDG_{CACHE,DATA}_HOME/Martin Rotter` these paths are now completely unused and abandoned, try to delete it, it should not get created again. `$XDG_{CACHE,DATA}_HOME/RSS Guard` is now used instead in all situations.

`~/.rssguard` is the original folder to keep user data. If that folder exists when RSS Guard is launched, then it is used. I did this to provide fallback. Users which do not have `~/.rssguard` will launch RSS Guard and our new $XDG_{CONFIG}_HOME/RSS Guard will get created.

So users are expected to move their user data from `~/.rssguard` to new location. I guees, that users who do not care about the change will like that they won't be hit by the change and RSS Guard will run with their data in old fallback location just fine. Users who care, will read changelog or this bug report and will move their data accordingly.

Do we understand each other now? :)

**Comment by pmattern** [comment] 2017-02-20 12:33
So once more: say `$XDG_{CACHE,DATA}_HOME/Martin Rotter` and `~/.rssguard` preexist from earlier versions. What I would have expected is RSS Guard keeps using *all three* directories. What it in fact does is go on using `~/.rssguard` but leave `$XDG_{CACHE,DATA}_HOME/Martin Rotter` aside and use `$XDG_{CACHE,DATA}_HOME/RSS Guard` instead.
I don't know whether this is expected behaviour. If so I found it a bit strange. At least I fail to see the benefit from going on the usage of a single of those three directories only as all of them are providing user-specific data.

**Comment by martinrotter** [comment] 2017-02-21 06:54
You are in fact correct. I do not use older fallback values `$XDG_{CACHE,DATA}_HOME/Martin Rotter`, now RSS Guard uses `$XDG_{CACHE,DATA}_HOME/RSS Guard` all the time.

Only `~/.rssguard` is used as fallback.

**For me** those cache files stored by QtWebEngine do not seem that important to RSS Guard to remember fallback values for those cache directories, RSS Guard just abandons old folders and uses new ones for it. I guess that maybe, I could add code which will load all three types of data: "data", "config" and "cache" from one new subfolder `$XDG_CONFIG_HOME/RSS Guard` but that is not really standard behavior since many apps use those `XDG_CONFIG/DATA` user subfolders.

What do you think.

**Comment by pmattern** [comment] 2017-02-21 19:34
I absolutely agree that it is alright to allocate different kind of data to different directories in `$HOME` and that these should definitely not be merged into a single directory like the old `~/.rssguard` or the new `$XDG_CONFIG_HOME/RSS Guard`.
(Personally I'm not that sure whether the way `$XDG_DATA_HOME` is currently used really makes sense, but this affects QtWebEngine and the XDG specs and is a different story.)

As for the continued use of `$XDG_{CACHE,DATA}_HOME/MartinRotter` I think it should depend on the impact for users.
If dropping `$XDG_{CACHE,DATA}_HOME/MartinRotter` in favour of `$XDG_{CACHE,DATA}_HOME/RSS Guard` simply means some caches have to be rebuilt or so, then it's fine. But if user data is lost, then I think it would be better to go on using `$XDG_{CACHE,DATA}_HOME/MartinRotter`. In current versions there's e. g. a file `$XDG_DATA_HOME/RSS Guard/QtWebEngine/Default/Visited Links`. If some counterpart in `$XDG_DATA_HOME/MartinRotter` did exist I figure its loss could result in some bad UX.
Unfortunately I cannot test all this myself right now. IMO this takes a set of the "old" directories which has been in use for a while which I don't have at hand.

What I also think is this `MartinRotter` vs. `RSS Guard` directory thing isn't too important. The release notes of the stable release introducing the new directory structure should explain the situation and how to manually migrate old to new directories enabling users to do what ever they want.

**Comment by martinrotter** [comment] 2017-02-21 19:57
Exactly, OK, I will write this stuff to changelog briefly. Then, I consider this solved and done.

**Closed** 2017-03-08 05:49 UTC
Labels: Component-Core, Status-Partially-Fixed, Type-Desktop-Integration
