### ISSUE TITLE
Inoreader initiate

### ISSUE THREAD

**Issue by jaredbidlow** [martinrotter/rssguard#150] opened 2017-10-15 18:02 UTC
#### Brief description of the issue.

Inoreader subscription is not updating.
[log.txt](https://github.com/martinrotter/rssguard/files/1385673/log.txt)

**Comment by martinrotter** [comment] 2017-10-15 19:42
Please, write better description and EXACT steps to reproduce the bugs, screenshots would be nice. What exactly happened? Use full bug report template.

**Comment by jaredbidlow** [comment] 2017-10-19 13:25
i will update it when I have the chance to use that pc. it seems as if i lost the bulk of the description when i posted this. I will update the issue today on Inoreader not syncing (only the folder list syncs, but I could be doing something wrong).

**Comment by mastafrooper** [comment] 2017-10-23 09:45
Same issue here.

Installed RSS Guard.
Signed into InoReader account.
Folder List Syncs.
Feed update starts.
Feed update completes.
No actual items are downloaded in the feeds. They all say 0.

The online version has plenty of unread as I left them for testing.

**Comment by martinrotter** [comment] 2017-10-23 09:52
Will try to do with exactly same steps.

Side questions:
1. Do you hit button "Login" in "Add Inoreader account" dialog?
2. Do you fill-in your credentials in popped login window and confirm the access?
3. Are any desktop notifications visible during the whole process?

**Comment by martinrotter** [comment] 2017-10-23 09:59
Follow-up: Full rssguard log would be nice.

**Comment by mastafrooper** [comment] 2017-10-24 09:23
1. Yes.
2. Yes. The OAuth dialog popped up. I logged in and allowed it access.
3. Desktop notification popped up saying that I was logged in. No other notifications
4. Maybe about 1/3 of them are red with an error. When I launched it in debug mode there were no red ones after it finished.

Log file attached. Some feed lines were deleted though as they contained key hashes etc. Most are still there.
[log.txt](https://github.com/martinrotter/rssguard/files/1410232/log.txt)

**Comment by martinrotter** [comment] 2017-10-24 09:59
@mastafrooper Was RSS Guard (when the log was recorded) started without clean database (without messages)?

**Comment by martinrotter** [comment] 2017-10-24 10:09
It seems that messages are downloaded correctly but for some reason not saved into database.

**Comment by martinrotter** [comment] 2017-10-24 10:15
See my previous question. If RSS Guard was not started with clean profile, please, **repeat your procedure and create log from RSS Guard started with clean profile**.

Follow-up questions:
 - You can try to lower the limit of downloaded messages for testing purposes to (for example) 30 messages, please try it (it is in account settings dialog) and see if the problem is still there.
 - You can send me your DB (remove your credentials first if you dont trust me) so that I can review the DB which seems to be a problem.

**Comment by mastafrooper** [comment] 2017-10-26 07:27
This was all done on a clean database/install. I had been following along but was using InoReader. Once I saw support was added I jumped on board to test.

I've lowered the message count and upped the timeout and it made no difference.

[log.txt](https://github.com/martinrotter/rssguard/files/1417318/log.txt)

Log is attached.

What's the best way to send the DB to you? I have a few places to upload it but would rather not share it to anyone else.

**Comment by martinrotter** [comment] 2017-10-26 09:57
Perhaps on my e-mail? rotter.martinos(at)gmail.com

I will check the log.

**Comment by mastafrooper** [comment] 2017-10-26 10:24
Sent you an email from OneDrive with a link to the file.

**Comment by martinrotter** [comment] 2017-10-26 10:26
Got it, stored db file into my PC, will check it later, thanks so far. :)

**Comment by martinrotter** [comment] 2017-10-26 18:28
OK, I think I maybe have idenitified the problem. The fix is in https://github.com/martinrotter/rssguard/commit/245c0b08c35866c63d445e212eb8fb7d08ac71f7

Please, wait until it appears in development builds and test and let me know :) - https://github.com/martinrotter/rssguard/wiki/Windows-development-builds

Check bottom of the list.

**Comment by martinrotter** [comment] 2017-10-26 20:24
Oh, can you send me email with link to db file once more? I lost it.

**Comment by mastafrooper** [comment] 2017-10-27 23:55
I've resent you the database.

As for the newest builds they seem to be working. Will continue testing but fingers crossed.

**Comment by martinrotter** [comment] 2017-10-28 08:32
Allright, can you please post logs from newest build? So that I can exactly see how it was fixed?

**Comment by martinrotter** [comment] 2017-10-28 08:32
Btw, thx for the database.

**Comment by mastafrooper** [comment] 2017-10-30 19:15
[log.txt](https://github.com/martinrotter/rssguard/files/1428456/log.txt)

Newest log file. I have upped the downloaded articles to 100 though from 30. I haven't turned it all the way back up yet though.

**Comment by martinrotter** [comment] 2017-10-30 21:07
SO, it seems to be fixed for you?

**Comment by mastafrooper** [comment] 2017-10-31 00:19
Seems to be yeah.

**Comment by martinrotter** [comment] 2017-10-31 07:20
OK, will check log and mark this fixed.

**Closed** 2017-10-31 07:22 UTC
Labels: Component-Plugins-Inoreader, Status-Accepted, Type-Defect
