### ISSUE TITLE
[BUG]: 6a3b0edb: On (re)start, with feed item highlighted, text box slips to bottom of screen (regression with Qt 6)

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#517] opened 2021-10-14 07:53 UTC
### Brief description of the issue

6a3b0edb: On (re)start, in horizontal (newspaper?) view, when a feed item highlighted, text box slips to bottom of screen, and does not remain in the higher position selected the last time the app was used.

### How to reproduce the bug?

1. Close Rssguard.
2. Reopen it.
3. Sync.
4. Highlight a feed item.
5. Text box has slipped to bottom of screen.

### What was the expected result?

Slippage of text area to bottom of app page.

### What actually happened?

As above.

### Operating system and version

* OS: Windows 10 21H1 latest
* RSS Guard version: 6a3b0edb

![Slippage](https://user-images.githubusercontent.com/59395777/137274948-db56db52-a147-4bcc-abee-216f8072fe31.png)

**Comment by umbellipher** [comment] 2021-10-15 07:53
Seems to be resolved now. Thanks. Closing.

**Comment by mcoret** [comment] 2021-11-16 06:25
Hi! I'm still experiencing this bug (on the latest dev release for win64).
Thank you!

**Comment by martinrotter** [comment] 2021-11-16 09:59
@mcoret Bad behavior only happens when you use "Restart" action from rss guard right?

**Comment by mcoret** [comment] 2021-11-16 11:43
No, I think I've probably never used the "Restart" feature, I usually just close the window normally instead.

**Comment by martinrotter** [comment] 2021-11-16 12:07
I see. I cannot really reproduce, perhaps attach some video here...

**Comment by mcoret** [comment] 2021-11-16 12:26
On each reopening, upon selecting any RSS feed, the main window looks exactly like the first picture above (even if the split was on 50/50 before closing).

**Comment by mcoret** [comment] 2021-11-16 18:21
I have this version (it has this problem):

RSS Guard
Version: 4.1.0 (built on Windows/x86_64)
Revision: 453363c4
Build date: 11/15/21 10:34 AM
Qt: 5.15.2 (compiled against 5.15.2)

I will update it now to a newer build.

**Comment by mcoret** [comment] 2021-11-16 18:58
The newer build behaves the same.
I've noticed that if I never expand/collapse a tree on the left-hand side (e.g., leaving it always expanded), the split remains in its place. But whenever I collapse a branch (a 'category') before quitting, after reopening (and selecting some article from the now-closed branch), the split slips to the bottom.
I hope this makes sense.

**Comment by umbellipher** [comment] 2021-11-19 08:23
May I add that, with f1baf56, fresh this morning, this is still happening, both on start and restart.

**Comment by martinrotter** [comment] 2021-11-19 08:36
@mcoret @umbellipher Two things:

1. Does same bug happen if you just for test try to start RSS Guard with clean user data folder?
2. Please, provide video/gif of how you trigger the bug, I cannot reproduce.

**Comment by martinrotter** [comment] 2021-11-19 08:42
Nevermind, reproduced the problem.

**Comment by martinrotter** [comment] 2021-11-19 09:45
Guys, now please test latest devbuild. The problem is a regression.

**Comment by umbellipher** [comment] 2021-11-19 10:10
1) Installed d7574cf1.
2) Opened, and text box is (as expected) at the bottom, not where the last dev build left it.
3) Click an item, and set the text box where I want it.
4) Restart.
5) On opening, text box is where I left it, in the right place.

Sorted, then?

**Comment by martinrotter** [comment] 2021-11-19 11:21
Well, the regression seems to be introduced by Qt 6, did not find any relevant bug ticket reported. For now, it works and I will take a look into it.

**Comment by martinrotter** [comment] 2021-11-19 12:17
OK, I pushed yet another fix, now with up-to-date Qt 6.

can you test?

**Comment by umbellipher** [comment] 2021-11-19 12:58
All good. I left the text box in the right place with d7574cf, updated to 258cff1c, synced it, and the text box was where I left it in the previous version.

Thanks, as always!

**Closed** 2021-11-19 13:08 UTC
Labels: Type-Defect, Status-Fixed

**Comment by mcoret** [comment] 2021-11-19 15:49
I can confirm, now it seems to work properly. Thank you! :)

**Comment by umbellipher** [comment] 2023-01-12 13:21
@martinrotter 

With ff3d1e5e (and the version before), this text box slippage appears to be happening again.

Also, I'm finding that notification sounds are not playing.
