### ISSUE TITLE
[FR]: Issues get closed before author has a chance to respond. Please at least  2 weeks grace.

### ISSUE THREAD

**Issue by nobicycle** [martinrotter/rssguard#890] opened 2023-01-30 10:20 UTC
### Brief description of the feature request

The issue https://github.com/martinrotter/rssguard/issues/878 was closed efore I had a chance to respond.

Can't we have a week or two to respond?

Holidays,
Funerals

etc
All are more important thnn github

**Comment by martinrotter** [comment] 2023-01-30 10:45
Open/close status of issue is really more relevant information to authors of the app. It is simply useful to see for me, which issues are open, and which are considered "done" for any reason.

If you feel that resolution of the issue is not satisfactory, you can comment and/or re-open the issue any time you wish.

Closing the issue does not mean that I do not want any more progress on it, it simply means that at the point when I was closing the issue I thought it is done.

I rather close issues fast because if I were not, things could spiral out veeeery quickly and I would end up with hundreds of useless tickets.

Not easy to manage rather large project in one person, I can assure you. Anyway, if you feel issue was not processed correctly, simply comment, I will see your comment notification anyway.

**Closed by martinrotter** 2023-01-30 10:45 UTC
Labels: Type-Enhancement
