### ISSUE TITLE
[BUG]: 4.x fails to fetch feeds with socks proxy

### ISSUE THREAD

**Issue by zero77** [martinrotter/rssguard#481] opened 2021-09-02 07:47 UTC
### Brief description of the issue

Rssguard fails to fetch any feeds when using a proxy but, it does seem to get the feed meta data ok.

### How to reproduce the bug?

Try to fetch new feeds on one or all feeds.
Rssguard fails to fetch any feeds.

### What was the expected result?

New feeds should be updated when you fetch them.

### What actually happened?

Rssguard fails to fetch any feeds.

### Other information

Log:
https://pastebin.com/WMwdcB3L

### Operating system and version

* OS: 4.0.0
* RSS Guard version: Debian

**Comment by martinrotter** [comment] 2021-09-02 09:01
> I did an import from 3.9.x using File > Restore
Not supporting 3.9.x and probably never will. I will make adjustments to make somehow know that fact. Preferably repeat your testing with clean RSS Guard data folder, please.

**Comment by zero77** [comment] 2021-09-02 09:04
What's the recommended way to import feeds from 3.9.x.

**Comment by martinrotter** [comment] 2021-09-02 09:14
@zero77 There is none, RSS Guard uses completely overhauled database layer and automatic import from 3.9.x will not be possible.

I will probably provide some DIY manual to transfer your data in documentation.

Also, I checked the issue and here with SSH-ed socks it works. I added more logging - afd9991.

Wait 30 minutes and test with latest dev. build. Then provided updated log, pls.

**Comment by martinrotter** [comment] 2021-09-03 09:02
Cannot reproduce, closing.

**Closed by martinrotter** 2021-09-03 09:02 UTC
Labels: Type-Defect

**Comment by zero77** [comment] 2021-09-03 09:56
@martinrotter
So after a bit more testing i think it may have been my fault.
I did a back up and restore from the old version, i tried it again using opml file export and that worked without any problem.
Thanks for your help.

To prevent users making the same mistake, it may be worth adding a gui error letting them know that older config and db are not compatible.

**Comment by aleksejrs** [comment] 2022-10-04 13:51
It just happened to me with 4.0.4 on Debian. It seemed like fetching used the general proxy setting instead of the per-account one.
