### ISSUE TITLE
Update process for feeds doesn't finish

### ISSUE THREAD

**Issue by fanteik** [martinrotter/rssguard#177] opened 2018-01-07 17:25 UTC
#### Brief description of the issue.

Update of all feeds of my tiny tiny rss account often never ends. That means, after some time the update process show no progress anymore. I also can't stop the update (e.g. "stop running update"). 
So, I end with some feeds updated, all other will never get an update. 

#### How to reproduce the bug?

Use a tiny tiny rss server with many feeds (I have 100).

1. Start rssguard
2. Start "update all items"
3. Wait some time (more than 30 seconds)

#### Other information (logs, see Wiki)

Output of the program:
[rssguard] DEBUG: I will start next check for cached service data in 30 seconds. (18/07/01 18:15:46)
[rssguard] DEBUG: Delaying scheduled feed auto-updates for one minute due to another running update. (18/07/01 18:16:46)
[rssguard] DEBUG: Starting next check for cached service data in NOW. (18/07/01 18:16:46)
[rssguard] DEBUG: I will start next check for cached service data in 30 seconds. (18/07/01 18:16:46)
[rssguard] DEBUG: Delaying scheduled feed auto-updates for one minute due to another running update. (18/07/01 18:17:46)
[rssguard] DEBUG: Starting next check for cached service data in NOW. (18/07/01 18:17:46)
[rssguard] DEBUG: I will start next check for cached service data in 30 seconds. (18/07/01 18:17:46)
[rssguard] DEBUG: Delaying scheduled feed auto-updates for one minute due to another running update. (18/07/01 18:18:46)
[rssguard] DEBUG: Starting next check for cached service data in NOW. (18/07/01 18:18:46)
[rssguard] DEBUG: I will start next check for cached service data in 30 seconds. (18/07/01 18:18:46)

**Comment by martinrotter** [comment] 2018-01-08 05:31
Can you post complete log?

Also, can you make testing account on your server for me to check the issue? Or perhaps can you export list of feeds for me to test on my own tt-rss instance?

**Comment by fanteik** [comment] 2018-01-08 22:59
I append the complete log with the error (2018_01_07-rssguard-log.txt) and the OPML file.

Today I start rssguard again and have had no problem (2018_01_08-rssguard-log.txt).

[files.zip](https://github.com/martinrotter/rssguard/files/1613359/files.zip)

**Comment by martinrotter** [comment] 2020-06-02 04:58
I create merged ticket for similar problems which have probably the same root cause - head over there to discuss or inform me of development on your side.

https://github.com/martinrotter/rssguard/issues/237

**Closed by martinrotter** 2020-06-02 04:58 UTC
