### ISSUE TITLE
[BUG]: next unread article hotkey on space also scrolls down those articles when opened

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#722] opened 2022-05-04 13:19 UTC
### Brief description of the issue

[BUG]: next unread article hotkey on space also scrolls down those articles when opened

### How to reproduce the bug?

set `space` as the hotkey for "next unread article"
select a feed with unread articles
press space

### What was the expected result?

unread article opened

### What actually happened?

unread article opened,
unread article also scrolled down

### Debug log

not needed  I suppose

### Operating system and version

* OS: Win10
* RSS Guard version: RSS Guard
Version: 4.3.1 (built on Windows/AMD64)
Revision: 871c92c1-nowebengine
Build date: 4/28/22 8:48 AM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by Owyn** [comment] 2022-05-06 11:01
You need to select a folder first, and there should be no article in the viewer currently, because only first article you go to is scrolled down, rest work fine.

Try like on the video:

https://user-images.githubusercontent.com/1309656/167119551-74f644d4-fa07-414d-8c96-003229fccca4.mp4

**Comment by Owyn** [comment] 2022-05-06 11:19
You are using webengine on your video... try it with nowebengine

**Comment by martinrotter** [comment] 2022-05-06 13:58
> You are using webengine on your video... try it with nowebengine

No, I am not. I am pretty sure I have compiled as nowebengine.

**Comment by Owyn** [comment] 2022-05-06 14:47
> > You are using webengine on your video... try it with nowebengine
> 
> No, I am not. I am pretty sure I have compiled as nowebengine.

But it looks entirely different from my nowebengine, cuz it has url bar, tons of buttons at the top and at the left etc...

**Comment by martinrotter** [comment] 2022-05-10 05:52
> > > You are using webengine on your video... try it with nowebengine
> > 
> > 
> > No, I am not. I am pretty sure I have compiled as nowebengine.
> 
> But it looks entirely different from my nowebengine, cuz it has url bar, tons of buttons at the top and at the left etc...

![image](https://user-images.githubusercontent.com/1255302/167557626-c5a63a6a-edc6-453d-9e8d-4496eda8fc67.png)

**Comment by martinrotter** [comment] 2022-05-10 05:53
Also, try with completely default setup - clean "data" folder, default skin, default style etc. I cannot reproduce, closing. Feel free to re-open if you determine factors needed to reproduce the issue.

**Closed by martinrotter** 2022-05-10 05:53 UTC
Labels: Type-Defect, Status-Invalid
