### ISSUE TITLE
[FR]: Automatically apply selected article filters to new added feeds

### ISSUE THREAD

**Issue by RetroAbstract** [martinrotter/rssguard#842] opened 2022-11-13 23:05 UTC
### Brief description of the feature request

This feature would allow the user to select article filters to automatically apply to new added feeds.

**Comment by akinokonomi** [comment] 2022-11-13 23:37
Duplicate of https://github.com/martinrotter/rssguard/issues/775

**Closed** 2022-11-21 08:05 UTC
Labels: Status-Duplicate, Type-Enhancement
