### ISSUE TITLE
[BUG]: RSS Guard sometimes crashes when fetching feeds

### ISSUE THREAD

**Issue by enxas** [martinrotter/rssguard#904] opened 2023-02-28 21:04 UTC
### Brief description of the issue

RSS Guard sometimes crashed when fetching all feeds

### How to reproduce the bug?

Click "Fetch all feeds" button

### What was the expected result?

not crashing

### What actually happened?

RSS Guard sometimes crashes

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/10854734/rssguard.log)

![Windows Event Viewer entry](https://user-images.githubusercontent.com/8630984/221978758-a9ce98eb-569d-4a56-be14-99753b9da508.png)

### Operating system and version

* OS: Windows 10 64bit 22H2
* RSS Guard version: 4.3.2

**Comment by martinrotter** [comment] 2023-03-16 11:06
I was not able to reproduce the problem. If you discover some related information, feel free to reopen.

**Comment by enxas** [comment] 2023-03-16 11:53
I have over 100 feeds and they all are YouTube feeds. What I have noticed, if I fetch all feeds after not fetching for a couple of days, then most of the time RSS Guard crashes when fetching

**Comment by martinrotter** [comment] 2023-03-16 11:56
> I have over 100 feeds and they all are YouTube feeds. What I have noticed, if I fetch all feeds after not fetching for a couple of days, then most of the time RSS Guard crashes when fetching

could you perhaps export your list of feeds to opml and provide here for me to test?

also post exact version of rssguard you use, thanks

**Comment by enxas** [comment] 2023-03-16 12:53
I use RSS Guard version 4.3.2 on Windows 10 64 bit 22H2. Attaching my Feeds.

[rssguard_feeds_2023-03-16.zip](https://github.com/martinrotter/rssguard/files/10990905/rssguard_feeds_2023-03-16.zip)

**Comment by mvertes** [comment] 2023-04-02 09:03
In my Linux system, version rssguard-4.3.3, it also often (not always) crashes with a segmentation faut. Here is the last debug messages printed and gdb stack trace:

```
time=" 12833.091" type="debug" -> feed-downloader: Made progress in feed updates total feeds count 122/196 (id of feed is 62).
time=" 12833.091" type="debug" -> database: SQLite connection 'db_connection_140736414611136' is already active.                                                                                                                    
time=" 12833.091" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 122/196 (id of feed is 63).                                                                                                     
time=" 12833.091" type="debug" -> database: SQLite database connection 'db_connection_140736414611136' to file '/home/marc/.config/RSS Guard 4/database/database.db' seems to be established.                                                      
time=" 12833.091" type="debug" -> feed-downloader: Downloading new messages for feed ID 'feed/146' URL: 'https://fly.io/' title: 'The Fly Blog' in thread  '140737127630528'.
time=" 12833.091" type="debug" -> feed-downloader: Downloading new messages for feed ID 'feed/183' URL: 'http://simonwillison.net/' title: 'Simon Willison's Weblog: Entries' in thread  '140736389433024'.
time=" 12833.091" type="debug" -> database: SQLite connection 'db_connection_140737127630528' is already active.
time=" 12833.091" type="debug" -> database: SQLite connection 'db_connection_140736389433024' is already active.
time=" 12833.091" type="debug" -> database: SQLite database connection 'db_connection_140737127630528' to file '/home/marc/.config/RSS Guard 4/database/database.db' seems to be established.
time=" 12833.091" type="debug" -> database: SQLite database connection 'db_connection_140736389433024' to file '/home/marc/.config/RSS Guard 4/database/database.db' seems to be established.

Thread 10 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe8bbf6c0 (LWP 6636)]
0x00007ffff77a9d20 in QtPrivate::RefCount::ref() ()
   from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
(gdb) bt
#0  0x00007ffff77a9d20 in QtPrivate::RefCount::ref() () from /mu/rssguard/4.3.3-#0  0x00007ffff77a9d20 in QtPrivate::RefCount::ref() () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#1  0x00007ffff77b7bb7 in Message::Message(Message const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#2  0x00007ffff79831fc in GreaderNetwork::getMessagesIntelligently(ServiceRoot*, QString const&, QHash<ServiceRoot::BagOfMessages, QStringList> const&, QHash<QString, QStringList> const&, QNetworkProxy const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#3  0x00007ffff7988d51 in GreaderServiceRoot::obtainNewMessages(Feed*, QHash<ServiceRoot::BagOfMessages, QStringList> const&, QHash<QString, QStringList> const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#4  0x00007ffff77b4394 in FeedDownloader::updateOneFeed(ServiceRoot*, Feed*, QHash<ServiceRoot::BagOfMessages, QStringList> const&, QHash<QString, QStringList> const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#5  0x00007ffff77b5dbc in FeedDownloader::updateThreadedFeed(FeedUpdateRequest const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#6  0x00007ffff77b5efc in std::_Function_handler<FeedUpdateResult (FeedUpdateRequest const&), FeedDownloader::updateFeeds(QList<Feed*> const&)::{lambda(FeedUpdateRequest const&)#1}>::_M_invoke(std::_Any_data const&, FeedUpdateRequest const&) ()
   from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#7  0x00007ffff77b62c1 in QtConcurrent::MappedEachKernel<QList<FeedUpdateRequest>::const_iterator, std::function<FeedUpdateResult (FeedUpdateRequest const&)> >::runIterations(QList<FeedUpdateRequest>::const_iterator, int, int, FeedUpdateResult*) ()
   from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#8  0x00007ffff77bb854 in QtConcurrent::IterateKernel<QList<FeedUpdateRequest>::const_iterator, FeedUpdateResult>::forThreadFunction() ()
   from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
#9  0x00007ffff7f0ea7d in QtConcurrent::ThreadEngineBase::run() () from /usr/lib64/libQt5Concurrent.so.5
#10 0x00007ffff58d6401 in ?? () from /usr/lib64/libQt5Core.so.5
#11 0x00007ffff58d3469 in ?? () from /usr/lib64/libQt5Core.so.5
#12 0x00007ffff5293caa in start_thread () from /lib64/libc.so.6
#13 0x00007ffff531dd9c in clone3 () from /lib64/libc.so.6
(gdb)
```

**Comment by martinrotter** [comment] 2023-04-03 05:23
> In my Linux system, version rssguard-4.3.3, it also often (not always) crashes with a segmentation faut. Here is the last debug messages printed and gdb stack trace:
> 
> ```
> time=" 12833.091" type="debug" -> feed-downloader: Made progress in feed updates total feeds count 122/196 (id of feed is 62).
> time=" 12833.091" type="debug" -> database: SQLite connection 'db_connection_140736414611136' is already active.                                                                                                                    
> time=" 12833.091" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 122/196 (id of feed is 63).                                                                                                     
> time=" 12833.091" type="debug" -> database: SQLite database connection 'db_connection_140736414611136' to file '/home/marc/.config/RSS Guard 4/database/database.db' seems to be established.                                                      
> time=" 12833.091" type="debug" -> feed-downloader: Downloading new messages for feed ID 'feed/146' URL: 'https://fly.io/' title: 'The Fly Blog' in thread  '140737127630528'.
> time=" 12833.091" type="debug" -> feed-downloader: Downloading new messages for feed ID 'feed/183' URL: 'http://simonwillison.net/' title: 'Simon Willison's Weblog: Entries' in thread  '140736389433024'.
> time=" 12833.091" type="debug" -> database: SQLite connection 'db_connection_140737127630528' is already active.
> time=" 12833.091" type="debug" -> database: SQLite connection 'db_connection_140736389433024' is already active.
> time=" 12833.091" type="debug" -> database: SQLite database connection 'db_connection_140737127630528' to file '/home/marc/.config/RSS Guard 4/database/database.db' seems to be established.
> time=" 12833.091" type="debug" -> database: SQLite database connection 'db_connection_140736389433024' to file '/home/marc/.config/RSS Guard 4/database/database.db' seems to be established.
> 
> Thread 10 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffe8bbf6c0 (LWP 6636)]
> 0x00007ffff77a9d20 in QtPrivate::RefCount::ref() ()
>    from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> (gdb) bt
> #0  0x00007ffff77a9d20 in QtPrivate::RefCount::ref() () from /mu/rssguard/4.3.3-#0  0x00007ffff77a9d20 in QtPrivate::RefCount::ref() () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #1  0x00007ffff77b7bb7 in Message::Message(Message const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #2  0x00007ffff79831fc in GreaderNetwork::getMessagesIntelligently(ServiceRoot*, QString const&, QHash<ServiceRoot::BagOfMessages, QStringList> const&, QHash<QString, QStringList> const&, QNetworkProxy const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #3  0x00007ffff7988d51 in GreaderServiceRoot::obtainNewMessages(Feed*, QHash<ServiceRoot::BagOfMessages, QStringList> const&, QHash<QString, QStringList> const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #4  0x00007ffff77b4394 in FeedDownloader::updateOneFeed(ServiceRoot*, Feed*, QHash<ServiceRoot::BagOfMessages, QStringList> const&, QHash<QString, QStringList> const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #5  0x00007ffff77b5dbc in FeedDownloader::updateThreadedFeed(FeedUpdateRequest const&) () from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #6  0x00007ffff77b5efc in std::_Function_handler<FeedUpdateResult (FeedUpdateRequest const&), FeedDownloader::updateFeeds(QList<Feed*> const&)::{lambda(FeedUpdateRequest const&)#1}>::_M_invoke(std::_Any_data const&, FeedUpdateRequest const&) ()
>    from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #7  0x00007ffff77b62c1 in QtConcurrent::MappedEachKernel<QList<FeedUpdateRequest>::const_iterator, std::function<FeedUpdateResult (FeedUpdateRequest const&)> >::runIterations(QList<FeedUpdateRequest>::const_iterator, int, int, FeedUpdateResult*) ()
>    from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #8  0x00007ffff77bb854 in QtConcurrent::IterateKernel<QList<FeedUpdateRequest>::const_iterator, FeedUpdateResult>::forThreadFunction() ()
>    from /mu/rssguard/4.3.3-6c463b81/lib64/librssguard.so
> #9  0x00007ffff7f0ea7d in QtConcurrent::ThreadEngineBase::run() () from /usr/lib64/libQt5Concurrent.so.5
> #10 0x00007ffff58d6401 in ?? () from /usr/lib64/libQt5Core.so.5
> #11 0x00007ffff58d3469 in ?? () from /usr/lib64/libQt5Core.so.5
> #12 0x00007ffff5293caa in start_thread () from /lib64/libc.so.6
> #13 0x00007ffff531dd9c in clone3 () from /lib64/libc.so.6
> (gdb)
> ```

Does bug happen only with your "Greader" account?

**Comment by martinrotter** [comment] 2023-04-03 05:28
OK, managed to reproduce the problem.

**Comment by mvertes** [comment] 2023-04-03 10:10
@martinrotter thanks for the prompt response. Testing your last commit 287e1da
No crash at the first feed update, good sign. Leaving it for a few hours to be sure.

**Comment by umbellipher** [comment] 2023-04-03 18:49
I've been running 287e1da for the last few hours. I seems to have fixed the crashing problem. Which is good, because it was driving me maaaad. I'll post of there's a future issue arising.

**Comment by mvertes** [comment] 2023-04-04 07:32
I have had a crash using 287e1da at the initial feed sync triggered by the timer 15s after start. Unfortunately not under gdb and coredumps were disabled. It does not reproduce just after. I will try again with proper setup tomorow morning to let updates building up. All my feeds are synced from a remote freshrss server through greader.

**Comment by martinrotter** [comment] 2023-04-04 13:37
OK, I added greader-based account to my RSS Guard testing instance and let it run - so far several hours with 40+ feeds and no crashes. It would be great if we could somehow narrow the area where the bug is. Perhaps there are some specific account-wide options you have activated?

**Comment by martinrotter** [comment] 2023-04-12 04:44
Unlikely.

**Comment by martinrotter** [comment] 2023-04-21 05:33
I will close this. Feel free to re-open if you have some new crashes and provide crashdump (stack).

**Closed by martinrotter** 2023-04-21 05:33 UTC
Labels: Type-Defect, Status-Invalid
