### ISSUE TITLE
3.8.4 - issues with adblock

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#322] opened 2020-12-14 13:11 UTC
I was in internal browser and selected adblock from the menu and rssgaurd crashed.  I restarted and selected and it takes a log time to show filter lists and crashes occasionally or gives a message about closing.

**Comment by martinrotter** [comment] 2020-12-14 13:23
Do you have rssguard process standard/error output? Log to a file and post a log perhaps.

**Comment by pcause** [comment] 2020-12-14 15:33
is there a setting on windows to capture a log?  I don't see.  Sorry if I'm missing something.  Portable installation.

**Comment by martinrotter** [comment] 2020-12-15 09:08
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#cli

**Comment by martinrotter** [comment] 2020-12-15 09:12
I have a hard time reproducing this, for me it does not crash, log could help.

**Comment by martinrotter** [comment] 2021-01-07 07:18
I made some significant testing and was not able to reproduce :( closing. Feel free to re-open if any new symptoms or something comes up.

**Closed by martinrotter** 2021-01-07 07:18 UTC
Labels: Component-Web-Browser, Status-Needs-Help, Status-Not-Enough-Data, Type-Defect
