### ISSUE TITLE
Linux AppImage crashes when URL link is clicked on

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#211] opened 2019-06-17 15:55 UTC
#### Brief description of the issue.
Using 3.5.8 and 3.5.9 on Ubuntu 18.04 with Unity desktop, everytime I try clicking on the URL link for an article, the application crashes.

#### How to reproduce the bug?

1. Download the AppImage & make it executable
2. Navigate to an article
3. Click on the blue-boxed URL link for the article

#### What is the expected result?

The article should be downloaded and displayed in the window within the RSSGuard

#### What actually happened?

Application immediately crashed; didn't happen with 3.5.6 (Does with 3.5.8 & 3.5.9)

**Comment by cement-head** [comment] 2019-06-18 18:31
[rss-log.txt](https://github.com/martinrotter/rssguard/files/3302924/rss-log.txt)

**Comment by cement-head** [comment] 2019-06-18 18:33
Is the libnss3 library being installed to an "incorrect" location?  Is the fix to symlink the file location?

**Comment by martinrotter** [comment] 2019-06-27 18:24
I tested myself and wasn't able to reproduce the issue.

**Comment by cement-head** [comment] 2019-07-05 15:11
3.5.6 works perfectly.  Using Ubuntu 18.04 Unity.  Maybe I have a missing depedency?  But I though AppImages negated that issue.  What changed between 3.5.6 and 3.5.6+ in terms of handling of the URL?

**Comment by cement-head** [comment] 2019-07-05 15:21
Maybe this is the same issue: https://github.com/probonopd/linuxdeployqt/issues/35

**Comment by cement-head** [comment] 2020-02-07 16:04
Brand new install 18.04.3 LTS, using Unity, can reproduce the identical issue.

**Comment by martinrotter** [comment] 2020-04-20 05:11
> 3.5.6 works perfectly. Using Ubuntu 18.04 Unity. Maybe I have a missing depedency? But I though AppImages negated that issue. What changed between 3.5.6 and 3.5.6+ in terms of handling of the URL?

Literally nothing, really.

**Comment by martinrotter** [comment] 2020-04-20 05:11
OK, will test soon.

**Comment by cement-head** [comment] 2020-05-08 16:21
I think it's because the AppImage uses the library installed by FF, and not what's in the AppImage

libsoftokn3.so: cannot open shared object file:

**Comment by martinrotter** [comment] 2020-05-11 05:14
OK, will check myself and see to error. It is probably deployment error because in normal installations across all systems the error cannot be reproduced.

**Comment by martinrotter** [comment] 2020-05-11 08:33
@cement-head 

Could you please try if

https://bintray.com/martinrotter/rssguard/download_file?file_path=rssguard-3.6.1-41520351-linux64.AppImage

works?

**Comment by martinrotter** [comment] 2020-05-19 08:34
OK, closing for now, it seems fixed when I test it. Let me know if it really works for you too.

**Closed by martinrotter** 2020-05-19 08:34 UTC
Labels: Type-Defect, Type-Deployment
