### ISSUE TITLE
Loading owncloud news just crashes and gets error 

### ISSUE THREAD

**Issue by pixadex** [martinrotter/rssguard#32] opened 2016-06-29 03:23 UTC
So updating news on owncloud then crashes

this is the error http://imgur.com/ClJ86xO
Need to fix this fast please.

**Comment by martinrotter** [comment] 2016-06-29 04:23
Can you obtain debug logs for me? See Wiki for more info.

**Comment by martinrotter** [comment] 2016-06-29 04:25
If you need working RSS Guard, you can rollback to version 3.2.4 for example. Unfortunately, binary packages are not available, because I close the previous official website and migrated to github without taking backup, you will for sure find needed installer on some download sites.

**Comment by martinrotter** [comment] 2016-06-29 04:26
Also, this bug could potentially be duplicate of some other bugs, like #27. I need debug logs.

**Comment by pixadex** [comment] 2016-06-29 04:37
is this normal "is not recognized as an internal or external command"

**Comment by martinrotter** [comment] 2016-06-29 04:40
No, you are doing something wrong.

**Comment by pixadex** [comment] 2016-06-29 04:42
Will can you fix that problem because thats what I get rssguard is not recognized as an internal or external command, really need your help with this, teamviewer please.

**Comment by martinrotter** [comment] 2016-06-29 04:43
You are in the wrong folder.

**Comment by pixadex** [comment] 2016-06-29 04:45
Can I get folder direction like this C:\Program Files (x86)\RSS Guard<--

**Comment by martinrotter** [comment] 2016-06-29 04:47
You need to `cd` to folder which really contains `rssguard.exe`.

**Comment by pixadex** [comment] 2016-06-29 04:48
whats is cd like in disk format
?

**Comment by martinrotter** [comment] 2016-06-29 04:50
If you want to switch to another drive, you simply write for example `D:`, without `cd`.

**Comment by pixadex** [comment] 2016-06-29 04:51
:OOOOO ok now I understand ok

**Comment by pixadex** [comment] 2016-06-29 04:55
need help here   cd C:\Programs\rssguard\ on to CMD YES OR NO

**Comment by martinrotter** [comment] 2016-06-29 04:56
It is just EXAMPLE. You need to go to folder where YOU HAVE YOUR RSS GUARD installed.

**Comment by pixadex** [comment] 2016-06-29 04:57
OK I did and nothings there WITH Log.txt  proff http://imgur.com/wAibN97

**Comment by martinrotter** [comment] 2016-06-29 04:59
Did RSS Guard start after command `rssguard.exe > log.txt 2>&1`? If it did, `log.txt` must exist.

**Comment by pixadex** [comment] 2016-06-29 05:00
"_**NOTHING**_"...

**Comment by martinrotter** [comment] 2016-06-29 05:10
??? It was yes/no question. It RSS Guard did not start, then you are doing something wrong.

**Comment by pixadex** [comment] 2016-06-29 05:12
it started, but nothings there. teamviewer?

**Comment by martinrotter** [comment] 2016-06-29 05:16
Okay, give numbers.

**Comment by pixadex** [comment] 2016-06-29 05:17
OF what?

**Comment by martinrotter** [comment] 2016-06-29 05:18
Your teamviewer code, OMG.

**Comment by pixadex** [comment] 2016-06-29 05:25
OOO, ook, I have 4 monitors on so, ID 597 121 467 Password 4940

**Comment by martinrotter** [comment] 2016-06-29 05:32
Lags brutally.

**Comment by pixadex** [comment] 2016-06-29 05:33
fix

**Comment by martinrotter** [comment] 2016-06-29 05:33
Start cmd, for me.

**Comment by martinrotter** [comment] 2016-06-29 05:37
When you now exit RSS Guard, debug file gets finalized and you can send it to me.

**Comment by martinrotter** [comment] 2016-06-29 05:37
It is placed in `C:\Users\<user>\txt.log` file as I shown you.

**Comment by martinrotter** [comment] 2016-06-29 05:38
So now start RSS Guard with the command I shown you, reproduce the problem, close RSS Guard and upload file here by attaching it.

**Comment by pixadex** [comment] 2016-06-29 05:39
[log.txt](https://github.com/martinrotter/rssguard/files/338601/log.txt)

**Comment by pixadex** [comment] 2016-06-29 05:39
Log.txt only

**Comment by martinrotter** [comment] 2016-06-29 05:40
Bro, are you kidding, just repeat the command by hitting the `UP` arrow key on your keyboard. You now entered it incorrectly.

**Comment by pixadex** [comment] 2016-06-29 05:43
thats what I get no joke 
[0628/224110:ERROR:resource_bundle.cc(720)] Failed to load C:\Program Files (x86)\RSS Guard\resources\qtwebengine_devtools_resources.pak
Some features may not be available.
[rssguard] DEBUG: Instantiated Application class.
[rssguard] DEBUG: Available icon theme paths: 'C:\Program Files (x86)\RSS Guard\icons', ':\icons', 'C:\Program Files (x86)\RSS Guard\icons'.
[rssguard] DEBUG: Initializing settings in 'C:\Program Files (x86)\RSS Guard\data\config\config.ini' (portable way).
[rssguard] DEBUG: Installed icon themes are: ', 'Faenza'.
[rssguard] DEBUG: Loading icon theme 'Faenza'.
[rssguard] DEBUG: Skin 'base/vergilius.xml' loaded.
[rssguard] DEBUG: Starting to load active localization. Desired localization is 'en_US'.
[rssguard] DEBUG: Application localization 'en_US' loaded successfully, specifically sublocalization 'en' was loaded.
[rssguard] WARNING: Qt localization 'en' was not loaded.
[rssguard] DEBUG: Creating main application form in thread: '0x984'.
[rssguard] DEBUG: Creating tray icon menu.
[rssguard] DEBUG: Working database source was determined as SQLite file-based database.
[rssguard] DEBUG: File-based SQLite database connection 'MessagesModel' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database has version '6'.
[rssguard] DEBUG: Current row changed - row [-1,-1] source [-1, -1].
[rssguard] DEBUG: Auto-update timer started with interval 60000.
[rssguard] DEBUG: Adjusting column resize modes for MessagesView.
[rssguard] DEBUG: Showing the main window when the application is starting.
[rssguard] DEBUG: Showing tray icon.
[rssguard] DEBUG: Creating SystemTrayIcon instance.
[rssguard] DEBUG: Showing tray icon immediately.
[rssguard] DEBUG: Tray icon displayed.
[rssguard] DEBUG: File-based SQLite database connection 'StandardServiceEntryPoint' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'TtRssServiceEntryPoint' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'OwnCloudServiceEntryPoint' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'OwnCloudServiceRoot' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: File-based SQLite database connection 'RecycleBin' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: SQLite connection 'OwnCloudServiceRoot' is already active.
[rssguard] DEBUG: File-based SQLite database connection 'OwnCloudServiceRoot' to file 'C:\Program Files (x86)\RSS Guard\data\database\local\database.db' seems to be established.
[rssguard] DEBUG: Cleaning up resources and saving application state.
[rssguard] DEBUG: Close lock was obtained safely.
[rssguard] DEBUG: Destroying FormMain instance.
[rssguard] DEBUG: Destroying TabWidget instance.
[rssguard] DEBUG: Destroying FeedMessageViewer instance.
[rssguard] DEBUG: Destroying BaseToolBar instance.
[rssguard] DEBUG: Destroying MessagesView instance.
[rssguard] DEBUG: Destroying MessagesProxyModel instance.
[rssguard] DEBUG: Destroying MessagesModel instance.
[rssguard] DEBUG: Destroying BaseToolBar instance.
[rssguard] DEBUG: Destroying FeedsView instance.
[rssguard] DEBUG: Destroying FeedsProxyModel instance
[rssguard] DEBUG: Destroying FeedsModel instance.
[rssguard] DEBUG: Destroying TabBar instance.
[rssguard] DEBUG: Destroying StatusBar instance.
[rssguard] DEBUG: Destroying SystemTrayIcon instance.
[rssguard] DEBUG: Destroying Application instance.
[rssguard] DEBUG: Destroying Mutex instance.
[rssguard] DEBUG: Destroying IconFactory instance.

**Comment by pixadex** [comment] 2016-06-29 05:43
this is from txt file

**Comment by martinrotter** [comment] 2016-06-29 05:44
Yes, now you must reproduce the bug and then send debug file from it. This is just when you launched RSS Guard and closed immediately.

**Comment by pixadex** [comment] 2016-06-29 05:47
http://en.file-upload.net/download-11722447/txt.log.html

**Comment by pixadex** [comment] 2016-06-29 05:47
and plus ITS txt.log not log.txt

**Comment by pixadex** [comment] 2016-06-29 05:50
download link works

**Comment by martinrotter** [comment] 2016-06-29 05:52
I don't see any problems app did not crash. It would be visible in log. You need to make app crash. And then upload log.

Read [this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by pixadex** [comment] 2016-06-29 05:54
so time app crash send it to you? and re do the command ?

**Comment by martinrotter** [comment] 2016-06-29 05:56
Yes, start app with command, now reproduce the bug (crash the app "Loading owncloud news just crashes and gets error"), and then send log file.

**Comment by pixadex** [comment] 2016-06-29 05:59
AWW ok It would take an hour to the crash again so I'll load the command let it do as I was doing before as normal when rss guard crashes again as what I reported load back file?

**Comment by pixadex** [comment] 2016-06-29 06:14
Program is not loading any more with command

**Comment by pixadex** [comment] 2016-06-29 06:17
so what command do you want me to put in cmd?

**Comment by martinrotter** [comment] 2016-06-29 06:27
You can find the command when you hit `UP` arrow.

> AWW ok It would take an hour to the crash again so I'll load the command let it do as I was doing before as normal when rss guard crashes again as what I reported load back file?

Yes, but that is exactly what you have to do.

**Comment by pixadex** [comment] 2016-06-29 06:29
yea but I restarted my computer so... command code please

**Comment by martinrotter** [comment] 2016-06-29 06:30
`.\rssguard.exe > C:\Users\<YOUR_USER_NAME>\rssguard-debug-log.txt 2>&1`

**Comment by pixadex** [comment] 2016-06-29 06:32
nothing?loads

**Comment by pixadex** [comment] 2016-06-29 06:37
teamviewer again?

**Comment by martinrotter** [comment] 2016-06-29 06:38
OK, last time.

**Comment by pixadex** [comment] 2016-06-29 06:38
thank you. 597 121 467    3038

**Comment by martinrotter** [comment] 2016-06-29 06:40
OK, now wait until bug appears. Sometimes it is tricky to be able to reproduce the bug again, like in this case.

**Comment by pixadex** [comment] 2016-06-29 06:40
thank you I'll get back with the file. in a hour or two.

**Comment by pixadex** [comment] 2016-06-30 05:00
OK when I put the command in to cmd it works but with out it doesn't. Any answers?

**Comment by martinrotter** [comment] 2016-06-30 05:27
Not possible. RSS Guard itself does not even know that your run it with "command".

**Comment by pixadex** [comment] 2016-06-30 20:38
Will why does it do that then?

**Comment by pixadex** [comment] 2016-06-30 23:33
Yea still crashen with out command to cmd

**Comment by martinrotter** [comment] 2016-08-03 07:55
Please, you must really provide the log or stacktrace. I cannot instruct you in detail on how to do it, it is just little advanced PC usage.

**Comment by martinrotter** [comment] 2016-08-26 08:29
Closing this, feel free to reopen if you come with full app log and/or backtrace.

**Closed by martinrotter** 2016-08-26 08:29 UTC
Labels: bug, not-enough-data, plugin-owncloud, postponed
