### ISSUE TITLE
[BUG]: feed creates double records every time

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#343] opened 2021-01-24 20:50 UTC
![image](https://user-images.githubusercontent.com/3852762/105643074-766ea480-5e96-11eb-8d13-e410d5d4e226.png)

src
http://www.eof.gr/web/guest/withdrawalscosmetics/-/journal/rss/12225/18339?doAsGroupId=12225&refererPlid=13919

#### How to reproduce the bug?

1. add the feed to RSS Guard
2. update the feed multiple times

#### What was the expected result?

unique articles

#### What actually happened?

now there are duplicate articles

#### Other information

* OS: win7x64
* RSS Guard version: v3.8.3 - 3.8.5

**Comment by martinrotter** [comment] 2021-01-25 07:33
Managed to reproduce the bug.

**Comment by martinrotter** [comment] 2021-01-25 08:23
The bug is caused by very very non-standard behavior of the server providing the feed. The server APPENDS dynamic cookie ID to all URLs of each messages at each feed request, making them different each time the feed file is downloaded. This is totally against all RSS/ATOM standards.

RSS Guard identifies "uniqueness" of message with these attributes at the same time: title, URL, author. If message with same attributes is found in databse, it is then identified as THE message and is overwritten.

But with your feed, basically, when you download feed 1st time, you get message A with URL "aaa/bbb/**123456489**" and 2nd time you download same feed file, you also get message A but this time with different URL "aaa/bbb/**16549849**". Some part of those URLs is still changing - RSS Guard cannot handle that. This is feed's fault, not RSS Guard's fault.

URLs are just not the same even if the physically point to "same" website. The website expects that the caller uses cookies but RSS Guard at this point does not support cookies, because their usage is against RSS/ATOM principles.

**Comment by martinrotter** [comment] 2021-01-25 08:47
Anyway, I made dirty fix for this. Should now work.

**Closed by martinrotter** 2021-01-25 08:47 UTC
Labels: Component-DB, Priority-High, Type-Defect
