### ISSUE TITLE
Rssguard will not close before browser

### ISSUE THREAD

**Issue by Arnaudv6** [martinrotter/rssguard#93] opened 2017-01-29 08:15 UTC
When closing rssguard, its process lives on (and the tray icon stays though it is emptied) until I close the browser.

I think this has to do with the way Rssguard opens news in the browser.
My browser is qupzilla, my DE openbox.

I have tried with both
- default settings
- "use custom external web browser" set to "xdg-open" for redirection

Thanks for this awesome soft.

**Comment by martinrotter** [comment] 2017-01-29 10:55
So if you close rssguard without actually opening anything in ext. Browser then everything works and rssguard quits without problems?

**Comment by Arnaudv6** [comment] 2017-01-29 11:18
That's it !

**Comment by martinrotter** [comment] 2017-01-30 06:46
This is actually weird. The web browser process should be started independently from RSS Guard and should not interfere with RSS Guard in any possible way.

On Windows, I tested it right now, and I do not see any problems, so this must be platform-specific problem. I will test in Arch Linux soon.

**Comment by martinrotter** [comment] 2017-05-03 05:18
I cannot reproduce this. Bad luck, closing this. If you have any relevant logs or anything, I will re-open.

**Closed by martinrotter** 2017-05-03 05:18 UTC
Labels: Component-Core, Type-Defect

**Comment by Arnaudv6** [comment] 2017-05-16 21:17
Never mind, problem occurred on a very customized environment.
I altered my browser-launching script, and pointed directly to it in rssguard's settings,
instead of letting rssguard use the "system browser". Problem seems to have gone now.

**Comment by martinrotter** [comment] 2017-05-17 04:09
Perfect. :)
