### ISSUE TITLE
[BUG]: Inoreader login fails: There is error. unknown error

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#401] opened 2021-04-17 10:20 UTC
#### Brief description of the issue.

Inoreader account is unable to login when tested after authorising the login on the website.

#### How to reproduce the bug?

1. Try to use Inoreader and test the login.

#### What was the expected result?

For the login to report success.

#### What actually happened?

The login fails with the following message:
There is error. unknown error

#### Other information

* OS: Windows Pro 20H2 64-bit
* Desktop Environment: Yes
* RSS Guard version: 3.9.2

https://user-images.githubusercontent.com/80743272/115109630-38ee5480-9f77-11eb-8f2e-37d6d5567abb.mp4

**Comment by martinrotter** [comment] 2021-04-17 12:47
Does "standard" account work for you if you try to fetch some "https" feed? Do "http" feeds work?

**Comment by martinrotter** [comment] 2021-04-20 05:44
Duplicate of #400.

**Closed by martinrotter** 2021-04-20 05:44 UTC
Labels: Status-Fixed, Type-Defect
