### ISSUE TITLE
filter not always applying to existing messages

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#277] opened 2020-09-18 16:33 UTC
#### Brief description of the issue.

When you edit a filter to include some additional messages and then refresh the feed, sometimes the filter is applied to previous messages and sometimes it isn't. This makes harder to make sure the filter is gonna catch the intended messages.

#### How to reproduce the bug?

1. Refresh a feed.
2. Take note of a particular message.
3. Edit a filter for this feed to make it mark the message as read.
4. Refresh the feed.

#### What was the expected result?

The message gets marked as Read.

#### What actually happened?

The message remains unread.

#### Other information (logs, see Wiki)

The particular filter I'm seeing this happening with accepts all messages, but marks some of them as Read:

```
function filterMessage() {
  if (msg.title.includes("xxx")
     && msg.isRead == false) {
    msg.isRead = true;
    msg.isImportant = true;
    return 1;
  }
  else {
    return 1;
  }
}
```
Maybe this behavior is by design, but given that sometimes the filter gets applied to previous messages I prefer to ask, as it would be great if the filter worked this way for the reason stated above.

Thank you very much.

**Comment by martinrotter** [comment] 2020-09-19 18:02
Well. In advance, let me state what the actual "workflow" of filtering/saving messages is.

1. Download ALL messages from the online feed XML file.
2. Run each filter for all messages, if any filter rejects the message, then it is removed from list of messages.
3. Result list of "accepted" (and possibly modified) messages is then fed to function which **saves messages to DB**.

Note that the function which performs message saving into DB is VERY very very [sophisticated and complicated](https://github.com/martinrotter/rssguard/blob/master/src/librssguard/miscellaneous/databasequeries.cpp#L516), because it must cover many "weird" and specific situations and sometimes it is actually quite difficult to decide if some particular message is "new" or even decide if the "same" message already exists in DB.

You may want to check this [condition](https://github.com/martinrotter/rssguard/blob/master/src/librssguard/miscellaneous/databasequeries.cpp#L675) and specifically the **2** subcondition which usually applies to messages from ordinary XML feeds. In current code, RSS Guard will only "update" the existing message in DB with new data if message has changed date/time (in other words, it is "newer") and its textual content is changed in the same time. This logic works well, but unfortunately message filters brought new semantics into the process.

For example, the method automatically expects that ordinary XML messages which are downloaded from ordinary feeds are automatically "unread", therefore no checking for read/important state changes are done.

I will have to probably rewrite the condition to make it work better with filters...

**Comment by mpr0st** [comment] 2020-09-20 08:52
OK, first of all let me apologize, as I forgot ([once again](https://github.com/martinrotter/rssguard/issues/268#issuecomment-679836999) 😡) to mention that I access my feeds via Inoreader (maybe you could include this detail in the template for new issues?).

Regarding your comment, if this is going to be hard to fix, forget about it. I only want to be able to test filters more easily, and there are other ways to achieve that goal (#266, #278). In fact, what I have in mind when I request this is something very similar to #261.

Thank you.

**Comment by martinrotter** [comment] 2020-09-23 08:19
So, I did some testing.

The idea is that RSS Guard should of course "overwrite" the messages with read/important attribute changed by filters and I tested this:
1. Update the feed, new messages get downloaded, they are all unread.
2. Activate the filter which marks messages as read.
3. Update the feed again, now all previously downloaded messages are overwritten and marked as read in RSS Guard and also I see them correctly read in Inoreader web interface (in other words, changes made by filter were correctly synced-out to server).

So we probably could have some bug here, the feature is there and should work. Can you perhaps investigate if the issue concerns only some specific feeds/messages? Or perhaps your test case has some steps I missed as I am not really able to reproduce the issue.

**Comment by martinrotter** [comment] 2020-09-23 08:23
+ One extra note, at this point only change from UNREAD -> READ is synced back to servers. If you wish to also have READ -> UNREAD changes (made by filters) to have synced back to servers, let me know.

**Comment by martinrotter** [comment] 2020-09-23 08:25
Also note, that the syncing is not made immediately! Synchronization of message attribute changes is made once a minute, but is forced to be immediate if you for example re-update the feed consecutively in short time intervals etc.

**Comment by martinrotter** [comment] 2020-09-23 08:28
Also one important note.
The filter is of course applied only to messages which are DOWNLOADED FROM THE REMOTE server/feed.

On other words, if you have some older message which is only stored locally in RSS Guard and remote server/feed does not have it online, then naturally no filtering/adjustments of that message happen.

**Comment by mpr0st** [comment] 2020-09-23 11:35
OK, let me check all of this is some detail and I'll get back to you.

Thanks.

**Comment by martinrotter** [comment] 2020-10-26 11:19
Any updates on this? @mpr0st

**Comment by pcause** [comment] 2020-10-28 11:48
btw, ability to run filters on existing messages (and sync back changes) was requested in another issue

**Comment by martinrotter** [comment] 2020-10-28 16:54
@mpr0st RSS Guard should download **all** messages and all of them should be stored to DB and visible in message list, unless they are rejected by some of message filters. Is the issue reproducible for certain feed/message? If so, could you post URL of such a feed and title of message? Maybe you could examine RSS Guard console output for errors or some other hints.

**Comment by mpr0st** [comment] 2020-10-31 19:08
Hi again and thank you for your help with this issue.

First of all, regarding your previous question:

> only change from UNREAD -> READ is synced back to servers. If you wish to also have READ -> UNREAD changes (made by filters) to have synced back to servers, let me know

Yes, I think that in order to facilitate the coherence between what you see in Inoreader and RSS Guard, two-way synchronization would be better, so changes, made by filters, or manually, should be synced back.

Regarding your other question:

> pay attention to "Download only XX newest messages per feed" (do you took this setting into account?)

No! I didn't!! 😳 That explains the missing messages.

So, with that out of the way, I think I (kind of) reproduced the error. Here are the steps I've taken:

1. Fresh installation of portable rssguard-3.7.2-4effd1a-nowebengine-win64.
1. Added my Inoreader account and then updated it (500 messages per feed).
1. After that, my Neowin feed (http://www.neowin.net/news/rss/) shows these messages:
![image](https://user-images.githubusercontent.com/49242687/97786797-4f157d80-1bae-11eb-89d8-9f191ac5dd26.png)
which properly reflects what I see in the web (except the older messages, which is OK):
![image](https://user-images.githubusercontent.com/49242687/97786831-8d12a180-1bae-11eb-800f-8d6cbd5e9f4c.png)
1. I'm going to try to mark as read the "Save 94% off the cost of this Essential PHP Coding Bundle" message, so I create this filter:
![image](https://user-images.githubusercontent.com/49242687/97786910-fb576400-1bae-11eb-844e-7920f79c9e00.png)
1.  The filter passes the test, so it's correctly defined:
![image](https://user-images.githubusercontent.com/49242687/97787026-df07f700-1baf-11eb-9b65-d6c79ce25a66.png)
1. I update the feed, but the message it's not marked as read in RSS Guard:
![image](https://user-images.githubusercontent.com/49242687/97787078-34dc9f00-1bb0-11eb-8ceb-4029a91b309a.png)
and, of course, neither it is in Inoreader (waiting makes no difference).

So this test with a fresh installation discards my previous desynchronization theory.

Thank you!

Note: I tried removing the `&& msg.isRead == false` bit from the filter, but the result is the same. This is the text of the filter:
```
function filterMessage() {
  if ((/^Save (?:up to |)(?:\d{1,2}%|\$\d{1,2},\d{1,3}) off .*? (?:bundle|subscription|course|bootcamp)/i.test(msg.title)
     ) && msg.isRead == false) {
    msg.isRead = true;
    msg.isImportant = true;
    return 1;
  }
  else {
    return 1;
  }
}
```

**Comment by martinrotter** [comment] 2020-11-01 19:41
I did some testing with your data your provided. I tested in RSS Guard, in Chrome and via regex101 and your script works for me. It correctly detects the message(s) and marks them important and read.

Honestly, I have no idea, whot could go wrong here.

**Comment by martinrotter** [comment] 2020-11-01 19:43
Can you please start with clean profile and reproduce all those steps and provide FULL application log for me?

@pcause

**Comment by mpr0st** [comment] 2020-11-02 15:28
Sorry to bother you again, but I'm unable to generate a log. I'm following [this instructions](https://github.com/martinrotter/rssguard/wiki/Generating-debug-log-file) to the letter, but the file that gets created is empty (0 bytes):

```
C:\progs\RSS Guard clean>del log.txt

C:\progs\RSS Guard clean>.\rssguard.exe > log.txt 2>&1

[RSS Guard opens, I update a feed and then File/Quit it]

C:\progs\RSS Guard clean>dir log.txt
 Volume in drive C has no label.
 Volume Serial Number is XXXX-XXXX

 Directory of C:\progs\RSS Guard clean

02-Nov-20  16:22                 0 log.txt
               1 File(s)              0 bytes
               0 Dir(s)  39.664.832.512 bytes free

C:\progs\RSS Guard clean>
```

Thank you.

**Comment by martinrotter** [comment] 2020-11-02 19:17
@mpr0st I see, the same behavior here. I am sure that on Linux it works. On Windows, it does not. Jesus. It seems that Windows does not really support "dual" applications (ones that have GUI and write to command line at the same time). Let me fix this, will report back.

**Comment by martinrotter** [comment] 2020-11-02 19:46
OK, will fix tomorrow, it is bit deeper problem.

**Comment by martinrotter** [comment] 2020-11-03 08:08
OK, so I found a "bug" in Windows. Unfortunately, when you have GUI application, then it cannot "natively" write to console on Windows. There are some hacks to workaround the issue, but I decided to add "log to file" functionality directly to RSS Guard. So now, RSS Guard support command line switch "-l" (or "--log") to specify custom file to log into. So now you can write debug file log like this on Windows:
1. Open command line and navigate to RSS Guard's folder.
2. Run `.\rssguard.exe --log 'C:\store\logs\here.txt'`
3. RSS Guard will start and will write all its logs into the file specified. Note that file does not need to exist, but parent folder structure must exist before RSS Guard is launched.

Pls, test with latest dev build https://github.com/martinrotter/rssguard/commit/abe289cf69655ecd3406be38b574f21e4111a452 and let me know. :)

**Comment by mpr0st** [comment] 2020-11-03 18:31
There you go: [log.zip](https://github.com/martinrotter/rssguard/files/5483234/log.zip)

BTW, the new look is great!

**Comment by martinrotter** [comment] 2020-11-03 18:57
@mpr0st Can you perhaps point at some specific messages which were not correctly processed by filters? Or does the problem happen for all messages from the provided log?

**Comment by mpr0st** [comment] 2020-11-03 19:03
I repeated the same steps (clean installation, account configuration, feed update, filter creation, filter test, feed update several times, File/Quit), with the same filter trying to catch the same message from the same feed, and the result was the same (the message doesn't get marked as Read, nor as Important).

**Comment by martinrotter** [comment] 2020-11-03 19:13
@mpr0st Yes, but does the problem concern only one message or all message that you expect to catch with the filter?

**Comment by martinrotter** [comment] 2020-11-03 20:05
@mpr0st OK, jesus, man. You gave me some headache. I totally dissected that message.

Your regular expression is wrong, because it does not take **NON-BREAKABLE spaces** into account!!!! Unfortunately, Inoreader places non-breaking spaces often before "the" tokens.

Your critical string contains nbsp here: "Save 94% off the**NBSP**cost of this Essential PHP Coding Bundle" therefore, regex fails.

Now, we could solve this two ways:
1. I will sanitize all titles and replace non-breaking spaces with normal spaces.
2. You will make your regex more robust.

This is fixed version of your regex: `^Save (?:up to |)(?:\d{1,2}%|\$\d{1,2},\d{1,3}) off.* (?:bundle|subscription|course|bootcamp)`. Note that your regex is unnecessarily complex, perhaps it is intentional.

Anyway, test fixed regex and let me know if you would prefer to have titles (and contents?) sanitized.

**Comment by mpr0st** [comment] 2020-11-04 16:41
OMG, I could've been trying to guess something like that for a hundred years. I hope at least you were interested in essential PHP coding 😁. Thank you very much for your help.

For clarification, I've been making tests and, as you say, my regex doesn't work:
`^Save (?:up to |)(?:\d{1,2}%|\$\d{1,2},\d{1,3}) off .*? (?:bundle|subscription|course|bootcamp)`

But this one does work:
`^Save (?:up to |)(?:\d{1,2}%|\$\d{1,2},\d{1,3}) off.*? (?:bundle|subscription|course|bootcamp)`

The difference being there's no space in it after the word "off". So no need to change `.*?` for `.*`, I just have to remove that space from the regex to make it work (maybe there is another NBSP after "off" in the title?).

Anyway, answering your question, yes, I think the way to go here is to replace all NBSP for regular spaces in titles and contents, otherwise it's gonna be a nightmare (what if the NBSP is located between "up to"? how can I take something like that into account without going crazy?), and not only for regexs but for things like `msg.title.startsWith` or `msg.contents.includes`.

And finally, yes, the regex it's a little bit complex, I'm trying to catch several sponsored messages with a single regex while, at the same time, trying to avoid false positives.

BTW, do you have any idea about why Inoreader does this? Doesn't seem to have much logic...

Thank you!

**Comment by martinrotter** [comment] 2020-11-04 17:43
@mpr0st OK, I will add message's title and contents sanitization.

Also I have the exact idea why they do it. It's because in English, it is correct to NOT have "the" separated from next word by newline. Therefore, by inserting non-breaking space, they ensure that if line wrapping kicks in, then those two words do not get split. I hope I made it clear, my English is not that good.

**Comment by martinrotter** [comment] 2020-11-05 07:13
OK, titles of messages are now sanitized, including non-breaking spaces. Contents, however, are only converted from percent-encoding and not sanitized, because sanitization in contents could potentially break layout of the message contents.

Pls test. Also, there is a new documentation (WIP).

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#downloading-new-messages

**Comment by mpr0st** [comment] 2020-11-05 18:11
OK, understood.

Which is the build number to test?

Thank you.

**Comment by martinrotter** [comment] 2020-11-05 18:45
@mpr0st Simply try the latest build available https://bintray.com/martinrotter/rssguard/download_file?file_path=rssguard-3.8.0-d436451-win64.7z

**Comment by mpr0st** [comment] 2020-11-07 08:51
Hmmm, I'm afraid it doesn't work (with the first regex I posted):

![image](https://user-images.githubusercontent.com/49242687/98436746-2e818200-20de-11eb-9c89-a57f9c82c378.png)

I tried with my configured instance, the previous clean instance and a new clean instance, with rssguard-3.8.0-d436451-nowebengine-win64.7z.

Attached is the log obtained reproducing the steps above in a new clean instance, build d436451.

Thank you!
[log.zip](https://github.com/martinrotter/rssguard/files/5504496/log.zip)

**Comment by martinrotter** [comment] 2020-11-07 14:31
OK, can you for completeness post the exact contents of the message filter?

**Comment by martinrotter** [comment] 2020-11-07 14:51
OK, found error in my implementation, fixed with 951330bb.

Can you pls test with dev. build of this commit?

**Comment by mpr0st** [comment] 2020-11-07 18:04
It works!! Thank you very much!

**Comment by martinrotter** [comment] 2020-11-07 18:28
OK, fixed. :)

**Closed by martinrotter** 2020-11-07 18:28 UTC
Labels: Component-Core, Component-DB, Component-Message-Filters, Status-Partially-Fixed, Type-Defect
