### ISSUE TITLE
[FR]: Select multiple feeds and categories with Ctrl and Shift

### ISSUE THREAD

**Issue by shoulders** [martinrotter/rssguard#960] opened 2023-05-24 19:30 UTC
### Brief description of the feature request

I would like the ability to select multiple feeds using **CTRL** and **Shift** as you can with files in windows.

This is related to #959

**Comment by martinrotter** [comment] 2023-06-05 07:38
duplicate of #89

**Closed by martinrotter** 2023-06-05 07:38 UTC
Labels: Type-Enhancement
