### ISSUE TITLE
[BUG]: All menus are shown on screen 2 of a multiscreen computer

### ISSUE THREAD

**Issue by edwardgjohns3** [martinrotter/rssguard#1071] opened 2023-08-24 13:25 UTC
### Brief description of the issue

After upgrading to 4.5.0, all menus appear on screen 2 of a multi-screen system. They are vertically-aligned with where they should be. Horizontal alignment of the menus is on the left side of screen 2 when the RSS Guard main window is on screen 1, and correctly placed when RSS Guard main window is on screen 2. No log file was generated when I ran the command. I've restarted the app, reconnected the docking station, rebooted the computer, etc.

Version:

RSS Guard
Version: 4.5.0 (built on Windows/AMD64)
Revision: 7175578b6
Build date: 8/24/23 11:58 AM
Qt: 6.5.2 (compiled against 6.5.2)

### How to reproduce the bug?

1. Start app
2. Move main window to screen 1
3. Open any menu
4. Observe that they appear on screen 2 at correct vertical position
5. Move main window to screen 2
6. Open any menu
7. Observe that it opens in the correct place

### What was the expected result?

Expected the menu to appear near mouse for context-sensitive menus and near menu header with main menus.

### What actually happened?

They appeared on screen 2, at the correct vertical position. They only appeared at the correct horizontal position when the main window was also on screen 2.

### Debug log

time="     0.315" type="debug" -> core: Initializing settings in 'C:\Users\johnse54\AppData\Local\RSS Guard 4\config\config.ini' (non-portable way).
time="     0.316" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.317" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.317" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     1.292" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file 'C:\Users\johnse54\AppData\Local\RSS Guard 4\database\database.db' seems to be established.
time="     1.292" type="debug" -> database: File-based SQLite database has version '7'.
time="     1.296" type="debug" -> gui: Available icon theme paths: QList(:/icons, :/graphics, C:/Users/johnse54/AppData/Local\RSS Guard 4\icons, C:/Program Files/RSS Guard\icons)
time="     1.297" type="debug" -> gui: Installed icon themes are: '', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     1.298" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     1.298" type="debug" -> gui: Found path of base skin: ':\skins\nudus-base'.
time="     1.299" type="debug" -> gui: Local file ':\skins\nudus-dark\html_wrapper.html' exists, using it for the skin.
time="     1.299" type="debug" -> gui: Local file ':\skins\nudus-dark\html_style.css' exists, using it for the skin.
time="     1.300" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_image.html' for the skin.
time="     1.300" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_single_message.html' for the skin.
time="     1.300" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_enclosure_every.html' for the skin.
time="     1.301" type="debug" -> gui: Local file ':\skins\nudus-dark\qt_style.qss' exists, using it for the skin.
time="     1.301" type="debug" -> gui: Trying to load base file ':\skins\nudus-base\html_adblocked.html' for the skin.
time="     1.301" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     1.302" type="debug" -> gui: Setting style: 'Fusion'.
time="     1.302" type="debug" -> gui: Activating alternative palette.
time="     1.303" type="debug" -> gui: Skin 'nudus-dark' loaded.
time="     1.303" type="warning" -> core: User CSS style was not provided in file 'C:/Users/johnse54/AppData/Local\RSS Guard 4\web\user-styles.css'.
time="     1.304" type="debug" -> network: Persistent web data storage path: 'C:/Users/johnse54/AppData/Local\RSS Guard 4\web\storage'.
time="     1.304" type="debug" -> network: Disabling application-wide proxy completely.
time="     1.305" type="debug" -> core: SQLite version: '3.42.0'.
time="     1.314" type="debug" -> core: OpenSSL version: 'OpenSSL 3.1.0 14 Mar 2023'.
time="     1.314" type="debug" -> core: OpenSSL supported: 'true'.
time="     1.314" type="debug" -> core: Global thread pool has 24 threads.
time="     1.314" type="debug" -> core: Starting RSS Guard 4.5.0.
time="     1.315" type="debug" -> core: Instantiated class  'Application'.
time="     1.316" type="warning" -> core: Another instance of the application is already running. Notifying it.
time="     1.316" type="debug" -> core: Destroying Application instance.
time="     1.317" type="debug" -> core: Destroying Mutex instance.
time="     2.447" type="debug" -> gui: Destroying IconFactory instance.

### Operating system and version

* OS: Windows 11 Enterprise 22H2
* RSS Guard version: 4.5.0

**Comment by martinrotter** [comment] 2023-08-24 18:17
can you somehow make screenshot ?

**Comment by martinrotter** [comment] 2023-08-25 05:02
Also, please re-test now with installers from here.

https://github.com/martinrotter/rssguard/releases/tag/devbuild

**Comment by edwardgjohns3** [comment] 2023-08-25 13:38
Dev build 4.5.1 with 8/25/23 release date resolves the issue. Thanks!

**Comment by martinrotter** [comment] 2023-08-28 11:14
Yes, well. It seems that for some reason the bug appeared in Qt 6.5.2 libraries used by RSS Guard. This is sad, but I will have to keep latest Qt libs because there are some other withstanding bugs which are fixed by those libs.

So, I will re-update libs to 6.5.2 for next "devbuilds" and if the issue is really there, write me here and I will post this as a Qt bug upstream for devs to fix.

**Comment by martinrotter** [comment] 2023-09-05 09:39
Does this concern all context menus?

**Comment by martinrotter** [comment] 2023-09-05 09:44
Closing, upstream bug. Feel free to re-open after some months if not fixed.

**Closed by martinrotter** 2023-09-05 09:44 UTC
Labels: Type-Defect
