### ISSUE TITLE
[BUG]: b743c72a crashing intermittently on use of hotkey 'Mark selected item read'

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#563] opened 2021-12-24 11:59 UTC
### Brief description of the issue

As above.

### How to reproduce the bug?

1. Set hotkey as necessary.
2. Sync.
3. Select 'unread feeds' only in left pane.
4. Select feed from left pane.
5. Hit hotkey.
6. Move to next feed with 'next unread article' hotkey.

### What was the expected result?

Expected result: feed marked as read. Use of 'next unread article' hotkey moves you to next unread feed.

### What actually happened?

Sometimes the process happens normally. Sometimes the app freezes and closes. Sometimes use of the 'next unread article' hotkey itself is enough to crash the app.

### Other information

I've tried to generate a log, but have so far failed.

### Operating system and version

* OS: Windows 10 Pro build 19041
* RSS Guard version: b743c72a

**Comment by umbellipher** [comment] 2021-12-25 15:50
Oh, and I think 'open in external browser' has stopped working, also.

**Comment by martinrotter** [comment] 2021-12-26 15:02
I see, will look into it after holiday.

**Comment by martinrotter** [comment] 2021-12-26 15:03
Does it happen with 4.0.4 stable?

**Comment by umbellipher** [comment] 2021-12-30 18:22
I think I can clarify further.

The problematic hotkey is 'Mark selected item read (Mark all messages (without message filters) from selected items as read.)'

When this is deployed on a feed with more than one unread post, it functions, marking items as read and moving you on to the next feed with unread item(s). If deployed on a feed with only one unread item, Rssguard crashes.

I hope that may help.

**Comment by akinokonomi** [comment] 2021-12-31 04:49
@umbellipher, What hotkeys do you have assigned them to—_Next unread article_ and _Mark all messages [...]?_

For what it's worth, can't reproduce it by these steps on Arch Linux (b743c72a).

**Comment by umbellipher** [comment] 2021-12-31 08:25
'INS' and 'PG DN' on Win 10 Pro, respectively - using my daskeyboard numpad, numlock not enabled. These have not changed since first setup, and they worked before the last dev version. I did try to change them so as to go 'CTRL-INS' and 'CTRL-PG DN', but same effect.

**Comment by martinrotter** [comment] 2021-12-31 15:37
RN I am AFK, but will check.

**Comment by akinokonomi** [comment] 2022-01-01 04:13
Was able to reproduce it.

Steps a bit differ for me.

#### Conditions
Have an assigned shortcuts or Toolbar actions for:
- Mark item unread
- Next unread article.

#### Steps
1. Manually mark **one** article in multiple feeds as unread
2. Enable option "Show unread items only" (default keybinding `U`)
3. Click some feed just in case, and call _Next unread_ action
4. Now current feed has no unread articles, and we call _Mark item unread_ action
5. Crash

**Comment by umbellipher** [comment] 2022-01-02 18:28
I can expand on this now, with my 'Mark selected item read (Mark all messages (without message filters) from selected items as read.)' version of the issue.

1) It still obtains on the latest dev version, 0d046d6.

2) It's definitely the 'Mark selected item read (Mark all messages (without message filters) from selected items as read.)' hotkey, not the 'Next unread article' one.

3) If I hit the 'Mark selected item...' hotkey when either (a) there is only one unread item in a selected feed; or (b) the bottom unread item in a feed with multiple items is selected and highlighted, then the app crashes.

**Comment by martinrotter** [comment] 2022-01-03 07:04
@akinokonomi @umbellipher 

OK, I did fix some basic related fuckups I have found: af19e5376.

Can you test latest devbuild when it compiles? Also, I've found some related inconsistencies which I will have to tweak.

**Comment by umbellipher** [comment] 2022-01-03 08:55
Thank you. Version 4de3db8 now seems to work as concerns my hotkey issue. If others such as @akinokonomi agree, I'm happy to regard this as now closed.

**Comment by martinrotter** [comment] 2022-01-03 09:20
Yes, there are some rather minor UI aspects to maybe solve, but if it works, it works right. Let me know @akinokonomi and I can close this.

**Comment by akinokonomi** [comment] 2022-01-03 21:36
Fixed for me too.

**Closed** 2022-01-04 06:10 UTC
Labels: Type-Defect, Component-Feed-List, Status-Fixed
