### ISSUE TITLE
[BUG] Very slow

### ISSUE THREAD

**Issue by aleksejrs** [martinrotter/rssguard#955] opened 2023-05-16 21:45 UTC
I added lots of feeds and some labels since the beginning, so RSS Guard (with sqlite) is not very usable, *especially when it is fetching* (*e.g.*, stopping a fetch takes a long time as RSS Guard `4.2.5 `is "`Fetching common data`" or the feed name after I click the stop button). I updated to `4.3.4`, but it's almost constantly unusable (the slow operation uses only one process). But now `4.2.5` is also pretty bad. Maybe it's the kernel or Qt update, or file fragmentation (on btrfs), or a slow proxy if it isn't the UI.

The last line of debug info is usually at "`CTRL is NOT pressed while sorting articles - sorting with standard mode.`" Does that mean that the UI is slow? Also the checks for "`database: Message with custom ID '...' is already present in DB and has DB ID '...'.`" are taking up to a second each.

I filed this is a feature request for offline mode, but I am talking more about the slowness. It was "one thing could help me at least delete some labels and some big folders without waiting for the UI to become responsive **and** not letting it start fetching: an offline mode like in Firefox and Thunderbird."

**Comment by aleksejrs** [comment] 2023-05-16 23:45
> updated to 4.3.4, but it's almost constantly unusable

I suspect it's due to the kernel or Qt update. 4.2.5 is pretty bad now, too.

**Comment by martinrotter** [comment] 2023-05-17 06:17
"Fetching common data"

What kind of RSS Guard plugins/accounts do you use? Just classic RSS/ATOM or some other synchronized service?

As for labels - there are several performance problems which I am investigating RN, address them in proper ticket.

#952

**Comment by aleksejrs** [comment] 2023-05-17 17:08
The bigger profile has two RSS/ATOM/JSON accounts after cleanup:
* 335 feeds, 88 categories, 975419 unread articles. No proxy.
* 43 feeds, 4 categories, 43079 unread articles. Tor.
Globally, a Tor SOCKS proxy is used.

The smaller profile currently has one account after cleanup and is much more usable:
* 91 feeds, 47 categories, 92175 unread articles.

When I click Stop, it doesn't switch between feeds, but often continues checking if messages exist. At least with 4.3.4, it seems to show the name of the feed that was being checked more than "Fetching common data" (which is usually at the end).
There are many consecutive.
```
time=" 36039.032" type="debug" -> database: SQLite connection 'db_connection_[number]' is already active.
time=" 36039.032" type="debug" -> database: SQLite database connection 'db_connection_[number]' to file '[user]/.config/RSS Guard 4/database/database.db' seems to be established.
```

The two most annoying things related to performance are that
* the UI is completely locked often (the contents of the last active window from a different Xfce workspace are shown instead, except for the title)
* the "Edit" menu item is inactive when fetching, so it isn't easy to get there.

**Comment by martinrotter** [comment] 2023-06-05 07:39
Closing, likelz duplicate of #952 

test again with newest devbuild and report back

**Closed by martinrotter** 2023-06-05 07:39 UTC
Labels: Type-Enhancement
