### ISSUE TITLE
[BUG]: Application starting from version 3.8.2 does not start because of custom compiled QtWebEngine

### ISSUE THREAD

**Issue by Eleferen** [martinrotter/rssguard#337] opened 2021-01-11 12:15 UTC
#### Brief description of the issue.

Application starting from version 3.8.2 does not start

#### How to reproduce the bug?

1. Download the application and run the installation over the already installed

#### What was the expected result?

Application installed and worked

#### What actually happened?

Application installed and not worked (does not start)

#### Other information

Tested on version:
rssguard-3.8.4-7ab95a75-win64.exe
rssguard-3.8.3-03684f5-win64.exe
rssguard-3.8.2-12104c7-win64.exe

Latest working version:
3.8.0 (Windows/x86_64)
13c8ecf
10.11.2020 08:09
Qt: 5.14.2 (5.14.2)

Localisation: Russian
Windows 10 64bit

No log file is created, the command `rssguard.exe --log 'log.txt'` is not executed

**Comment by martinrotter** [comment] 2021-01-11 12:36
Wow, I start app literally everyday like twenty times. Do you say that even latest  3.8.4 official binaries do not start?

**Comment by martinrotter** [comment] 2021-01-11 12:51
Could you please try to run RSS Guard with PowerShell?

1. Open PowerShell window and navigate to RSS Guard's folder.
2. Write `.\rssguard.exe | Out-Default` and you should see debugging output directly in PowerShell now when RSS Guard starts.
3. Investigate the output for any weird stuff and perhaps paste it here?

**Comment by Eleferen** [comment] 2021-01-11 14:04
I`m testin at version rssguard-3.8.4-7ab95a75-win64.exe (https://github.com/martinrotter/rssguard/releases/download/3.8.4/rssguard-3.8.4-7ab95a75-win64.exe)

Screenshot of command `rssguard.exe --log 'log.txt'` output:
![image](https://user-images.githubusercontent.com/15795413/104190449-2d960500-542d-11eb-961d-0d6e39d9cce6.png)
command `rssguard.exe --help` is work
command `rssguard.exe --log 'log.txt'` is not work
Nothing just happens. The rssguard process hangs for a few seconds in the Windows manager and then disappears without starting.

Screenshot of command `. \ Rssguard.exe | Out-Default`:
![image](https://user-images.githubusercontent.com/15795413/104191145-2d4a3980-542e-11eb-9ae3-e729a502563e.png)
The symptoms are the same. The rssguard process hangs for a few seconds in the Windows manager and then disappears without starting. PowerShell displays nothing.

**Comment by martinrotter** [comment] 2021-01-11 18:00
@Eleferen Just to assure myself. If you ran `rssguard.exe --log 'log.txt'` no `log.txt` file appears in RSS Guard's directory?

**Comment by martinrotter** [comment] 2021-01-11 19:23
Are you trying to start RSS Guard with clean "data" folder? Perhaps there is something in the user data which triggers the bug? Can you **move**/**backup** your "data" folder and try with empty one? If the bug goes away, then we know the cause is in data and if it is, can you perhaps share the "data" folder with me, so that I could reproduce the bug?

**Comment by martinrotter** [comment] 2021-01-11 19:25
I will additionally test with clean latest Windows 10 in VirtualBox.

**Comment by martinrotter** [comment] 2021-01-12 06:21
Pls check if "data" folder makes any different and let me know, I am also willing to debug the problem with you over TeamViewer if you wish, I am really interested in finding the problem.

**Comment by Eleferen** [comment] 2021-01-12 08:56
> @Eleferen Just to assure myself. If you ran `rssguard.exe --log 'log.txt'` no `log.txt` file appears in RSS Guard's directory?

Yes. The log.txt file does not appear in the RSS Guard directory. The file is not created.
![image](https://user-images.githubusercontent.com/15795413/104289431-2e30a900-54ca-11eb-9836-9f2b87d45965.png)


I deleted the folder C:\Users\ <user_name>\AppData\Local\RSS Guard
I uninstall RSS Guard and deleted the folder C:\Program Files (x86)\RSS Guard
Then installed rssguard-3.8.4-7ab95a75-win64.exe in C:\Program Files (x86)\RSS Guard. RSS Guard still won't start :( I don't understand what could be the problem :(

**Comment by martinrotter** [comment] 2021-01-12 08:59
@Eleferen Does the same bug appear when you use "portable" RSS Guard and unpack it to custom directory like `C:\rssguard` - https://github.com/martinrotter/rssguard/releases/download/3.8.4/rssguard-3.8.4-7ab95a75-win64.7z

?

**Comment by martinrotter** [comment] 2021-01-12 09:06
Also the problem with log file could be that RSS Guard is in "Program Files" folder which is writable only for programs executed with admin privileges. Try the "7z" archive, unpack to custom folder and try to reproduce the bug, even pls try "--log" option again with that custom folder. There is something weird...

**Comment by martinrotter** [comment] 2021-01-12 09:18
@Eleferen One more thing. Right now I tested 3.8.4 with CLEAN latest 20H2 Windows 10 x64 freshly installed in VirtualBox. I installed RSS Guard, then executed "vc_redist.x64.exe" to install needed runtime libraries and then executed "rssguard.exe" and it ran without any problems.

**Comment by Eleferen** [comment] 2021-01-12 09:51
In the Windows system log, I found an error (sorry that in Russian):

_Имя сбойного приложения: rssguard.exe, версия: 3.8.4.0, метка времени: 0x5ff46a7e
Имя сбойного модуля: Qt5WebEngineCore.dll, версия: 5.15.1.0, метка времени: 0x5f69d595
Код исключения: 0x80000003
Смещение ошибки: 0x00000000001395ad
Идентификатор сбойного процесса: 0x245c
Время запуска сбойного приложения: 0x01d6e8c5e84672c9
Путь сбойного приложения: C:\Program Files (x86)\RSS Guard\rssguard.exe
Путь сбойного модуля: C:\Program Files (x86)\RSS Guard\Qt5WebEngineCore.dll
Идентификатор отчета: 2ef89c47-b1bd-4168-8fee-3940f45b8c40_

![image](https://user-images.githubusercontent.com/15795413/104297183-9b950780-54d3-11eb-9da0-e82c8f8543ee.png)
![image](https://user-images.githubusercontent.com/15795413/104298100-a69c6780-54d4-11eb-93ba-37c356467461.png)

**Comment by Eleferen** [comment] 2021-01-12 10:14
The portable version also didn't start. Even after manually installing vc_redist.x64.exe. The log file is also not created even in another directory on another disk

Apparently, the problem lies in my specific computer and installed programs and software environment.

**Comment by martinrotter** [comment] 2021-01-12 10:24
I believe I partly identified possible problem. Can you just for test try package https://github.com/martinrotter/rssguard/releases/download/3.8.4/rssguard-3.8.4-7ab95a75-nowebengine-win64.7z and test if it works? I believe that problem is that RSS Guard starting with version 3.8.1 uses custom-built QtWebEngine and it probably has some bug. Try https://github.com/martinrotter/rssguard/releases/download/3.8.4/rssguard-3.8.4-7ab95a75-nowebengine-win64.7z and let me know if there is any difference, thank you. :)

**Comment by Eleferen** [comment] 2021-01-12 10:39
@martinrotter This version works! https://github.com/martinrotter/rssguard/releases/download/3.8.4/rssguard-3.8.4-7ab95a75-nowebengine-win64.7z
I even gave her my settings.

![image](https://user-images.githubusercontent.com/15795413/104303401-1b72a000-54db-11eb-96fd-855b60ae80f4.png)

**Comment by martinrotter** [comment] 2021-01-12 10:47
@Eleferen Yes, settings are "portable" between all RSS Guard versions.

Now, is this non-webengine version enough for you, or should I try to fix the issue?

**Comment by Eleferen** [comment] 2021-01-12 11:01
@martinrotter I think this version is enough. If you have some free time, then I would not mind the version with a web engine.

Thank you so much for your help and your time spent solving this problem!

**Comment by martinrotter** [comment] 2021-01-12 11:02
@Eleferen Will try to fix, will post links here.

**Comment by martinrotter** [comment] 2021-01-12 11:25
@Eleferen OK, could you please test this exact file: https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.8.4-9df88887-win64.7z
Note that this package is very rough development binary but just see if the RSS Guard starts fine with this one - also try with empty "data" folder if it does not start with already existing "data" folder.

Let me know and we will then go from there.

**Comment by Eleferen** [comment] 2021-01-12 12:15
@martinrotter This version works with my "data": https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.8.4-9df88887-win64.7z
![image](https://user-images.githubusercontent.com/15795413/104312831-37307300-54e8-11eb-8eb8-585159716130.png)

**Comment by martinrotter** [comment] 2021-01-12 12:24
OK, there are some rough edges to smoothen out, but core bug is fixed. Thank you. :)

**Comment by martinrotter** [comment] 2021-01-12 18:28
@Eleferen I had to revert some code changes and I will go different path I will reopen this. Feel free to stick to no-webengine version for now. I will compile new Qt 5.15.2 with some webengine-specific tweaks and hopefully it will work better in the future.

**Comment by martinrotter** [comment] 2021-01-12 18:29
FOR ME: Compile QtWebengine with more flags allowed?

**Comment by martinrotter** [comment] 2021-01-15 11:45
@Eleferen OK, can you now pls test this new development build: https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.8.4-b2ef7e81-win64.7z

**Comment by Eleferen** [comment] 2021-01-19 09:37
@martinrotter The file https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.8.4-b2ef7e81-win64.7z appears to have been deleted?

**Comment by martinrotter** [comment] 2021-01-19 09:39
@Eleferen Those files in "devbuild" release are automagically overwritten by newly automatically compiled latest versions of RSS Guard. Therefore it is always the best to just go to

https://github.com/martinrotter/rssguard/releases/tag/devbuild

and pick your file from the list by hand. That way you will **always** get the most up to date development build for testing.

**Comment by Eleferen** [comment] 2021-01-19 15:49
@martinrotter 
**rssguard-3.8.4-1ad6005d-nowebengine-win64.7z** - works great 👍 
**rssguard-3.8.4-1ad6005d-nowebengine-win64.exe** - works great 👍 
**rssguard-3.8.4-1ad6005d-win64.7z** - does not work (rssguard does not start)
**rssguard-3.8.4-1ad6005d-win64.exe** - does not work (rssguard does not start)

**Comment by martinrotter** [comment] 2021-01-20 06:16
@Eleferen OK, my brother, one last push, be patient. Will prepare one more test build for you which will work I thing.

**Comment by martinrotter** [comment] 2021-01-20 07:33
@Eleferen OK, we are at the finish line: test latest devbuild binary please https://github.com/martinrotter/rssguard/releases/download/devbuild/rssguard-3.8.4-18a1d0e5-win64.7z

and let me know, thanks man.

**Comment by Eleferen** [comment] 2021-01-20 09:24
@martinrotter 
rssguard-3.8.4-18a1d0e5-nowebengine-win64.7z - works great 👍
rssguard-3.8.4-18a1d0e5-nowebengine-win64.exe - works great 👍
rssguard-3.8.4-18a1d0e5-win64.7z - works great 👍
rssguard-3.8.4-18a1d0e5-win64.exe - works great 👍

**Comment by martinrotter** [comment] 2021-01-20 11:43
@Eleferen Holy shit. Closing as solved and fixed. Have a nice day.

**Closed by martinrotter** 2021-01-20 11:43 UTC
Labels: Component-Web-Browser, Status-Partially-Fixed, Type-Defect, Type-Deployment

**Comment by martinrotter** [comment] 2021-01-20 13:45
@Eleferen Thank you for donation, it's cute.
