### ISSUE TITLE
Closing RSS Guard on Windows somethimes does not work (3.4.1)

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#121] opened 2017-06-13 08:47 UTC
#### Brief description of the issue.

When using the RSS Guard application for some time. Somethimes the application is unable to close, when right clicking on the tray icon and chosing "Quit".
The problem was not there before and I noticed it since the update that does the OwnCloud marking read in a batched way (every x minutes) instead of directly.
Could it be that some thread is not closed, where the exit process hangs?

#### How to reproduce the bug?

1. Install the app and connect to an Owncloud/NextCloud instances for News
2. Use the application for a while
3. Try closing the application via "quit" on the taskbar.

#### What is the expected result?
The expected result is that the application will close.

#### What actually happened?
Quite often the application is unable to close and needs to be "killed" via the Task manager.

#### Other information (logs, see Wiki)

I tried to log anything on the issue, but as the logfile is not directly dumped to the file, there is no information about "closing" in the end of the logfile and it is not filled anymore...

Latest tested with: rssguard-3.4.1-1ff2316-win32.7z

**Comment by martinrotter** [comment] 2017-09-09 07:31
The bug is caused by fact that RSS Guard tries to sent cached changes **when the application quits** and sometimes extra thread locks up. I am not able to reproduce the issue, thus I have to blindly try to fix this with something I think (yet not for sure) will work.

I plan to fix this like this:
 - there will be shorter interval of checking if there are any new message changes to be sent to server (now, it is 30 seconds, I will lower it to like 3 seconds), so that if you make any message state change like 5 seconds (OR MORE) BEFORE you quit the app, you should be OK,
 - unsent cached changes will be saved to disk and WILL NOT BE SENT TO SERVER WHEN APP QUITS, they will be reloaded when app is started again and sent then.

**Comment by martinrotter** [comment] 2017-09-09 12:15
Hey @groentebroer I attempted to fix the issue in another way. Can you, please, test build https://github.com/martinrotter/rssguard/commit/31cd7d5b01d9d86a529100a54967bab175ed58a7 when it is ready in development builds?

**Comment by groentebroer** [comment] 2017-09-11 13:34
Hi Martin
Great news, I will check it out and let it know afterwards

**Comment by groentebroer** [comment] 2017-09-12 19:30
Status update! Closed multiple times and does not seem to occur anymore!
Sounds good! Will now download the newer version to test the number of messages setting.

**Comment by groentebroer** [comment] 2017-09-12 19:42
Oke, my previous comment was somewhat too positive...
When installing the new version I got an error that the Qt5Core.dll could not be written. Although RSS Guard seemed closed. (No tray icon, settings where perfectly saved, etc.)

But actually the rssguard.exe was not completely closed, but came a little further then before (where the tray icon persisted and the status was not saved). And starting a new version seemed ok.


Error Message updating
![2017-09-12 21_37_15-rss guard portable setup](https://user-images.githubusercontent.com/1811817/30344814-1d02b8ee-9803-11e7-9cd8-834d623f30b8.png)


Multiple RSSGuard instances
![2017-09-12 21_36_33-task manager](https://user-images.githubusercontent.com/1811817/30344813-1d00c462-9803-11e7-87c7-788f2d809ea9.png)



Attached two screenshots indicating file in use still and multiple instances of rssguard.exe.

**Comment by martinrotter** [comment] 2017-09-12 20:16
I see, let me try something more, will notify you when need to test. Thanks. :)

**Comment by martinrotter** [comment] 2017-09-13 06:21
I made one more adjustment: the cache is now not sent to server on app exit, but is SAVED TO local file instead. On next RSS Guard launch, it is restored and sent.

Please test newest master if this particular issue is solved.

**Comment by groentebroer** [comment] 2017-09-13 09:03
Installed: 49fda7a, keep you posted.

**Comment by groentebroer** [comment] 2017-09-13 21:13
Still have a process rssguard.exe, while nothing being shown on the taskbar. Everything seems closed, but actually is not. Starting rssguard again, gives me a new rssguard.exe process. Could it be that my laptop went to sleep somewhere in between or something?

**Comment by martinrotter** [comment] 2017-09-14 05:23
Well, in that case, it really does not seem connected to OwnCloud at all. This is weird.

The sleep, well, I can try myself.

**Comment by martinrotter** [comment] 2017-09-14 06:48
@groentebroer I Will make SPECIAL build for you, which will turn off EVERYTHING RSS Guard does when it exits. This will help me to identify the probable place of our problem.

**Comment by martinrotter** [comment] 2017-09-14 07:14
https://transfer.sh/V0UNk/rssguard-3.4.3-3671ab7-win64.exe

Please, test this release - only test for this ticket - to see if this build will shutdown correctly.

**Comment by groentebroer** [comment] 2017-09-14 14:30
Oke, installed this version, will let you know what happens...

**Comment by groentebroer** [comment] 2017-09-14 21:04
The issue is still there after going home from work (laptop to sleep/hybernate). Opening it afterwards. Closing RSS guard. The exectuable stays in the process list. Starting again gives me another RRSGuard process.

**Comment by martinrotter** [comment] 2017-09-15 05:24
This is actually weird, because I removed all code which is executed when RSS Guard exits.

**Comment by martinrotter** [comment] 2017-09-15 05:25
The only way to diagnose the issue is probably run RSS Guard in Qt Creator in DEBUG mode and see, where it stucks, but this is rather technical stuff, thus probably not feasible.

**Comment by martinrotter** [comment] 2017-09-15 05:33
Does the bug occur if you DO NOT put PC to sleep?

**Comment by martinrotter** [comment] 2017-09-15 05:52
I MANAGED TO REPRODUCE THE ISSUE.

**Comment by groentebroer** [comment] 2017-09-15 07:01
I have not seen it without setting the PC to sleep (I cannot confirm that it never does...).
That you can reproduce it is a good thing right ;-) 👍

**Comment by martinrotter** [comment] 2017-09-15 07:02
Yes, it is, but I only managed it once, it seems to be quite random bug.

**Comment by martinrotter** [comment] 2017-09-15 08:41
Well, I made some research, and it seems that the factual bug is very complex. I have one idea,  what about this:
 - revert this feature to last working state, the change will be sent to server IMMEDIATELY when it is made,
 - I will do some enhancements to make sure that GUI is more responsive when changes are sent to server.

I think it is better to have WORKING worse feature than BUGGY better feature. What you think?

**Comment by martinrotter** [comment] 2017-09-18 06:48
OK, I completely removed any sort of caching, all changes are sent immediately, but in an asynchronous way, so it should not make GUI responsive too much.

Please test latest stuff and let me know.

https://github.com/martinrotter/rssguard/commit/efac9d1310856116f76527f48f0d16e7730f0420

**Comment by martinrotter** [comment] 2017-09-18 08:59
OK, @groentebroer please wait for https://github.com/martinrotter/rssguard/commit/7b62a456a6cf2a83aabadec4c333e4249531fec8 to get compiled and then please test. I made networking in owncloud cache differently, more simple and now it technically uses different way which should not block app exits. **Please test and let me know.**

If this will not work, then I will not cache changes and send them to server immediately, but in async way so that GUI will not stuck. This approach I used before 3.4.1 and it was working, but I will tweak it to not block GUi. But only if our latest attempt (above) fails.

**Comment by groentebroer** [comment] 2017-09-18 21:34
Oke, thanks! Give me a some moment, because I am rather busy currently :) Will let you know.

**Comment by martinrotter** [comment] 2017-09-22 04:57
Any updates? :)

**Comment by groentebroer** [comment] 2017-09-22 10:52
Yes, tried it for 2 days now and do not seem able to reproduce the issue.
Everything else seems to work oke! If it is up to mee, this is perfect now!

**Comment by martinrotter** [comment] 2017-09-22 11:05
OK, I am satistifed with the state too now. So the tweak is basically simple, there is now blocking behavior when sending cached state to online services, and changes are sent ONCE PER MINUTE.

Marking this as solved, feel free to re-open anytime.

**Closed by martinrotter** 2017-09-22 11:05 UTC
Labels: Component-Core, Component-DB, Component-Plugins-Nextloud, Component-Plugins-TT-RSS, Status-Accepted, Type-Defect
