### ISSUE TITLE
sync "read" status back to inoreader when a message has been marked as "read" by a filter

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#258] opened 2020-08-01 11:08 UTC
#### Brief description of the issue.

When a filter marks a message as "read" (using msg.isRead = true;) this "read" status is not sent to inoreader, so inoreader keeps seeing the message as "unread".

#### How to reproduce the bug?

1. Create a basic filter to mark a particular message from a particular feed as read:
```
function filterMessage() {
  if (msg.title.startsWith("Here's what's fixed")) {
    msg.isRead = true;
    return 1;
  }
  else {
    return 1;
  }
}
```
2. Test the filter updating the particular feed -> the message will be correctly marked as "read" automatically by the filter.
3. Update the feed once again to sync back this "read" status to inoreader.

#### What was the expected result?

The message appears as "read" in inoreader web interface.

#### What actually happened?

The message appears as "unread" in inoreader web interface.

#### Other information (logs, see Wiki)

This is not an issue with the inoreader connector, because when the message is manually marked as "read" by the user, the "read" status is correctly synchronized back to inoreader in the next update of the feed.

Thank you!!

**Comment by martinrotter** [comment] 2020-08-02 17:19
Hello @mpr0st.

You are completely right. I must admit, I totally forgot about this sub-feature and of course, If message is marked as read/important by the filter, then this change should be propagated to the "server". Thinking about this, it can make the filtering feature even more useful.

Will fix soon.

**Comment by mpr0st** [comment] 2020-08-02 17:31
Thank you very much.

**Closed** 2020-08-03 08:45 UTC
Labels: Component-Core, Component-Plugins-Base, Type-Defect

**Comment by martinrotter** [comment] 2020-08-03 08:50
So @mpr0st I pushed new changes which should automagically synchronise new state of your messages. Note that synchronization is done asynchronously and is done ONCE A MINUTE, so there may be a small delay between your feed's update in RSS Guard and new state visibility in Inoreader WEB client.

So far only these changes caused by message filters are saved:
unread -> read
unimportant -> important

So if your message  is important in your Inoreader server and your message filter marks it UNimportant, then this change is not synchronised. Also, state is only synchronised for messages which were ACCEPTED by the filter.

If you feel that some of this behavior is actually wrong, let me know.

Please, test the functionality in latest development build which has "962ba67" in its name. Thank you and let me know if it works, I expect some things to maybe break because this part of program functionality could be relatively fragile.

**Comment by mpr0st** [comment] 2020-08-04 18:17
Hi Martin. I've tested it with a test feed for a while and it seems to work perfectly. I will start configuring a few non-test filters in my feeds and will report back if I find any issues.

BTW, this filter functionality you just added is my dream come true, I can process the messages with Javascript and filter accordingly??? Incredibly powerful!!! Thank you very much.
