### ISSUE TITLE
How Prevent External Browser from Gaining Focus?

### ISSUE THREAD

**Issue by 88mm** [martinrotter/rssguard#304] opened 2020-11-26 03:01 UTC
I am using the lite version of RSS Guard and have a key (space) assigned to "Open selected source articles in external browser".  This works.  How do I prevent the focus from shifting to the external web browser (Firefox)?  

I wish to have RSS Guard open each selected article in a new tab in Firefox, which RSS Guard does, but NOT switch the focus to the external web browser each time I "select" an article in RSS Guard.   (I typically want to send several articles to the external web browser and then read them when I am finished with RSS Guard.)

**Comment by martinrotter** [comment] 2020-11-26 06:45
Hello.

@88mm When you launch firefox (or any other program), then it is brought to foreground (given focus) almost in every case, this is sadly the feature of windowing system (same thing happens on Linux and on Windows).

That said, you might check out https://superuser.com/questions/1346935/how-to-actually-start-program-minimized-in-windows-10

Firefox, specifically, should have command line parameter `-silent` which could help. It should automagically start firefox minimized, perhaps something like `firefox.exe -silent <URL>` could work.

**Comment by 88mm** [comment] 2020-11-26 19:42
martinrotter, thank you for the suggestion.  I will try the "-silent" switch  today in the RSS Guard custom external web browser executable parameters.
I guess I should have mentioned that I am using Linux.  (I figure there is some way to do this as the previous  RSS reader I was using, quiterss, pulled firefox into the foreground for about one second then quiterss popped back on top.)

**Comment by 88mm** [comment] 2020-11-26 20:19
"--silent" did not work.  Adding it had no effect.   However, below is a Firefox configuration change that keeps Firefox from gaining the focus when RSS Guard or any other application sends it a URL.  

In Firefox's about:config  change browser.tabs.loadDivertedInBackground  to True.

**Comment by martinrotter** [comment] 2020-11-27 05:11
I see, I tested it on Windows. Yes, you are right, on Linux (preferably under X11), there is a couple of better ways to actually bring window to foreground but I will also test again on Windows.

**Comment by martinrotter** [comment] 2020-11-27 06:03
It seem they use this to bring app window back to front after the tool is executed:

https://github.com/QuiteRSS/quiterss/blob/4bd7f02379572a5942b318e2a83e2079a8330f42/src/application/mainwindow.cpp#L244

**Comment by martinrotter** [comment] 2020-11-27 06:08
Btw, on Windows: "An application cannot force a window to the foreground while the user is working with another window. Instead, Windows flashes the taskbar button of the window to notify the user." (from microsoft docs)

I will add this feature for Linux and other OSES.

**Comment by martinrotter** [comment] 2020-11-27 06:33
OK, I think I fixed it for all platforms: 902570a0

Note that this feature will only work if you use "Open selected source articles in external browser" action. I did not enable new behavior for "external tools" because usually when users use custom external tools, they actually do want to bring external tool window to front, not RSS Guard.

Pls test with development build once it gets builded and let me know.

**Comment by martinrotter** [comment] 2020-11-27 08:39
Tested on Windows and Mac OS X, works.

**Comment by 88mm** [comment] 2020-11-27 19:33
There is an issue with the latest Linux build when using an external browser.  You may wish to re-open this thread.

I downloaded the latest zip from github.  For testing I configured and compiled  with:

    qmake ../rssguard-master/build.pro -r CONFIG+=release USE_WEBENGINE=false PREFIX=/tmp/rssguard
    make -j28
    make install

(btw: USE_WEBENGINE does not appear to default to false, so I added it.)

To run it I
    export LD_LIBRARY_PATH=/tmp/rssguard/lib
    /tmp/rssguard/bin/rssguard

My configuration has "use custom external web browser" checked.  I am using:
Web browser executable:  /usr/bin/firefox       (note:  Firefox  78.5.0esr (64-bit))
Executable parameters:  %1

(note:  I am using the database from RSS Guard - 3.5.9 , the latest provided in my OS repository: Gentoo)

Everything works until I click on a link in the RSS Guard text web browser or hit the hot key to send the article to the external web browser.  Then a new browser window appears (instead of opening a new tab) and it is a firefox window with my defined home page instead of the article.  If I cut the URL from the RSS Guard text web browser page and paste that into the browser window,  the URL is displayed as expected.

Reverting to older RSS Guard for now.

**Comment by martinrotter** [comment] 2020-11-29 17:55
@88mm Yes, I found the regression from earlier versions, fixed in 80c5280c.

Pls test.

**Closed by martinrotter** 2020-11-29 17:55 UTC
Labels: Component-GUI, Status-Fixed, Type-Desktop-Integration, Type-Enhancement

**Comment by 88mm** [comment] 2020-12-01 03:48
The version I just tested, 3.8.3,   db92b9d  works as expected: When I click on a link in the RSSGuard text browser Firefox pops to the foreground, and new tab is opened with the page pointed to by the link from RSSGuard.  Finally RSS Guard pops back to the foreground.    Thanks for the fix.

This change is also compatible with setting  Firefox's about:config browser.tabs.loadDivertedInBackground to True.  In this case Firefox stays in the background and new tabs are opened when you click on a link in RSSGuard.

**Comment by guihkx** [comment] 2020-12-16 09:15
Hi, can you please turn this into an option? I really liked the previous behavior where RSS Guard didn't steal the browser's focus.

Thanks!

**Comment by Johandrex** [comment] 2021-01-08 21:08
> 
> 
> Hi, can you please turn this into an option? I really liked the previous behavior where RSS Guard didn't steal the browser's focus.
> 
> Thanks!

I second that

**Comment by martinrotter** [comment] 2021-01-08 21:26
@Johandrex @guihkx Will do.

**Comment by martinrotter** [comment] 2021-01-08 21:43
It's done.

![image](https://user-images.githubusercontent.com/1255302/104067128-e3314000-5202-11eb-8ff6-92c31d23efac.png)

**Comment by maturz** [comment] 2021-03-09 18:00
This seems to work fine for me (Version: 3.9.0 (built on Windows/x86_64)) if I double click or right click a "message" but focus stays on browser if I right click a link in the preview pane and chose "Open link in external browser".

**Comment by martinrotter** [comment] 2021-03-10 05:33
Hello @maturz I fixed the behavior you describe and the fix will appear in next released version. Thank you.
