### ISSUE TITLE
macOS: Tab close button is on the wrong side

### ISSUE THREAD

**Issue by phedlund** [martinrotter/rssguard#128] opened 2017-07-07 17:41 UTC
#### Brief description of the issue.

Tab close buttons are placed on the right instead of the left side

#### How to reproduce the bug?

1. Open an article in a tab.
2. The close button is on the right side
3. 

#### What is the expected result?

On macOS close buttons are expected to be on the left side

#### What actually happened?

The close button is on the right side

#### Other information (logs, see Wiki)

![screen shot 2017-07-07 at 10 28 02 am](https://user-images.githubusercontent.com/884639/27969718-d370a47a-6300-11e7-8104-300c156caa1e.png)

**Comment by martinrotter** [comment] 2017-07-08 07:20
Those buttons are drawn manually on the right side on all platforms, I will check what I can do.

**Comment by martinrotter** [comment] 2017-07-08 07:35
Probably fixed, please check.

**Comment by phedlund** [comment] 2017-07-09 21:29
Now drawn on the left, but there is an overlap between the favicon and the title. A fancy way of doing this would be to have the favicon turn into a close button when hovering over it with the mouse.

<img width="192" alt="screen shot 2017-07-09 at 2 24 36 pm" src="https://user-images.githubusercontent.com/884639/27997697-e380ad7a-64b2-11e7-9b89-7bd1833cb881.png">

**Comment by martinrotter** [comment] 2017-07-10 05:32
Oh, I see. I will check this out. Actually it is not totally bad idea to turn X icon into favicon if there is one. But it would make sense probably only on Mac OS X because on other platforms this Qt bug is not there, since X buttons are on the right side.

I believe that this is actually Qt bug, and not RSS Guard bug but I will check.

**Comment by martinrotter** [comment] 2017-07-10 05:46
Yes, confirmed Qt bug - https://bugreports.qt.io/browse/QTBUG-61742?jql=text%20~%20%22tab%20icon%20button%22

It seems they have much trouble with icon/button/title of tab rendering.

Maybe. Could it "fix" the situation if the title of the tab would contain some spaces in its beginning? It would probably create some space between the icon and title.

**Comment by martinrotter** [comment] 2017-07-10 06:13
Wait for 	c623da6 gets compiled and then please test, I added two spaces before tab title.

**Comment by martinrotter** [comment] 2017-07-11 05:09
Confirm fixed pls.

**Comment by phedlund** [comment] 2017-07-11 13:56
Yes, this fixes the overlap for now.

**Comment by martinrotter** [comment] 2017-07-13 04:44
OK, I will close this. I also fixed the title for rest of use-cases (tab "Downloads") etc.

**Closed by martinrotter** 2017-07-13 04:44 UTC
Labels: Component-GUI, Status-Partially-Fixed, Type-Enhancement
