### ISSUE TITLE
[BUG]: reader panel resizing not remembered

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#605] opened 2022-01-21 12:20 UTC
### Brief description of the issue

Here's what I set it to:
![image](https://user-images.githubusercontent.com/1309656/150525972-edf6c5ee-2b7d-4515-90ec-d17af92d9de5.png)

And here is what I come back to next day:
![image](https://user-images.githubusercontent.com/1309656/150525950-29ae55dd-79cf-4400-96d6-18e0c08d7c54.png)

### How to reproduce the bug?

restart app?
restart windows?
wait a day?

### What was the expected result?

should be remembered

### What actually happened?

it isn't

### Other information

I use nowebengine

### Operating system and version

* OS: win10 x64
* RSS Guard version: dev

**Comment by peperjohnny** [comment] 2022-01-24 14:51
Can confirm this on linux aswell.

**Comment by martinrotter** [comment] 2022-01-25 11:00
@Owyn Write exact step-by-step procedure to trigger the bug.

**Comment by martinrotter** [comment] 2022-01-25 11:18
@akinokonomi Can you somehow check? I just do not seem to be able to reproduce at all? Also, I remember I "fixed" the bug some weeks ago.

**Comment by martinrotter** [comment] 2022-01-25 11:18
Also, this could be caused by Qt5->Qt6 transition.

Everyone, could you test with stable 4.1.2?

**Comment by Owyn** [comment] 2022-01-25 13:02
> Everyone, could you test with stable 4.1.2?

I noticed this bug first time I tried RSSGuard - so on the stable way before I got a dev build

I always quit the app by clicking red "quit" button

**Comment by akinokonomi** [comment] 2022-01-25 22:02
@martinrotter, Yes, I do see this from time to time. 
I have no reliable steps to reproduce it, though.

> I set it to another than the default setting.
If I quit with Ctrl+Q everything is fine on next restart.
If I quit by restarting computer or killing it via taskmanager it reverts to the default setting once again.
This happens on both arch linux and win10.

Sending either SIGKILL or SIGTERM does not reliably produces the same result. 
Same goes for `xdotool`, `wmctrl`, and `xkill`. Sometimes it happens, but mostly does not. 

(Now tested Qt6 build, but I've experienced this with Qt5 build too.)

**Comment by martinrotter** [comment] 2022-01-26 07:15
I can do whatever I want, just not able to reproduce.

**Comment by martinrotter** [comment] 2022-01-26 07:17
To clarify, we are REALLY talking about "MESSAGE VIEW" / "MESSAGE LIST" splitter?

**Comment by akinokonomi** [comment] 2022-01-26 23:19
> we are REALLY talking about "MESSAGE VIEW" / "MESSAGE LIST" splitter?

**Comment by Owyn** [comment] 2022-01-27 10:05
I've posted two screenshots for it tho, so who cares about the name... 😄 

> reproduce

I think it has something to do with changing setting, because when I was just setting up the program and changing a lot of setting and restarting the app to see changes - bug happened a lot, but now when I just open\close the app and don't change any settings - it seems to be stable and no bug

**Comment by martinrotter** [comment] 2022-01-29 14:46
> and restarting the app to see changes

This could be the problem. The "restart" feature is known to be very buggy and I was thinking about removing it several times.

If it is stable now, closing.There is similar issue with the other divider which i will address too.

**Closed by martinrotter** 2022-01-29 14:46 UTC
Labels: Type-Defect

**Comment by Owyn** [comment] 2022-01-29 14:57
> This could be the problem. 

But not the only one, I definitely exited normally one evening and next morning it was "broken", I didn't use the restart feature

**Comment by Owyn** [comment] 2022-02-08 09:50
bug happened again on:
````
Version: 4.2.0 (built on Windows/AMD64)
Revision: 8cb7c1c4-nowebengine
````

![image](https://user-images.githubusercontent.com/1309656/152961581-d4fcbce4-e53e-4513-b901-d2390deb67ff.png)

I don't think I even changed any settings.... maybe renamed few feed names tho (or was it the day before? can't remember)

**Comment by meelten** [comment] 2022-04-25 11:28
@martinrotter 
I had the same issue (4.1.2 webengine on Linux) and it was driving me crazy because I was not able to reproduce the bug with default settings. Finally discovered what is causing this:

A) "Show unread articles only" has to be toggled.
B) I have to close application using either dedicated "Quit the application" button or Ctrl+Q (which I assume do the same). When I close by clicking "X" on titlebar it remembers size correctly. I have disabled tray icon so clicking "X" actually closes the application (I double checked in process monitor) but there must be some difference how termination is handled.

**Comment by martinrotter** [comment] 2022-04-26 06:08
> @martinrotter I had the same issue (4.1.2 webengine on Linux) and it was driving me crazy because I was not able to reproduce the bug with default settings. Finally discovered what is causing this:
> 
> A) "Show unread articles only" has to be toggled. B) I have to close application using either dedicated "Quit the application" button or Ctrl+Q (which I assume do the same). When I close by clicking "X" on titlebar it remembers size correctly. I have disabled tray icon so clicking "X" actually closes the application (I double checked in process monitor) but there must be some difference how termination is handled.

Retest with 4.2.0 and report back pls.

**Comment by meelten** [comment] 2022-05-05 12:28
> > @martinrotter I had the same issue (4.1.2 webengine on Linux) and it was driving me crazy because I was not able to reproduce the bug with default settings. Finally discovered what is causing this:
> > A) "Show unread articles only" has to be toggled. B) I have to close application using either dedicated "Quit the application" button or Ctrl+Q (which I assume do the same). When I close by clicking "X" on titlebar it remembers size correctly. I have disabled tray icon so clicking "X" actually closes the application (I double checked in process monitor) but there must be some difference how termination is handled.
> 
> Retest with 4.2.0 and report back pls.

Just updated to 4.2.2 and it seems to be fixed.
