### ISSUE TITLE
CPU load 100% when updating feeds

### ISSUE THREAD

**Issue by jluttine** [martinrotter/rssguard#195] opened 2018-08-21 10:23 UTC
#### Brief description of the issue.

I have RSS Guard updating the feeds every hour. Whenever it updates them, CPU load jumps to 100% (for one core) until the update finishes. I have a huge number (thousands) of unread messages, if that might contribute to the issue.

#### How to reproduce the bug?

1. Update feeds (manually or automatically).

#### What is the expected result?

Not-100% CPU load.

#### What actually happened?

100% CPU load.

#### Other information (logs, see Wiki)

Version: 3.5.6 (built on Linux/x86_64)
Qt: 5.11.1 (compiled against 5.11.1)

**Comment by martinrotter** [comment] 2019-04-04 06:49
Well, RSS Guard has separate working thread which handles updates of all feeds. If you update 10 feeds, then this thread updates them one by one in single thread and it can really happen that CPU core gets fully saturated by the work.

I could spread feed updating among more threads but that would lead to spikes on all CPU cores, while their load would be lower.

I do not think there is any advantage in that. Or does temporal 100% CPU core load has any disadvantages for you?

**Comment by jluttine** [comment] 2019-04-04 07:01
My computer gets really jammed when the updates are running. I have 4-core quite powerful laptop and still my programs behave really badly when RSSGuard is updating its feeds.. I was just thinking that is the feed updating expected to be this CPU intensive? I would have expected it to be network bandwidth intensive as it downloads the feeds. I was surprised so I thought it might be a bug. For now, I have just disabled the feed updates and I'll run them manually when I don't want to use my laptop for anything else.

(I have many feeds and they have many posts, and most of them are unread.)

**Comment by martinrotter** [comment] 2019-04-04 08:51
RSS Guard performs these operations during feed update:
- download feed XML file
- parse file
- save new messages to DB file
- repeat the above for each selected feed

None of these tasks is CPU intensive and it actually looks weird, as I do not see behavior you describe on my machines. I hardly even notice that updates are running right now.

Could you export your feed list to OPML file for me? I will import it and try with your exact feeds...

**Comment by Skycoder42** [comment] 2019-04-04 09:27
I can confirm that it happens for me as well. I am using Manjaro Linux with Qt 5.12.2 - however, this issue has been there since quite a while, independently of Kernel, GCC or Qt Version.

I am using the Inoreader plugin to get my feeds, so it might be related to that plugin only.

**Comment by jluttine** [comment] 2019-04-04 09:53
I'm not using any plugins as far as I know. I have all my feeds in my private TinyRSS server and I just sync that account to RSSGuard. Maybe related to that? I'll see about exporting my OPML file if that's helpful even in this TinyRSS case.

**Comment by xmstspider** [comment] 2019-04-12 09:49
I can confirm there are peaks where the main thread (as it seems) takes one whole CPU core. Attached a screenshot from htop.
![scr_rssguard_100](https://user-images.githubusercontent.com/7497125/56028662-e68b5500-5d18-11e9-9066-25707548f601.png)

**Comment by valdotdev** [comment] 2019-10-24 16:45
I can confirm on my end as well. Slow downs when updating feeds. For context, I'm synced to my Inoreader account. CPU temps are 100% and switching between feeds is painfully slow when the update is going on. This will be trouble some for people like me who has dozens of feeds and the app cycles thru them one by one which takes a while.

I'm not an expert on this but I think the method on fetching "new" feeds should be revisited. Maybe fetching the update file by batch/group rather than cycling thru each and every feed?

```
System: Dell XPS 15 7590
OS: Manjaro KDE 18.1.1
```

**Comment by martinrotter** [comment] 2020-05-04 11:56
I plan to completely rewrite the threading logic when downloading feed files with more elaborate testing.

**Comment by martinrotter** [comment] 2020-06-02 04:58
I create merged ticket for similar problems which have probably the same root cause - head over there to discuss or inform me of development on your side.

https://github.com/martinrotter/rssguard/issues/237

**Closed by martinrotter** 2020-06-02 04:58 UTC
