### ISSUE TITLE
[FR]: Open links in external browser

### ISSUE THREAD

**Issue by Rex000** [martinrotter/rssguard#932] opened 2023-05-01 04:25 UTC
### Brief description of the feature request

When we click an article and look at it's preview below in the preview section, any links it contains only open within the built-in browser upon clicking. I would like to request an option to allow those links to open in  external browser.

**Comment by martinrotter** [comment] 2023-05-02 08:13
well, there is tray menu and it has "open link in external browser"

also, there is option in settings to open all links in external browser

![rssguard_cDL46Imjwi](https://user-images.githubusercontent.com/1255302/235614370-2cabdfdd-bbe7-4efb-83ff-9d6db01ab910.png)
![rssguard_mnw3GCEeTv](https://user-images.githubusercontent.com/1255302/235614389-d517cacc-4ddd-4f61-9880-4ecbee5e1d12.png)

**Comment by Rex000** [comment] 2023-05-02 15:43
Yes I have tried that option as well but it doesn't seem to work. Here is an example to elaborate more:
![exmp0](https://user-images.githubusercontent.com/28770012/235715852-6b6bac8e-babe-478f-bf24-047d61fe96bb.jpg)

As you can see there are four links in that article but when I click on any of them, they just open in the internal browser.

**Comment by Rex000** [comment] 2023-05-02 17:29
Yes I have tried that option as well but it doesn't seem to work. Here is an example to elaborate more:
![exmp0](https://user-images.githubusercontent.com/28770012/235740197-bb91dcb0-3927-47ac-af30-a979eeebf760.jpg)

As you can see there are four links in that article but when I click on any of them, they just open in the internal browser.

**Comment by winteriscariot** [comment] 2023-05-08 03:11
i am having the same issue. if i right click the url and 'open in external web browser' it functions as expected, but the settings option doesn't appear to be respected. even with that box ticked it still opens in the internal browser

**Comment by martinrotter** [comment] 2023-06-02 11:24
i was not able to reproduce, provide set of steps to reproduce, closing for now

**Closed by martinrotter** 2023-06-02 11:24 UTC
Labels: Type-Enhancement

**Comment by Rex000** [comment] 2023-06-02 16:53
It now seems to work fine in the latest developmental build.
