### ISSUE TITLE
exit fullscreen from maximize window

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#48] opened 2016-08-03 14:37 UTC
#### Brief description of the issue.

I think window should stay maximize after exit fullsreen when earlier it went to fullscreen from maximized window

#### How to reproduce the bug?

1. maximize window
2. go to fullscreen
3. exit fullscreen

#### What is the expected result?

window in maximized state

#### What actually happened?

its not maximized

**Comment by blackarcher21** [comment] 2016-08-10 09:44
it works but looks like flickering, restore first and then maximize immediately. different issue but quit from fullscreen seems also doing restore first then quit from RSS Guard.

**Comment by martinrotter** [comment] 2016-08-10 10:40
There is no other way.

When you quit fullscreened RSS Guard, it also needs to store its un-fullscreened window size/position. And there is no other way to do it than unfullscreen -> unmaximize -> save size/position.

The only way to avoid flickering would be saving those values immediatelly when user maximizes/restores window, which is also quite tricky.

**Comment by martinrotter** [comment] 2016-08-10 10:51
EDIT: I double checked our options. The flicker cannot be removed. I do it the most appropriate way. In code, I tell the window to go directly to maximized state from fullscreen state. The flickering is maybe caused by underlying OS windows handling.

**Comment by martinrotter** [comment] 2016-08-10 10:53
+ Saving the window state/size/position when app exits is the most efficient way for HDD etc. Saving each time user moves/maximizes/restores window is just not good.

So issue is resolved and the problem we have right now is just cosmetic one?

**Comment by blackarcher21** [comment] 2016-08-10 13:00
yes, it is just cosmetic. :)
sorry once again about comparing with other app, but compare to QuiteRSS regarding GUI behavior, it works as expected. not sure what they do. I hope RSS Guard can also be improved about this.

**Comment by martinrotter** [comment] 2016-08-10 16:49
I will check their code.

**Comment by martinrotter** [comment] 2016-08-13 12:07
Closing this, since all other ways are not as reliable as I would like them to be. :)

**Closed by martinrotter** 2016-08-13 12:07 UTC
Labels: bug, fixed, gui
