### ISSUE TITLE
[BUG]: Very High RAM Usage in RSS database with 200+ feeds

### ISSUE THREAD

**Issue by chromer030** [martinrotter/rssguard#760] opened 2022-06-27 13:24 UTC
### Brief description of the Bug

I have a database with 200-1000 rss feeds , while nothing is going on (fetching, updating ,etc) the software is using very high ram usage , probably a memory leak ?

![Screenshot_20220627_174134](https://user-images.githubusercontent.com/13361552/175950167-c43b6791-06aa-4f27-babc-212949365a29.jpg)

Application on-start :
(Fetch all articles on startup is disabled)

![Screenshot_20220627_180112](https://user-images.githubusercontent.com/13361552/175953935-4aa4d168-9d1a-42e8-97b5-e04205299d96.jpg)

After Exporting the feeds to opml :

![Screenshot_20220627_175955](https://user-images.githubusercontent.com/13361552/175954181-4b6935e4-8b01-4521-a919-02f6b1fdb6bb.jpg)

### How to reproduce the bug?

1- Add more than 200 rss feeds
2- Watch the ram usage

### What was the expected result?

Normal RAM usage.

### What actually happened?

High RAM Usage

### Debug log

[rssguard-ramusage.log](https://github.com/martinrotter/rssguard/files/8992346/rssguard-ramusage.log)

### Operating system and version

* OS:  Arch Linux
* RSS Guard version: 4.2.3 nowebengine
* QT : 6.3.1
* Database Size : database.db 63.6 MiB 
Software is provided via [Arch official repository](https://archlinux.org/packages/community/x86_64/rssguard-nowebengine/)

### Feeds List for testing and reproducing :
1079 tech-related RSS feeds :

[1079.txt](https://github.com/martinrotter/rssguard/files/8993394/1079.txt)

**Comment by chromer030** [comment] 2022-06-28 04:02
Once there was such issue with ViennaRSS , and maybe this helps :
```
I have spent some time investigating this.
The most probable cause is that Vienna has no limit set for undoing mark read/unread actions. 
So ArticleReference objects can be kept for long times…
```

**Comment by meelten** [comment] 2022-06-28 12:18
I just wanted to make new thread but I think it might be related.

Do you use in-memory database option? I recently noticed that when using in-memory database, RAM usage is quite significantly lower than default on-disk setting which makes little sense to me. Whatever you use check the other option and see results.

I have only about 70 feeds and database size is about 30 MB. For me with default setting RSS Guard launches with ~125 MB then jumps to ~170 when starts updating feeds and then gradually grows with further updates and reading articles, so after few hours is sitting on 200-300 MB depending on usage which is pretty high (note that is nowebengine version!).
Now, with in-memory setting it launches with under 120 MB then jumps to ~125 when updating and then grows gradually the same, but it's still 50+ MB lower. Why?

I'm on pretty much the same setup as you, Arch Linux and nowebengine.

**Comment by chromer030** [comment] 2022-06-28 12:46
@meelten 
Thank you very much for your explanation , i do not using in-memory database option , but it seems that i should use it until this huge memory consumption will be fixed.

**Comment by meelten** [comment] 2022-06-28 14:21
> @meelten Thank you very much for your explanation , i do not use in-memory database option , but it seems that i should use it until this huge memory consumption be fixed.

Please report how it looks in your case and if there is noticeable difference.

**Comment by chromer030** [comment] 2022-06-28 15:01
@meelten 
After enabling `In memory database` i have less memory usage in RSS Guard's startup :
![Screenshot_20220628_192748](https://user-images.githubusercontent.com/13361552/176212494-e294153e-e40e-4ad8-86fb-b5e91c300fab.jpg)

500 MiB vs 372 Mib.

My question is , With enabling `In memory database` as the name is stating, we should have more ram usage and with disabling this option we should have less ram usage , why it is contrariwise ?

**Comment by martinrotter** [comment] 2022-06-30 07:35
Hi guys. I am incredibly busy last weeks.

Indeed, what a nice discussion you have here. From a practical POV, it really should be that in-memory DB option should increase used RAM and in-disk option decrease it. You are correct in your assumptions.

> I have only about 70 feeds and database size is about 30 MB.

That's good value.

Btw, those ram usages are just weird. Not the usages itself, but if usage gradually increases over time, it could mean i fucked up somewhere in the code and it leaks.

I will try to do some monitoring and testing in coming days. :)

**Comment by martinrotter** [comment] 2022-06-30 07:37
> Once there was such issue with ViennaRSS , maybe this helps :
> 
> ```
> I have spent some time investigating this.
> The most probable cause is that Vienna has no limit set for undoing mark read/unread actions. 
> So ArticleReference objects can be kept for long times…
> ```

Not likely in our case.

There are several things: One thing is, is RSS Guard behaving fine otherwise? No crashes, freezes? If so, it just seems like a leak. Also, it should be noted that the amount of MBs used from ram can be misleading, because some proportion are Qt libraries and other lib dependecies which cannot be changed (in nonwebengine version, usually loaded deps are smaller).

**Comment by chromer030** [comment] 2022-06-30 08:37
Yes ,RSS Guard behaving fine and it's without any freeze or crash.
It should be a leak.

**Comment by chromer030** [comment] 2022-06-30 13:17
In comparing newsboat (a ncurses-based feed reader) with rssguard , while both using the SQLite 3 , with considering all of libs and dependencies that a GUI app has (QT etc ) , why newsboat is consuming just 30 MB of RAM with same feed list (1000+), and rssguard a large amount of RAM in idle times ? (approximately it should consume 100 or 200 MB of RAM).

Does RSS Guard loads and keeps whole database into memory ?
In most of the times all of feeds,feed lists and features are not needed to be loaded on same time and an on-demand approach would be a better solution.

BTW, really thank you for developing and maintaining this useful and great software.

**Comment by martinrotter** [comment] 2022-07-07 07:47
I see. Can anyone share some big "database.db" files which "trigger" the issue?

**Comment by martinrotter** [comment] 2022-07-07 07:48
> Does RSS Guard loads and keeps whole database into memory ?

Explicitly, no. Underlying SQLite component handles this on its own and should load into memory only and only when "in-memory" DB option is enabled.

**Comment by chromer030** [comment] 2022-07-09 11:43
@martinrotter 
I did some tests , and found where the leak occurs :
I reset everything (previous database and config file) and imported opml and fetched all , while fetching and after that ram usage is normal , starting in 30 MB and gradually increase to ~ 130 MB , even with more than 30,000 unread feeds , but when i click on `mark selected item read` all at once ram usage will jump to 300 MB ! , and every time i click on this option we have even more ram increase, so i think this option and its logic in back-end makes this high ram usage :
![Screenshot_20220709_160559](https://user-images.githubusercontent.com/13361552/178104068-b8152bfd-a196-4d72-815a-fa04c9c1507a.jpg)

**Comment by CsatiZoltan** [comment] 2022-07-21 07:50
> I see. Can anyone share some big "database.db" files which "trigger" the issue?

I could share, as I have a lot of feeds (by the way, where can I get the number of feeds a feed account has ?). For now, I only include a screenshot taken from `htop`:
![Screenshot from 2022-07-21 09-40-19](https://user-images.githubusercontent.com/12742890/180159235-4706e56c-a66f-42e5-ac7f-e1575c9bc8fe.png)

This is under Ubuntu 18.04 with RSS Guard 3.9.2, while the program is not fetching feeds. The corresponding database size is 206 MB.

**Comment by martinrotter** [comment] 2022-08-19 11:36
OK, I did some very brief testing and it seems, that SQLite is doing some memory/disk decisions along the way which influence RAM usage.

Interesting trick would be to try if MariaDB backend suffers from same problems and I would bet it does not.

**Comment by martinrotter** [comment] 2024-05-31 06:10
Closing, old ticket, if the issue is still relevant and causing performance problems, feel free to reopen.

**Closed** 2024-05-31 06:09 UTC
Labels: Type-Defect
