### ISSUE TITLE
[FR]: Should be an option to deactivate a feed

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#347] opened 2021-01-24 22:22 UTC
in the feed properties. Now, even the 
![image](https://user-images.githubusercontent.com/3852762/105645288-55608080-5ea3-11eb-952b-fae6f6e71a62.png)

when clicking the
![image](https://user-images.githubusercontent.com/3852762/105645301-64dfc980-5ea3-11eb-9cff-87d66ce033ff.png)

the item keeps updated.

--

can only get updated when use the **mouse context menu option** 'Download messages..'.

**Comment by martinrotter** [comment] 2021-03-25 05:47
Duplicate of #393

**Closed by martinrotter** 2021-03-25 05:47 UTC
Labels: Type-Enhancement
