### ISSUE TITLE
[BUG]: [KDE] Main window is inaccessible when modal window was active before main window was hidden (via tray icon)

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#418] opened 2021-05-27 06:46 UTC
#### Brief description of the issue.

~~Look below.~~ <ins>Look the title.</ins>
#### How to reproduce the bug?
1. Enable "Hide main window when it is minimized" in "Tray & notifications" settings
2. Click "Minimise" button on "Settings" window
3. Click on tray icon to make the main window visible
4. Observe how Main window does not react  on any click, and Settings window will not be visible

#### What was the expected result?
Settings, or any other sort of secondary window (such as About, Message filters) should actually turn minimised in such situation, keeping Main window untouched.
Otherwise the Minimise button should be removed from such windows.

#### What actually happened?

After click upon tray icon the Main window shows no response, whereas secondary windows stays invisible,

#### Other information

* OS: Arch Linux, KDE
* RSS Guard:
 Version: 3.9.2 (built on Linux/x86_64)
Build date: 4/17/21 8:31 AM
Qt: 5.15.2 (compiled against 5.15.2)

**Comment by martinrotter** [comment] 2021-05-27 06:59
This seems to be DE-specific thing because on Windows such a behavior cannot be reproduced as "minimize" button is correctly disabled on modal windows

![image](https://user-images.githubusercontent.com/1255302/119780086-acb24400-bec9-11eb-8f48-de48831cc6d6.png)

and if I try to hide main window by clicking on tray icon (while modal icon is active) it correctly hides itself and modal window still stays visible.

Which DE you use? Btw thumbs up for Arch, it is my main driver distro on my home station and server too. :)

**Comment by sakkamade** [comment] 2021-05-27 07:03
Ah, sorry, it's KDE.

**Comment by sakkamade** [comment] 2021-05-27 07:08
Seeing this window from Windows...
In KDE, the Close button is not present in such secondary windows, and the only way to close it is to click OK or Cancel at the bottom.

**Comment by martinrotter** [comment] 2021-05-27 07:20
This is what I see:
![image](https://user-images.githubusercontent.com/1255302/119782379-6ad6cd00-becc-11eb-89e4-4838e995372f.png)
Hiding main window in any way when modal window is opened makes the bug trigger. Main window gets subsequently "blocked" and cannot be clicked into.

I am pretty sure that "visibility" of close/max/min button also has something to do if you run app/de on Wayland or X11.

I can control behavior of window to a degree, problem is that the outcome is highly different, depending on platform and/or DE, especially on Linux (sadly).

**Comment by martinrotter** [comment] 2021-05-27 07:21
I will do some tests.

**Comment by sakkamade** [comment] 2021-05-27 07:29
Strange... 
I cannot see Close button whatever I do: Move it to the right side, remove RSS Guard config...
I wonder if it has something to do with qt updates.
Which version of "qt5-base" is now on Manjaro?

X11 by the way.

**Comment by martinrotter** [comment] 2021-05-27 07:38
> 
> 
> Strange...
> I cannot see Close button whatever I do: Move it to the right side, remove RSS Guard config...
> I wonder if it has something to do with qt updates.
> Which version of "qt5-base" is now on Manjaro?
> 
> X11 by the way.
> 
> EDIT: Wait, it's RSS Guard `4.0.0`...

5.15.2

Yes, it is RSS Guard DEVELOPMENT version. You can download it from releases, it is updated within 15 minutes of each source code commit. AppImage is there...

**Comment by sakkamade** [comment] 2021-05-27 07:48
> 5.15.2

And no 5.15.2+kde+r..... ? Or just 5.15.2. But never mind, I very much wonder that this is the cause.

>  You can download it from releases, it is updated within 15 minutes of each source code commit. AppImage is there...

Thanks, will test it tomorrow.

**Comment by martinrotter** [comment] 2021-05-27 07:50
Yes 5.15.2+kde+r192.1

**Comment by sakkamade** [comment] 2021-05-27 21:51
> Hiding main window in any way when modal window is opened makes the bug trigger.

I see, so just hiding Minimise button will not be a solution.

> You can download it from releases,

Sadly there are not no AppImage for Development builds; thankfully there is a script in AUR.
The Close button in secondary windows is present in build with latest commit https://github.com/martinrotter/rssguard/commit/719071a9e8c108f76fddd7850a9f86269281cf6e.

![rss button](https://user-images.githubusercontent.com/62730422/119901431-6db9d800-bf35-11eb-881d-b14e4a4a06f1.png)


> 5.15.2+kde+r192.1

Did not try to downgrade to this version as it is needn't, since the issue is indeed had nothing to do with this.

**Comment by martinrotter** [comment] 2021-05-28 05:06
@sakkamade Yes, builds are broken, let me quick fix. There will be appimage soon.

**Comment by sakkamade** [comment] 2021-05-28 05:17
Sorry for such ping, but there is the question starving for some attention https://github.com/martinrotter/rssguard/issues/416#issuecomment-849455876.

**Comment by martinrotter** [comment] 2021-05-28 09:45
OK, I did some testing (Windows, Linux (Gnome, KDE, MATE), Mac OS X.

Windows, Mac OS X and Gnome and MATE - no problems, it is virtually impossible to replicate buggy behavior.  When you minimize/hide modal window or main window and bring it back, then modal is again displayed if was opened before etc.

The only buggy behavior is on KDE. If you click on tray icon (while any rssguard's modal is shown) then main window is hidden and when clicked again, it is re-shown but not the model. KDE "forgets" about modal.

**Comment by sakkamade** [comment] 2021-05-28 20:51
> Windows, Mac OS X and Gnome and MATE - no problems ... 
> The only buggy behavior is on KDE.

Well, if this is the case, and since the issue is not a critical one, simply add it in "List of known bugs" should be enough?

**Comment by martinrotter** [comment] 2021-05-31 05:14
@sakkamade I will make some more testing on KDE.

**Comment by martinrotter** [comment] 2021-05-31 05:43
@sakkamade

I made a change which tries to detect the situation and disable window hiding unless all modal windows are close first.

![image](https://user-images.githubusercontent.com/1255302/120145492-e5149380-c1e3-11eb-85f1-d122ac420409.png)

I tested on Kubuntu RN and it works okay. Closing.

**Closed by martinrotter** 2021-05-31 05:43 UTC
Labels: Component-GUI, Status-Accepted, Type-Defect

**Comment by sakkamade** [comment] 2021-05-31 05:57
Fixed indeed!
